force-app/main/default/objects/Video__mdt/Video__mdt.object-meta.xml
<CustomObject>
    <label>Video</label>
    <pluralLabel>Videos</pluralLabel>
</CustomObject>

force-app/main/default/objects/Video__mdt/fields/Article_Id__c.field-meta.xml
<CustomField>
    <fullName>Article_Id__c</fullName>
    <description>The Id of the article that is displayed in the link.</description>
    <label>Article Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Video__mdt/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>The Video description.</description>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Video__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>The Video order.</description>
    <label>Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Video__mdt/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The Video title.</description>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Video__mdt/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>The Vidyard UUID.</description>
    <label>UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Video__mdt/fields/Video_URL__c.field-meta.xml
<CustomField>
    <fullName>Video_URL__c</fullName>
    <description>The Vidyard Video URL.</description>
    <label>Video URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VideoCarouselController.cls
public without sharing class VideoCarouselController {
    
    @AuraEnabled(cacheable=true) 
    public static List<VideoWrapper> getVideos(){

        List<VideoWrapper> videoWrappers = new List<VideoWrapper>(); 

        List<Video__mdt> videos = Video__mdt.getAll().values();

        for(Video__mdt video : [Select Id, Title__c, Article_Id__c, Video_URL__c, Description__c, UUID__c, Order__c
                                from Video__mdt order by Order__c]) {
            VideoWrapper vw = new VideoWrapper();
            vw.header = video.Title__c;
            vw.articleId = video.Article_Id__c;
            vw.video = video.Video_URL__c;
            vw.description = video.Description__c;
            vw.uuid = video.UUID__c;
            vw.url = '/article-page?articleId=' + video.Article_Id__c;

            videoWrappers.add(vw);
        }

        return videoWrappers;
    }

    public class VideoWrapper {
        @AuraEnabled
        public String header {get; set;}
        @AuraEnabled
        public String video {get; set;}
        @AuraEnabled
        public String uuid {get; set;}
        @AuraEnabled
        public String description {get; set;}
        @AuraEnabled
        public String articleId {get; set;}
        @AuraEnabled
        public Integer order {get; set;}
        @AuraEnabled
        public String url {get; set;}
    }
}