force-app/main/default/objects/Circle_Account__c/Circle_Account__c.object-meta.xml
<CustomObject>
    <label>Circle Mint</label>
    <nameField>
        <label>Circle Mint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Circle Mints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Circle_Account__c/fields/Account_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Account_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Lookup</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Circle_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <description>Is this a Circle Account Customer or a Merchant Dashboard Customer</description>
    <label>Account Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Accounts_API__c.field-meta.xml
<CustomField>
    <fullName>Accounts_API__c</fullName>
    <label>Accounts API</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First-Party (internal use)</fullName>
            </value>
            <value>
                <fullName>Third-Party</fullName>
            </value>
            <value>
                <fullName>BTC/ETH Beta</fullName>
            </value>
            <value>
                <fullName>Exchange Beta</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Application_Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Submitted_Date__c</fullName>
    <description>Date CA application was submitted.</description>
    <label>Application Submitted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Business_Segment__c.field-meta.xml
<CustomField>
    <fullName>Business_Segment__c</fullName>
    <label>Business Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Business_Website__c.field-meta.xml
<CustomField>
    <fullName>Business_Website__c</fullName>
    <description>Business / Company website or domain</description>
    <label>Business Website</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the associated Circle Account</description>
    <label>Case</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account_Lookup__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case</referenceTo>
    <relationshipName>Circle_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/CeFi_Yield_Application_Status__c.field-meta.xml
<CustomField>
    <fullName>CeFi_Yield_Application_Status__c</fullName>
    <label>CeFi Yield Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Pre-Qualified by Sales</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Pending Submission</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Pending Revision</fullName>
            </value>
            <value>
                <fullName>Pending Signature</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Circle_Account_Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Circle_Account_Application_Status__c</fullName>
    <label>Circle Mint Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Pending Submission</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Pending Revision</fullName>
            </value>
            <value>
                <fullName>Pending Signature</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Sales Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Circle_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Circle_Customer_Id__c</fullName>
    <label>Circle Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Circle_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Core_API__c.field-meta.xml
<CustomField>
    <fullName>Core_API__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Core API</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Country_of_Incorporation__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Incorporation__c</fullName>
    <description>Location of incorporation (Country)</description>
    <label>Country of Incorporation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_of_Incorporation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Cybavo__c.field-meta.xml
<CustomField>
    <fullName>Cybavo__c</fullName>
    <description>Used to identify the type of Cybavo product the customer has.</description>
    <inlineHelpText>Select which Cybavo product the customer has purchased.</inlineHelpText>
    <label>Cybavo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cybavo VAULT</fullName>
            </value>
            <value>
                <fullName>Cybavo Cashflow Manager</fullName>
            </value>
            <value>
                <fullName>Cybavo Wallet SDK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Deposit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Limit__c</fullName>
    <description>What is the customer&apos;s deposit limit.</description>
    <label>Deposit Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Diameter_URL__c.field-meta.xml
<CustomField>
    <fullName>Diameter_URL__c</fullName>
    <label>Diameter - URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Doing_Business_As_DBA__c.field-meta.xml
<CustomField>
    <fullName>Doing_Business_As_DBA__c</fullName>
    <label>Doing Business As (DBA)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Entity_Type_PQ_0__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type_PQ_0__c</fullName>
    <label>Entity Type PQ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Entity_Type_PQ</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Entity_Type_PQ__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type_PQ__c</fullName>
    <label>Entity Type PQ</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>publicCo</fullName>
                <label>Publicly Traded Company</label>
            </value>
            <value>
                <fullName>privateCo</fullName>
                <label>Private company (e.g., LLC, Pvt, Pty, Ltd)</label>
            </value>
            <value>
                <fullName>trust</fullName>
                <label>Trust</label>
            </value>
            <value>
                <fullName>Foundation</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
            <value>
                <fullName>soleTrader</fullName>
                <label>Sole Trader</label>
            </value>
            <value>
                <fullName>associationOrConsortium</fullName>
                <label>Association or Consortium</label>
            </value>
            <value>
                <fullName>coop</fullName>
                <label>Co-operative</label>
            </value>
            <value>
                <fullName>governmentBody</fullName>
                <label>Government Body</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/First_Transaction__c.field-meta.xml
<CustomField>
    <fullName>First_Transaction__c</fullName>
    <label>First Transaction</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/First_Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Transaction_Date__c</fullName>
    <description>First Minting Date</description>
    <label>First Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Hubspot_Circle_Id__c.field-meta.xml
<CustomField>
    <fullName>Hubspot_Circle_Id__c</fullName>
    <externalId>true</externalId>
    <label>Hubspot Circle Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Hubspot_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Hubspot_Created_Date__c</fullName>
    <label>Hubspot Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Last_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Last_Transaction__c</fullName>
    <label>Last Transaction</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Circle_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <label>Legal Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Monthly_Payments_Volume__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Payments_Volume__c</fullName>
    <label>Monthly Payments Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Nature_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Nature_of_Business__c</fullName>
    <label>Nature of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nature_of_Business</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Product_Application_Interest__c.field-meta.xml
<CustomField>
    <fullName>Product_Application_Interest__c</fullName>
    <label>Product Application Interest</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>account</fullName>
                <label>Circle Account</label>
            </value>
            <value>
                <fullName>yield</fullName>
                <label>Circle Yield</label>
            </value>
            <value>
                <fullName>api</fullName>
                <label>Circle APIs</label>
            </value>
            <value>
                <fullName>Circle APIs</fullName>
                <isActive>false</isActive>
                <label>Circle APIs</label>
            </value>
            <value>
                <fullName>Circle Account</fullName>
                <isActive>false</isActive>
                <label>Circle Account</label>
            </value>
            <value>
                <fullName>Circle Yield</fullName>
                <isActive>false</isActive>
                <label>Circle Yield</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/State_of_Incorporation__c.field-meta.xml
<CustomField>
    <fullName>State_of_Incorporation__c</fullName>
    <label>State of Incorporation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Withdrawal_Limit__c.field-meta.xml
<CustomField>
    <fullName>Withdrawal_Limit__c</fullName>
    <description>What is the customer&apos;s withdrawal limit.</description>
    <label>Withdrawal Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CircleAccountWebService.cls
@RestResource(urlMapping='/CircleAccount/*')
global class CircleAccountWebService {

    @HttpPost
    global static void upsertCircleAccount(CircleAccountWrapper properties) {
        RestResponse res = RestContext.response;
        Map<String, String> mapResponse = new Map<String, String>();
        try{
            Circle_Account__c circleAccount = new Circle_Account__c();
            if(properties.circleEntityId != null){
                List<Circle_Account__c> circleAccounts = CircleAccountDAO.getCircleAccountByID(properties.circleEntityId);
                if(circleAccounts.size() > 0){
                    circleAccount = circleAccounts.get(0);
                }
            }
            circleAccount.Legal_Entity_Name__c = properties.legalEntityName != null ? properties.legalEntityName : circleAccount.Legal_Entity_Name__c;
            circleAccount.Name = properties.name != null ? properties.name : circleAccount.Name;
            if(circleAccount.Name != null && circleAccount.Name.length()>79){
                circleAccount.Name = circleAccount.Name.left(79);
            }
            circleAccount.Withdrawal_Limit__c = properties.withdrawalLimit != null ? properties.withdrawalLimit : circleAccount.Withdrawal_Limit__c;
            circleAccount.Account_Lookup__c = properties.accountId != null ? properties.accountId : circleAccount.Account_Lookup__c;
            circleAccount.Contact__c = properties.contactId != null ? properties.contactId : circleAccount.Contact__c;
            circleAccount.Lead__c = properties.leadId != null ? properties.leadId : circleAccount.Lead__c;
            circleAccount.Case__c = properties.caseId != null ? properties.caseId : circleAccount.Case__c;
            circleAccount.Diameter_URL__c = properties.diameterURL != null ? properties.diameterURL : circleAccount.Diameter_URL__c;
            circleAccount.Business_Website__c = properties.businessWebsite != null ? properties.businessWebsite : circleAccount.Business_Website__c;
            circleAccount.State_of_Incorporation__c = properties.stateOfIncorporation != null ? properties.stateOfIncorporation : circleAccount.State_of_Incorporation__c;
            circleAccount.Product_Application_Interest__c = properties.productApplicationInterest != null ? properties.productApplicationInterest : circleAccount.Product_Application_Interest__c;
            circleAccount.Country_of_Incorporation__c = properties.countryOfIncorporation != null ? properties.countryOfIncorporation : circleAccount.Country_of_Incorporation__c;
            circleAccount.Entity_Type_PQ__c = properties.entityTypePQ != null ? properties.entityTypePQ : circleAccount.Entity_Type_PQ__c;
            circleAccount.Circle_Account_Application_Status__c = properties.circleAccountApplicationStatus != null ? properties.circleAccountApplicationStatus : circleAccount.Circle_Account_Application_Status__c;
            circleAccount.Nature_of_Business__c = properties.natureOfBusiness != null ? properties.natureOfBusiness : circleAccount.Nature_of_Business__c;
            circleAccount.CeFi_Yield_Application_Status__c = properties.ceFiYieldApplicationStatus != null ? properties.ceFiYieldApplicationStatus : circleAccount.CeFi_Yield_Application_Status__c;
            circleAccount.Circle_Customer_Id__c = properties.circleCustomerId != null ? properties.circleCustomerId : circleAccount.Circle_Customer_Id__c;
            circleAccount.Account_Type__c = properties.accountType != null ? properties.accountType : circleAccount.Account_Type__c;
            circleAccount.Accounts_API__c = properties.accountsApi != null ? properties.accountsApi : circleAccount.Accounts_API__c;
            circleAccount.Application_Submitted_Date__c = properties.applicationSubmittedDate != null ? properties.applicationSubmittedDate : circleAccount.Application_Submitted_Date__c;
            circleAccount.Business_Segment__c = properties.businessSegment != null ? properties.businessSegment : circleAccount.Business_Segment__c;
            circleAccount.Core_API__c = properties.coreApi != null ? properties.coreApi : circleAccount.Core_API__c;
            circleAccount.Doing_Business_As_DBA__c = properties.doingBusinessAsDBA != null ? properties.doingBusinessAsDBA : circleAccount.Doing_Business_As_DBA__c;
            circleAccount.Cybavo__c = properties.cybavo != null ? properties.cybavo : circleAccount.Cybavo__c;
            circleAccount.Deposit_Limit__c = properties.depositLimit != null ? properties.depositLimit : circleAccount.Deposit_Limit__c;
            circleAccount.Entity_Type_PQ_0__c = properties.entityTypePQ != null ? properties.entityTypePQ : circleAccount.Entity_Type_PQ_0__c;
            circleAccount.First_Transaction__c = properties.firstTransaction != null ? properties.firstTransaction : circleAccount.First_Transaction__c;
            circleAccount.First_Transaction_Date__c = properties.firstTransactionDate != null ? properties.firstTransactionDate : circleAccount.First_Transaction_Date__c;
            circleAccount.Hubspot_Circle_Id__c = properties.hubspotCircleId != null ? properties.hubspotCircleId : circleAccount.Hubspot_Circle_Id__c;
            circleAccount.Hubspot_Created_Date__c = properties.hubspotCreatedDate != null ? properties.hubspotCreatedDate : circleAccount.Hubspot_Created_Date__c;
            circleAccount.Last_Transaction__c = properties.lastTransaction != null ? properties.lastTransaction : circleAccount.Last_Transaction__c;
            circleAccount.Monthly_Payments_Volume__c = properties.monthlyPaymentsVolume != null ? properties.monthlyPaymentsVolume : circleAccount.Monthly_Payments_Volume__c;
            circleAccount.Payments_API__c = properties.paymentsApi != null ? properties.paymentsApi : circleAccount.Payments_API__c;
            circleAccount.Payouts_API__c = properties.payoutsApi != null ? properties.payoutsApi : circleAccount.Payouts_API__c;
            circleAccount.Read_Only_API__c = properties.readOnlyApi != null ? properties.readOnlyApi : circleAccount.Read_Only_API__c;
            circleAccount.SEN__c = properties.sen != null ? properties.sen : circleAccount.SEN__c;
            circleAccount.Signet__c = properties.signet != null ? properties.signet : circleAccount.Signet__c;
            circleAccount.USDC_Express__c = properties.usdcExpress != null ? properties.usdcExpress : circleAccount.USDC_Express__c;
            circleAccount.USDC_Express_Tokenization__c = properties.usdcExpressTokenization != null ? properties.usdcExpressTokenization : circleAccount.USDC_Express_Tokenization__c;
            circleAccount.Expected_Minting_Volume_Monthly__c = properties.expectedMintingVolumeMonthly != null ? properties.expectedMintingVolumeMonthly : circleAccount.Expected_Minting_Volume_Monthly__c;
            circleAccount.Active_Users_On_Platform__c = properties.activeUsersOnPlatform != null ? properties.activeUsersOnPlatform : circleAccount.Active_Users_On_Platform__c;
            circleAccount.Use_Case__c = properties.useCase != null ? properties.useCase : circleAccount.Use_Case__c;
            circleAccount.Weekly_Payments_Volume__c = properties.weeklyPaymentsVolume != null ? properties.weeklyPaymentsVolume : circleAccount.Weekly_Payments_Volume__c;
            circleAccount.Yield_Application_Approved_Date__c = properties.yieldApplicationApprovedDate != null ? properties.yieldApplicationApprovedDate : circleAccount.Yield_Application_Approved_Date__c;
            circleAccount.USDC_Rewards_Application_Status__c = properties.usdcRewardsApplicationStatus != null ? properties.usdcRewardsApplicationStatus : circleAccount.USDC_Rewards_Application_Status__c;
            circleAccount.Email_Verified__c = properties.emailVerified != null ? properties.emailVerified : circleAccount.Email_Verified__c;
            circleAccount.Circle_Account_Qualification_Status__C = properties.circleAccountQualificationStatus != null ? properties.circleAccountQualificationStatus : circleAccount.Circle_Account_Qualification_Status__C;
            if(circleAccount.id != null){
                update circleAccount;
                mapResponse.put('message', circleAccount.Id + ' Updated Successfully');
            }     
            else{ 
                circleAccount.Circle_Entity_Id__c = properties.circleEntityId;
                insert circleAccount;
                mapResponse.put('message', circleAccount.Id + ' Inserted Successfully');
            }
            res.responseBody = Blob.valueOf(JSON.serialize(mapResponse));
            res.statusCode = 200;
        }
        catch(Exception e){
            mapResponse.put('message', e.getMessage());
            res.responseBody = Blob.valueOf(JSON.serialize(mapResponse));
            res.statusCode = 500;
        }
    }
}