force-app/main/default/objects/Circle_Account__c/Circle_Account__c.object-meta.xml
<CustomObject>
    <label>Circle Mint</label>
    <nameField>
        <label>Circle Mint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Circle Mints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Circle_Account__c/fields/Account_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Account_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Lookup</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Circle_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RollUpCircleAccountMetricsBatch.cls
global class RollUpCircleAccountMetricsBatch implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT ID,Account_Lookup__c FROM Circle_Account__c';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Circle_Account__c> circleAccounts) {
        Set<Id> accountIds = new Set<Id>();
        for(Circle_Account__c ca : circleAccounts){
            accountIds.add(ca.Account_Lookup__c);
        }
        Accounts.rollUpAccountMetrics(accountIds);
    }
     
    global void finish(Database.BatchableContext bc) {
    }
}