force-app/main/default/objects/Partnership_Objective__c/Partnership_Objective__c.object-meta.xml
<CustomObject>
    <description>Track the key objectives of our customer relationships</description>
    <label>Partnership Objective</label>
    <nameField>
        <label>Partnership Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnership Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partnership_Objective__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field should auto-populate, but should be checked to ensure that the correct Salesforce Account is associated with the Partnership Objective</description>
    <inlineHelpText>This field should auto-populate, but should be checked to ensure that the correct Salesforce Account is associated with the Partnership Objective</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partnership Objectives</relationshipLabel>
    <relationshipName>Partnership_Objectives</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Current_MEWs__c.field-meta.xml
<CustomField>
    <fullName>Current_MEWs__c</fullName>
    <description>This field should include the current number of meaningful wallets</description>
    <inlineHelpText>This field should include the current number of meaningful wallets</inlineHelpText>
    <label>Current MEWs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Current_Stablecoin_Liquidity__c.field-meta.xml
<CustomField>
    <fullName>Current_Stablecoin_Liquidity__c</fullName>
    <description>Current total amount of USDC held on platform.</description>
    <inlineHelpText>Current total amount of USDC held on platform.</inlineHelpText>
    <label>Current Stablecoins on Platform</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Current_Stablecoin_Volume__c.field-meta.xml
<CustomField>
    <fullName>Current_Stablecoin_Volume__c</fullName>
    <description>Aggregate stablecoin transaction volume since the beginning of the objective</description>
    <inlineHelpText>Aggregate stablecoin transaction volume since the beginning of the objective</inlineHelpText>
    <label>Current Stablecoin Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/MeWs_Growth__c.field-meta.xml
<CustomField>
    <fullName>MeWs_Growth__c</fullName>
    <description>Incremental MeWs added since the start of the objective</description>
    <formula>IF(
   AND(!ISBLANK(Current_MEWs__c), !ISBLANK(Starting_MEWs__c)),
   Current_MEWs__c - Starting_MEWs__c,
   null
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Incremental MeWs added since the start of the objective</inlineHelpText>
    <label>MeWs Growth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Projected_MeWs_Growth__c.field-meta.xml
<CustomField>
    <fullName>Projected_MeWs_Growth__c</fullName>
    <description>Projected incremental MeWs added during the timeframe of the objective</description>
    <inlineHelpText>Projected incremental MeWs added during the timeframe of the objective</inlineHelpText>
    <label>Projected MeWs Growth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Projected_Stablecoin_On_Platform_Growth__c.field-meta.xml
<CustomField>
    <fullName>Projected_Stablecoin_On_Platform_Growth__c</fullName>
    <description>Projected incremental stablecoin on platform growth during the timeframe of the objective</description>
    <inlineHelpText>Projected incremental stablecoin on platform growth during the timeframe of the objective</inlineHelpText>
    <label>Projected Stablecoin On Platform Growth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Projected_Total_Stablecoin_Volume__c.field-meta.xml
<CustomField>
    <fullName>Projected_Total_Stablecoin_Volume__c</fullName>
    <description>Projected aggregate stablecoin transaction volume during the timeframe of the objective</description>
    <inlineHelpText>Projected aggregate stablecoin transaction volume during the timeframe of the objective</inlineHelpText>
    <label>Projected Total Stablecoin Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Stablecoin__c.field-meta.xml
<CustomField>
    <fullName>Stablecoin__c</fullName>
    <description>This field should indicate USDC in most cases, but for certain opportunities, the Partnership Objective will focus on the growth of EUROC or other stablecoins in the future</description>
    <inlineHelpText>This field should indicate USDC in most cases, but for certain opportunities, the Partnership Objective will focus on the growth of EUROC or other stablecoins in the future</inlineHelpText>
    <label>Stablecoin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USDC</fullName>
            </value>
            <value>
                <fullName>EURC</fullName>
            </value>
            <value>
                <fullName>EUROC</fullName>
                <isActive>false</isActive>
                <label>EUROC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Stablecoin_On_Platform_Growth__c.field-meta.xml
<CustomField>
    <fullName>Stablecoin_On_Platform_Growth__c</fullName>
    <description>Incremental stablecoin balance added since the start of the objective</description>
    <formula>IF(
   AND(!ISBLANK(Current_Stablecoin_Liquidity__c), !ISBLANK(Starting_Stablecoin_Liquidity__c)),
   Current_Stablecoin_Liquidity__c -  Starting_Stablecoin_Liquidity__c
   ,
   null
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Incremental stablecoin balance added since the start of the objective</inlineHelpText>
    <label>Stablecoin On Platform Growth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Stablecoin_Volume_Growth__c.field-meta.xml
<CustomField>
    <fullName>Stablecoin_Volume_Growth__c</fullName>
    <formula>IF(
   AND(!ISBLANK(Current_Stablecoin_Volume__c), !ISBLANK(Starting_Stablecoin_Volume__c)),
   Current_Stablecoin_Volume__c -  Starting_Stablecoin_Volume__c,
   null
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Stablecoin Volume Growth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Starting_MEWs__c.field-meta.xml
<CustomField>
    <fullName>Starting_MEWs__c</fullName>
    <description>This field should include the number of meaningful wallets prior to any incentive deal</description>
    <inlineHelpText>This field should include the number of meaningful wallets prior to any incentive deal</inlineHelpText>
    <label>Starting MEWs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Starting_Stablecoin_Liquidity__c.field-meta.xml
<CustomField>
    <fullName>Starting_Stablecoin_Liquidity__c</fullName>
    <description>Total amount of USDC held on platform at the Objective Start Date.</description>
    <inlineHelpText>Total amount of USDC held on platform at the Objective Start Date.</inlineHelpText>
    <label>Starting Stablecoins on Platform</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Starting_Stablecoin_Volume__c.field-meta.xml
<CustomField>
    <fullName>Starting_Stablecoin_Volume__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Average monthly Stablecoin transaction volume</description>
    <inlineHelpText>Average monthly Stablecoin transaction volume</inlineHelpText>
    <label>Starting Stablecoin Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Success_Metrics__c.field-meta.xml
<CustomField>
    <fullName>Success_Metrics__c</fullName>
    <description>These are the metrics from the Partnership Construct by which we will determine the success of the Opportunity.</description>
    <formula>IF(
   AND(
      !ISBLANK(Opportunity__c),
      !ISBLANK(Opportunity__r.Success_Metrics__c)
   ),
   LEFT(
      IF ( INCLUDES ( Opportunity__r.Success_Metrics__c , &quot;MEWs&quot; ), &quot;MEWs, &quot;,null ) &amp;
      IF ( INCLUDES ( Opportunity__r.Success_Metrics__c , &quot;USDC On Platform&quot; ), &quot;USDC On Platform, &quot;,null ) &amp;
      IF ( INCLUDES ( Opportunity__r.Success_Metrics__c , &quot;Transaction Volume&quot; ), &quot;Transaction Volume, &quot;,null ) &amp;
      IF ( INCLUDES ( Opportunity__r.Success_Metrics__c , &quot;Other&quot; ), &quot;Other, &quot;,null),
      LEN(
         IF( INCLUDES ( Opportunity__r.Success_Metrics__c , &quot;MEWs&quot; ), &quot;MEWs, &quot;,null ) &amp;
         IF ( INCLUDES ( Opportunity__r.Success_Metrics__c , &quot;USDC On Platform&quot; ), &quot;USDC On Platform, &quot;,null ) &amp;
         IF ( INCLUDES ( Opportunity__r.Success_Metrics__c , &quot;Transaction Volume&quot; ), &quot;Transaction Volume, &quot;,null ) &amp;
         IF ( INCLUDES ( Opportunity__r.Success_Metrics__c , &quot;Other&quot; ), &quot;Other, &quot;,null)
      )-2
   )
,null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>These are the metrics from the Partnership Construct by which we will determine the success of the Opportunity.</inlineHelpText>
    <label>Success Metrics</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This field is used by CSMs to separate Partner Objectives</description>
    <inlineHelpText>Keep the default for specific Partnership Objectives. Switch to Partner Metrics Tracking to track starting and current metrics.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Objective Tracking</fullName>
            </value>
            <value>
                <fullName>Partner Metrics Tracking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RollUpPartnershipObjectivesBatch.cls
global class RollUpPartnershipObjectivesBatch implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT ID,Account__c,Type__c,Current_Stablecoin_Liquidity__c,Current_MEWs__c,Current_Stablecoin_Volume__c,Projected_MeWs_Growth__c,Mews_Growth__c, Stablecoin_On_Platform_Growth__c, Stablecoin_Volume_Growth__c, Projected_Total_Stablecoin_Volume__c,Projected_Stablecoin_on_Platform_Growth__c,Stablecoin__c, Success_Metrics__c, Starting_Mews__C, Starting_Stablecoin_liquidity__c, Starting_Stablecoin_Volume__c FROM Partnership_Objective__c';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Partnership_Objective__c> objectives) {
        Set<Id> accountIds = new Set<Id>();
        Set<Partnership_Objective__c> objectivesToRecalculate = new Set<Partnership_Objective__c>();
        for(Partnership_objective__c objective : objectives){
            accountIds.add(objective.Account__c);
            if(objective.Type__c =='Partner Metrics Tracking'){
                objectivesToRecalculate.add(objective);
            }
        }
        Accounts.rollUpAccountMetrics(accountIds);
        if(objectivesToRecalculate.size()>0){
            PartnershipObjectives.rollUpPOMetrics(objectivesToRecalculate);
            List<Partnership_Objective__c> objectivesToUpdate = new List<Partnership_Objective__c>();
            objectivesToUpdate.addAll(objectivesToRecalculate);
            update objectivesToUpdate;
        }
    }
     
    global void finish(Database.BatchableContext bc) {
    }
}