force-app/main/default/objects/Partnership_Objective__c/Partnership_Objective__c.object-meta.xml
<CustomObject>
    <description>Track the key objectives of our customer relationships</description>
    <label>Partnership Objective</label>
    <nameField>
        <label>Partnership Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnership Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partnership_Objective__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field should auto-populate, but should be checked to ensure that the correct Salesforce Account is associated with the Partnership Objective</description>
    <inlineHelpText>This field should auto-populate, but should be checked to ensure that the correct Salesforce Account is associated with the Partnership Objective</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partnership Objectives</relationshipLabel>
    <relationshipName>Partnership_Objectives</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Current_MEWs__c.field-meta.xml
<CustomField>
    <fullName>Current_MEWs__c</fullName>
    <description>This field should include the current number of meaningful wallets</description>
    <inlineHelpText>This field should include the current number of meaningful wallets</inlineHelpText>
    <label>Current MEWs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Current_Stablecoin_Liquidity__c.field-meta.xml
<CustomField>
    <fullName>Current_Stablecoin_Liquidity__c</fullName>
    <description>Current total amount of USDC held on platform.</description>
    <inlineHelpText>Current total amount of USDC held on platform.</inlineHelpText>
    <label>Current Stablecoins on Platform</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Current_Stablecoin_Volume__c.field-meta.xml
<CustomField>
    <fullName>Current_Stablecoin_Volume__c</fullName>
    <description>Aggregate stablecoin transaction volume since the beginning of the objective</description>
    <inlineHelpText>Aggregate stablecoin transaction volume since the beginning of the objective</inlineHelpText>
    <label>Current Stablecoin Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Custom_Metric__c.field-meta.xml
<CustomField>
    <fullName>Custom_Metric__c</fullName>
    <description>(Numerical Values Only) Current value of the Success Metric Details.</description>
    <inlineHelpText>(Numerical Values Only) Current value of the Success Metric Details.</inlineHelpText>
    <label>Custom Metric</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Growth__c.field-meta.xml
<CustomField>
    <fullName>Growth__c</fullName>
    <label>Growth</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/MeWs_Growth__c.field-meta.xml
<CustomField>
    <fullName>MeWs_Growth__c</fullName>
    <description>Incremental MeWs added since the start of the objective</description>
    <formula>IF(
   AND(!ISBLANK(Current_MEWs__c), !ISBLANK(Starting_MEWs__c)),
   Current_MEWs__c - Starting_MEWs__c,
   null
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Incremental MeWs added since the start of the objective</inlineHelpText>
    <label>MeWs Growth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Objective_Status__c.field-meta.xml
<CustomField>
    <fullName>Objective_Status__c</fullName>
    <description>This field should indicate the most current status of the objective based on the goals defined, the current progress, and the planned completion</description>
    <inlineHelpText>This field should indicate the most current status of the objective based on the goals defined, the current progress, and the planned completion</inlineHelpText>
    <label>Objective Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onboarding</fullName>
                <color>#F3D904</color>
                <label>Onboarding</label>
            </value>
            <value>
                <fullName>Pre-Launch</fullName>
                <color>#E27001</color>
                <label>Pre-Launch</label>
            </value>
            <value>
                <fullName>Launched</fullName>
                <color>#419249</color>
                <label>Launched</label>
            </value>
            <value>
                <fullName>Not Active</fullName>
                <color>#BBBBBB</color>
                <label>Not Active</label>
            </value>
            <value>
                <fullName>At Risk</fullName>
                <isActive>false</isActive>
                <label>At Risk</label>
            </value>
            <value>
                <fullName>Exceeded Expectations</fullName>
                <isActive>false</isActive>
                <label>Exceeded Expectations</label>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <isActive>false</isActive>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Objective Not Met</fullName>
                <isActive>false</isActive>
                <label>Objective Not Met</label>
            </value>
            <value>
                <fullName>Off Track</fullName>
                <isActive>false</isActive>
                <label>Off Track</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <isActive>false</isActive>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>On Track</fullName>
                <isActive>false</isActive>
                <label>On Track</label>
            </value>
            <value>
                <fullName>Successful</fullName>
                <isActive>false</isActive>
                <label>Successful</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Performance_Objective_Health__c.field-meta.xml
<CustomField>
    <fullName>Performance_Objective_Health__c</fullName>
    <inlineHelpText>Please use the Update Objective Health button (top right) to update this field.</inlineHelpText>
    <label>Partnership Objective Health</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <color>#999999</color>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Off Track</fullName>
                <color>#CC0000</color>
                <label>Off Track</label>
            </value>
            <value>
                <fullName>At Risk</fullName>
                <color>#FF6600</color>
                <label>At Risk</label>
            </value>
            <value>
                <fullName>On Track</fullName>
                <color>#33CC00</color>
                <label>On Track</label>
            </value>
            <value>
                <fullName>Objective Not Met</fullName>
                <color>#660000</color>
                <label>Objective Not Met</label>
            </value>
            <value>
                <fullName>Successful</fullName>
                <color>#009900</color>
                <label>Successful</label>
            </value>
            <value>
                <fullName>Exceeded Expectations</fullName>
                <color>#006600</color>
                <label>Exceeded Expectations</label>
            </value>
            <value>
                <fullName>Incorrect Hypothesis</fullName>
                <isActive>false</isActive>
                <label>Incorrect Hypothesis</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <isActive>false</isActive>
                <label>On Hold</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Projected_MeWs_Growth__c.field-meta.xml
<CustomField>
    <fullName>Projected_MeWs_Growth__c</fullName>
    <description>Projected incremental MeWs added during the timeframe of the objective</description>
    <inlineHelpText>Projected incremental MeWs added during the timeframe of the objective</inlineHelpText>
    <label>Projected MeWs Growth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Projected_Stablecoin_On_Platform_Growth__c.field-meta.xml
<CustomField>
    <fullName>Projected_Stablecoin_On_Platform_Growth__c</fullName>
    <description>Projected incremental stablecoin on platform growth during the timeframe of the objective</description>
    <inlineHelpText>Projected incremental stablecoin on platform growth during the timeframe of the objective</inlineHelpText>
    <label>Projected Stablecoin On Platform Growth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Projected_Total_Stablecoin_Volume__c.field-meta.xml
<CustomField>
    <fullName>Projected_Total_Stablecoin_Volume__c</fullName>
    <description>Projected aggregate stablecoin transaction volume during the timeframe of the objective</description>
    <inlineHelpText>Projected aggregate stablecoin transaction volume during the timeframe of the objective</inlineHelpText>
    <label>Projected Total Stablecoin Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Stablecoin__c.field-meta.xml
<CustomField>
    <fullName>Stablecoin__c</fullName>
    <description>This field should indicate USDC in most cases, but for certain opportunities, the Partnership Objective will focus on the growth of EUROC or other stablecoins in the future</description>
    <inlineHelpText>This field should indicate USDC in most cases, but for certain opportunities, the Partnership Objective will focus on the growth of EUROC or other stablecoins in the future</inlineHelpText>
    <label>Stablecoin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USDC</fullName>
            </value>
            <value>
                <fullName>EURC</fullName>
            </value>
            <value>
                <fullName>EUROC</fullName>
                <isActive>false</isActive>
                <label>EUROC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Stablecoin_On_Platform_Growth__c.field-meta.xml
<CustomField>
    <fullName>Stablecoin_On_Platform_Growth__c</fullName>
    <description>Incremental stablecoin balance added since the start of the objective</description>
    <formula>IF(
   AND(!ISBLANK(Current_Stablecoin_Liquidity__c), !ISBLANK(Starting_Stablecoin_Liquidity__c)),
   Current_Stablecoin_Liquidity__c -  Starting_Stablecoin_Liquidity__c
   ,
   null
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Incremental stablecoin balance added since the start of the objective</inlineHelpText>
    <label>Stablecoin On Platform Growth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Stablecoin_Volume_Growth__c.field-meta.xml
<CustomField>
    <fullName>Stablecoin_Volume_Growth__c</fullName>
    <formula>IF(
   AND(!ISBLANK(Current_Stablecoin_Volume__c), !ISBLANK(Starting_Stablecoin_Volume__c)),
   Current_Stablecoin_Volume__c -  Starting_Stablecoin_Volume__c,
   null
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Stablecoin Volume Growth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Starting_MEWs__c.field-meta.xml
<CustomField>
    <fullName>Starting_MEWs__c</fullName>
    <description>This field should include the number of meaningful wallets prior to any incentive deal</description>
    <inlineHelpText>This field should include the number of meaningful wallets prior to any incentive deal</inlineHelpText>
    <label>Starting MEWs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Starting_Stablecoin_Liquidity__c.field-meta.xml
<CustomField>
    <fullName>Starting_Stablecoin_Liquidity__c</fullName>
    <description>Total amount of USDC held on platform at the Objective Start Date.</description>
    <inlineHelpText>Total amount of USDC held on platform at the Objective Start Date.</inlineHelpText>
    <label>Starting Stablecoins on Platform</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Starting_Stablecoin_Volume__c.field-meta.xml
<CustomField>
    <fullName>Starting_Stablecoin_Volume__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Average monthly Stablecoin transaction volume</description>
    <inlineHelpText>Average monthly Stablecoin transaction volume</inlineHelpText>
    <label>Starting Stablecoin Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This field is used by CSMs to separate Partner Objectives</description>
    <inlineHelpText>Keep the default for specific Partnership Objectives. Switch to Partner Metrics Tracking to track starting and current metrics.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Objective Tracking</fullName>
            </value>
            <value>
                <fullName>Partner Metrics Tracking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PartnershipObjectives.cls
public with sharing class PartnershipObjectives {

    public static void recalculateAccountRollUpFields(Map<Id, Partnership_Objective__c> newObjectives, Map<Id, Partnership_Objective__c> oldObjectives){
        Set<Id> accountIdsToRollUp = new Set<Id>();
        for(Id id : newObjectives.keyset()){
            if(oldObjectives != null){
                if((newObjectives.get(id).Performance_Objective_Health__c != oldObjectives.get(id).Performance_Objective_Health__c || newObjectives.get(id).Account__c != oldObjectives.get(id).Account__c 
                    || newObjectives.get(id).Objective_Status__c != oldObjectives.get(id).Objective_Status__c) && newObjectives.get(id).Type__c == 'Partner Metrics Tracking'){
                        accountIdsToRollUp.add(newObjectives.get(id).Account__c);
                    }
            }
            else{
                if((newObjectives.get(id).Performance_Objective_Health__c != null || newObjectives.get(id).Objective_Status__c != null ) && newObjectives.get(id).Type__c == 'Partner Metrics Tracking' && newObjectives.get(id).Account__c != null){
                    accountIdsToRollUp.add(newObjectives.get(id).Account__c);
                }
            }
        }
        if(accountIdsToRollUp.size()>0){
            Accounts.rollUpAccountMetrics(accountIdsToRollUp);
        }
    }

    public static void recalculatePORollUpFields(Map<Id, Partnership_Objective__c> newObjectives, Map<Id, Partnership_Objective__c> oldObjectives){
        Set<Partnership_Objective__c> partnershipMetricsNeedRollUp = new Set<Partnership_Objective__c>();
        for(Id id : newObjectives.keyset()){
            if((newObjectives.get(id).Current_Stablecoin_Liquidity__c != oldObjectives.get(id).Current_Stablecoin_Liquidity__c || newObjectives.get(id).Current_MEWs__c != oldObjectives.get(id).Current_MEWs__c 
                || newObjectives.get(id).Current_Stablecoin_Volume__c != oldObjectives.get(id).Current_Stablecoin_Volume__c || newObjectives.get(id).Projected_MeWs_Growth__c != oldObjectives.get(id).Projected_MeWs_Growth__c
                || newObjectives.get(id).Projected_Total_Stablecoin_Volume__c != oldObjectives.get(id).Projected_Total_Stablecoin_Volume__c || newObjectives.get(id).Projected_Stablecoin_on_Platform_Growth__c != oldObjectives.get(id).Projected_Stablecoin_on_Platform_Growth__c
                || newObjectives.get(id).Custom_Metric__c != oldObjectives.get(id).Custom_Metric__c || newObjectives.get(id).Starting_Mews__C !=oldObjectives.get(id).Starting_mews__c || newObjectives.get(id).Starting_Stablecoin_Volume__c !=oldObjectives.get(id).Starting_Stablecoin_Volume__c 
                || newObjectives.get(id).Starting_stablecoin_Liquidity__C !=oldObjectives.get(id).Starting_stablecoin_Liquidity__C)
                && newObjectives.get(id).Type__c == 'Partner Metrics Tracking'){
                    partnershipMetricsNeedRollUp.add(newObjectives.get(id));
            }
        }

        if(partnershipMetricsNeedRollUp.size()>0){
            rollUpPOMetrics(partnershipMetricsNeedRollUp);
        }
    }

    public static void recalculatePORollUpFields(List<Partnership_Objective__c> newObjectives){
        Set<Partnership_Objective__c> partnershipMetricsNeedRollUp = new Set<Partnership_Objective__c>();
        for(Partnership_Objective__c po : newObjectives){
            if((po.Current_Stablecoin_Liquidity__c != null ||  po.Current_MEWs__c != null || po.Current_Stablecoin_Volume__c != null ||  po.Projected_Stablecoin_on_Platform_Growth__c != null
                ||  po.Projected_MeWs_Growth__c != null || po.Projected_Total_Stablecoin_Volume__c != null || po.Custom_Metric__c != null || po.Starting_Mews__c != null 
                || po.Starting_stablecoin_Liquidity__C != null || po.Starting_Stablecoin_Volume__c != null) && po.Type__c == 'Partner Metrics Tracking'){
                partnershipMetricsNeedRollUp.add(po);
            }
        }
        if(partnershipMetricsNeedRollUp.size()>0){
            rollUpPOMetrics(partnershipMetricsNeedRollUp);
        }
    }

    public static void rollUpPOMetrics(Set<Partnership_Objective__c> objectives){
        List<String> currencyFormatting = new String[]{'0','number','⌗⌗⌗,⌗⌗⌗,⌗⌗⌗,⌗⌗⌗'};
        for(Partnership_Objective__c po: objectives){
            String currentMetrics = '';
            String projectedMetrics = '';
            String attainment = '';
            String growthMetrics = '';

            String stablecoin = po.Stablecoin__c;
            if(stablecoin == null || stablecoin == ''){
                stablecoin = 'USDC';
            }
        
            currentMetrics += po.Current_MEWs__c != null ? 'MEWs: ' +String.format(po.Current_MEWs__c.format(), currencyFormatting) +'<br/>': ''; 
            currentMetrics += po.Current_Stablecoin_Liquidity__c != null ? stablecoin+ ' On Platform: $' +String.format(po.Current_Stablecoin_Liquidity__c.format(), currencyFormatting) +'<br/>': '';
            currentMetrics += po.Current_Stablecoin_Volume__c != null ? 'Transaction Volume: $' +String.format(po.Current_Stablecoin_Volume__c.format(), currencyFormatting) +'<br/>': '';  
            
            projectedMetrics += po.Projected_MeWs_Growth__c != null ? 'MEWs: ' +String.format(po.Projected_MeWs_Growth__c.format(), currencyFormatting) +'<br/>': '';
            projectedMetrics += po.Projected_Stablecoin_on_Platform_Growth__c != null ? ''+stablecoin+ ' On Platform: $' +String.format(po.Projected_Stablecoin_on_Platform_Growth__c.format(), currencyFormatting) +'<br/>': '';                
            projectedMetrics += po.Projected_Total_Stablecoin_Volume__c != null ? 'Transaction Volume: $' +String.format(po.Projected_Total_Stablecoin_Volume__c.format(), currencyFormatting) +'<br/>': '';
            
            growthMetrics += po.Starting_Mews__c != null && po.Current_MEWs__c != null ?'MeWs: '+ String.format((po.Current_MEWs__c-po.Starting_Mews__c).format(), currencyFormatting) + '<br/>' : '';
            growthMetrics += po.Starting_stablecoin_liquidity__C != null && po.Current_Stablecoin_Liquidity__c != null ?'Stablecoin On Platform: $'+ String.format((po.Current_Stablecoin_Liquidity__c-po.Starting_stablecoin_liquidity__C).format(), currencyFormatting) + '<br/>' : '';
            growthMetrics += po.Starting_Stablecoin_Volume__c != null && po.Current_Stablecoin_Volume__c != null ? 'Transaction Volume: $'+String.format((po.Current_Stablecoin_Volume__c-po.Starting_Stablecoin_Volume__c).format(), currencyFormatting) + '<br/>' : '';


            if(po.Projected_MeWs_Growth__c != null && po.Projected_MeWs_Growth__c != 0 && po.MeWs_Growth__c != null){
                Decimal projectedMewAttainment = po.MeWs_Growth__c / po.Projected_MeWs_Growth__c;
                attainment += 'MEWs: '+(projectedMewAttainment*100.0).setScale(0)+'%<br/>';
            }
            if(po.Projected_Stablecoin_on_Platform_Growth__c != null &&po.Projected_Stablecoin_on_Platform_Growth__c != 0  && po.Stablecoin_On_Platform_Growth__c != null){
                Decimal stableCoinOnPlatformAttainment = po.Stablecoin_On_Platform_Growth__c / po.Projected_Stablecoin_on_Platform_Growth__c;
                attainment += stablecoin+' On Platform: '+(stableCoinOnPlatformAttainment*100.0).setScale(0)+'%<br/>';
            }
            if(po.Projected_Total_Stablecoin_Volume__c != null && po.Projected_Total_Stablecoin_Volume__c != 0 &&  po.Stablecoin_Volume_Growth__c !=null){
                Decimal projectedtransactionAttainment = po.Stablecoin_Volume_Growth__c / po.Projected_Total_Stablecoin_Volume__c;
                attainment += 'Transaction Volume: '+(projectedtransactionAttainment*100.0).setScale(0)+'%<br/>';
            }
            if(po.Success_Metrics__c != null && po.Success_Metrics__c =='Other'){
                projectedMetrics = 'Click into Partnership Objective for Detail';
                currentMetrics = 'Click into Partnership Objective for Detail'; 
                attainment = 'Click into Partnership Objective for Detail';
            }
            
            po.Current_Metrics__c = currentMetrics.removeEnd('<br/>');
            po.Projected_Metrics__c = projectedMetrics.removeEnd('<br/>');
            po.Attainment__c = attainment.removeEnd('<br/>');
            po.Growth__c = growthMetrics.removeEnd('<br/>');
        }
    }

    public static void setMostRecentNoteHistory(Map<Id, Partnership_Objective__c> newObjectives, Map<Id, Partnership_Objective__c> oldObjectives){
        for(Id id : newObjectives.keyset()){
            if(newObjectives.get(id).Most_recent_Note__c != oldObjectives.get(id).Most_recent_Note__c && newObjectives.get(id).Most_recent_Note__c != null){
                if(newObjectives.get(id).Most_recent_Note_History__c != null){
                    newObjectives.get(id).Most_recent_Note_History__c = '('+String.valueOf(Date.today()) +') : '+newObjectives.get(id).Most_recent_Note__c+ '<br/><br/>' +newObjectives.get(id).Most_recent_Note_History__c;
                }
                else{
                    newObjectives.get(id).Most_recent_Note_History__c = '('+String.valueOf(Date.today()) +') : '+newObjectives.get(id).Most_recent_Note__c;
                }
                newObjectives.get(id).Most_Recent_Note_Date__c = Date.today();
            }
        }
    }
}