force-app/main/default/objects/Support_Category__mdt/Support_Category__mdt.object-meta.xml
<CustomObject>
    <label>Support Category</label>
    <pluralLabel>Support Categories</pluralLabel>
</CustomObject>

force-app/main/default/objects/Support_Category__mdt/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <description>The Data Category API Name.</description>
    <label>API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Support_Category__mdt/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <description>The Category Icon (deprecated)</description>
    <label>Icon</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Support_Category__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>The Category Order.</description>
    <label>Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CategoryMenuController.cls
public without sharing class CategoryMenuController {

    public static Boolean testError = false;

    @AuraEnabled(cacheable=true)
    public static List<CategoryWrapper> getSupportCategories(Boolean checkingSuggestedArticles) {

        List<CategoryWrapper> wrappers = new List<CategoryWrapper>();

        try {
            // Get the Support Categories from the MetaData.
            for(Support_Category__mdt supportCategory : DataCategoryHelper.getSupportCategories(SiteUtils.isGated(), checkingSuggestedArticles)) {

                CategoryWrapper cWrapper = new CategoryWrapper();
                cWrapper.name = supportCategory.API_Name__c;
                cWrapper.label = supportCategory.Label;
                cWrapper.order = Integer.valueOf(supportCategory.Order__c);
                cWrapper.icon = supportCategory.Icon__c;

                wrappers.add(cWrapper);
            }

            if(testError) {
                throw new AuraHandledException('Test error');
            }
        }
        catch(Exception e) {

            System.debug(e.getMessage());
            System.debug(e.getStackTraceString());

            AuraHandledException exc = new AuraHandledException(e.getMessage());
            exc.setMessage(e.getMessage());
            throw exc;
        }

        return wrappers;
    }
}