force-app/main/default/objects/Account/fields/Accounts_API__c.field-meta.xml
<CustomField>
    <fullName>Accounts_API__c</fullName>
    <label>Accounts API</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Accounts_API</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Core_API_Number__c.field-meta.xml
<CustomField>
    <fullName>Core_API_Number__c</fullName>
    <label>Core API Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cybavo__c.field-meta.xml
<CustomField>
    <fullName>Cybavo__c</fullName>
    <description>Used to identify the type of Cybavo product the customer has.</description>
    <inlineHelpText>Select which Cybavo product the customer has purchased.</inlineHelpText>
    <label>Cybavo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cybavo VAULT</fullName>
            </value>
            <value>
                <fullName>Cybavo Cashflow Manager</fullName>
            </value>
            <value>
                <fullName>Cybavo Wallet SDK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Payments_API__c.field-meta.xml
<CustomField>
    <fullName>Payments_API__c</fullName>
    <label>Payments API</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payments_API</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Payouts_API__c.field-meta.xml
<CustomField>
    <fullName>Payouts_API__c</fullName>
    <label>Payouts API</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payouts_API</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Read_Only_API_Number__c.field-meta.xml
<CustomField>
    <fullName>Read_Only_API_Number__c</fullName>
    <label>Read Only API Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region field to be populated by HQ Country Field on Account Object.</description>
    <inlineHelpText>Populated by HQ Country.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
                <label>North America</label>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>Middle East and Africa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SEN_Number__c.field-meta.xml
<CustomField>
    <fullName>SEN_Number__c</fullName>
    <label>SEN Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Signet_Number__c.field-meta.xml
<CustomField>
    <fullName>Signet_Number__c</fullName>
    <label>Signet Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/USDC_Express_Number__c.field-meta.xml
<CustomField>
    <fullName>USDC_Express_Number__c</fullName>
    <label>USDC Express Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/Circle_Account__c.object-meta.xml
<CustomObject>
    <label>Circle Mint</label>
    <nameField>
        <label>Circle Mint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Circle Mints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Circle_Account__c/fields/Account_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Account_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Lookup</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Circle_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Accounts_API__c.field-meta.xml
<CustomField>
    <fullName>Accounts_API__c</fullName>
    <label>Accounts API</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First-Party (internal use)</fullName>
            </value>
            <value>
                <fullName>Third-Party</fullName>
            </value>
            <value>
                <fullName>BTC/ETH Beta</fullName>
            </value>
            <value>
                <fullName>Exchange Beta</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Core_API_Number__c.field-meta.xml
<CustomField>
    <fullName>Core_API_Number__c</fullName>
    <formula>IF( Core_API__c = TRUE,1,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Core API Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Country_of_Incorporation__c.field-meta.xml
<CustomField>
    <fullName>Country_of_Incorporation__c</fullName>
    <description>Location of incorporation (Country)</description>
    <label>Country of Incorporation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_of_Incorporation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Cybavo__c.field-meta.xml
<CustomField>
    <fullName>Cybavo__c</fullName>
    <description>Used to identify the type of Cybavo product the customer has.</description>
    <inlineHelpText>Select which Cybavo product the customer has purchased.</inlineHelpText>
    <label>Cybavo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cybavo VAULT</fullName>
            </value>
            <value>
                <fullName>Cybavo Cashflow Manager</fullName>
            </value>
            <value>
                <fullName>Cybavo Wallet SDK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Circle_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Payments_API__c.field-meta.xml
<CustomField>
    <fullName>Payments_API__c</fullName>
    <label>Payments API</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cards</fullName>
            </value>
            <value>
                <fullName>Wires</fullName>
            </value>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>SEPA</fullName>
            </value>
            <value>
                <fullName>USDC</fullName>
            </value>
            <value>
                <fullName>Crypto Payments</fullName>
            </value>
            <value>
                <fullName>Apple Pay</fullName>
            </value>
            <value>
                <fullName>Google Pay</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Payouts_API__c.field-meta.xml
<CustomField>
    <fullName>Payouts_API__c</fullName>
    <label>Payouts API</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>SEPA</fullName>
            </value>
            <value>
                <fullName>USDC</fullName>
            </value>
            <value>
                <fullName>Wires</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Read_Only_API_Number__c.field-meta.xml
<CustomField>
    <fullName>Read_Only_API_Number__c</fullName>
    <formula>IF( Read_Only_API__c  = TRUE,1,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Read Only API Number</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>Middle East and Africa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/SEN_Number__c.field-meta.xml
<CustomField>
    <fullName>SEN_Number__c</fullName>
    <formula>IF( SEN__c =TRUE,1,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SEN Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Signet_Number__c.field-meta.xml
<CustomField>
    <fullName>Signet_Number__c</fullName>
    <formula>IF( Signet__c =TRUE,1,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Signet Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/USDC_Express_Number__c.field-meta.xml
<CustomField>
    <fullName>USDC_Express_Number__c</fullName>
    <formula>IF( USDC_Express__c =TRUE,1,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>USDC Express Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Number_of_Circle_Accounts__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Circle_Accounts__c</fullName>
    <label>Number of Circle Accounts</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Region field to be populated by Country Field on Account Object.</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>Middle East and Africa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CircleAccountsTest.cls
@isTest
public class CircleAccountsTest {

    @TestSetup
    static void setup(){
        CircleTestDataFactory.insertCustomSettings();
    }

    @isTest static void testAccountRollupInsert(){
        Account act = CircleTestDataFactory.insertAccount();
        Test.startTest();
            Circle_Account__c ca = CircleTestDataFactory.insertCircleAccount(act.id, null, 'Third-Party',true,true,true,false,true,'Cybavo Cashflow Manager', 'Cards;Wires', 'USDC;Wires',100,200);   
        Test.stopTest();

        act = [SELECT ID, Accounts_API__c, Core_API_Number__C,Read_Only_API_Number__c,Sen_Number__c, Signet_Number__c,USDC_Express_Number__c, Cybavo__c, Payments_Api__c, Payouts_Api__c FROM Account WHERE ID = :act.id];
        System.assertEquals('Third-Party', act.Accounts_API__c);
        System.assertEquals(1, act.Core_API_Number__C);
        System.assertEquals(1, act.Read_Only_API_Number__c);
        System.assertEquals(1, act.Sen_Number__c);
        System.assertEquals(0, act.Signet_Number__c);
        System.assertEquals(1, act.USDC_Express_Number__c);
        System.assertEquals('Cybavo Cashflow Manager', act.Cybavo__c);
        System.assertEquals('Cards;Wires', act.Payments_Api__c);
        System.assertEquals('Wires;USDC', act.Payouts_Api__c);
    }

    @isTest static void testAccountRollupMultipleCA(){
        Account act = CircleTestDataFactory.insertAccount();
        Test.startTest();
            Circle_Account__c ca = CircleTestDataFactory.makeCircleAccount(act.id, null,'Third-Party',true,true,true,true,true,'Cybavo Wallet SDK', 'Cards;Wires', 'Wires;USDC',100,200);
            Circle_Account__c ca2 = CircleTestDataFactory.makeCircleAccount(act.id, null, 'None',true,true,true,false,true,'Cybavo Cashflow Manager', 'USDC;ACH','ACH',300,400);
            insert new List<Circle_Account__c>{ca,ca2}; 
        Test.stopTest();

        act = [SELECT ID, Accounts_API__c,Core_API_Number__C,Read_Only_API_Number__c,Sen_Number__c, Signet_Number__c,USDC_Express_Number__c,Cybavo__c,Payments_Api__c, Payouts_Api__c FROM Account WHERE ID = :act.id];
        System.assertEquals('None;Third-Party', act.Accounts_API__c);
        System.assertEquals(2, act.Core_API_Number__C);
        System.assertEquals(2, act.Read_Only_API_Number__c);
        System.assertEquals(2, act.Sen_Number__c);
        System.assertEquals(1, act.Signet_Number__c);
        System.assertEquals(2, act.USDC_Express_Number__c);
        System.assertEquals('Cybavo Cashflow Manager;Cybavo Wallet SDK', act.Cybavo__c);
        System.assertEquals('Cards;Wires;ACH;USDC', act.Payments_Api__c);
        System.assertEquals('Wires;ACH;USDC', act.Payouts_Api__c);
    }

    @isTest static void testAccountRollupUpdate(){
        Account act = CircleTestDataFactory.insertAccount();
        Circle_Account__c ca = CircleTestDataFactory.insertCircleAccount(act.id, null, 'Third-Party',true,true,true,true,true, 'Cybavo Cashflow Manager','USDC;ACH','USDC',100,200);
        Test.startTest();
            ca.Accounts_API__c = 'None';
            update ca;
            act = [SELECT ID, Accounts_API__c FROM Account WHERE ID = :act.id];
            System.assertEquals('None', act.Accounts_API__c);
            ca.Account_lookup__C = null;
            update ca;
            act = [SELECT ID, Accounts_API__c,Core_API_Number__C,Read_Only_API_Number__c,Sen_Number__c, Signet_Number__c, USDC_Express_Number__c,Cybavo__c,Payments_Api__c, Payouts_Api__c FROM Account WHERE ID = :act.id];
            System.assertEquals(null, act.Accounts_API__c);
            System.assertEquals(0, act.Core_API_Number__C);
            System.assertEquals(0, act.Read_Only_API_Number__c);
            System.assertEquals(0, act.Sen_Number__c);
            System.assertEquals(0, act.Signet_Number__c);
            System.assertEquals(0, act.USDC_Express_Number__c);
            System.assertEquals(null, act.Cybavo__c);
            System.assertEquals(null, act.Payments_Api__c);
            System.assertEquals(null, act.Payouts_Api__c);
            ca.Account_lookup__C = act.id;
            update ca;
        Test.stopTest();
    }
    

    @isTest static void testLeadCircleAccountRollupInsert(){
        Lead testLead = CircleTestDataFactory.insertLead();
        Test.startTest();
            Circle_Account__c ca = CircleTestDataFactory.makeCircleAccount(null, testLead.id, null,true,true,true,true,true,null,null,null,null,null);
            Circle_Account__c ca2 = CircleTestDataFactory.makeCircleAccount(null, testLead.id, null,true,true,true,true,true,null,null,null,null,null);
            insert new List<Circle_Account__c>{ca,ca2};
        Test.stopTest();

        testLead = [SELECT ID, Number_of_Circle_Accounts__c FROM Lead WHERE ID = :testLead.id];
        System.assertEquals(2, testLead.Number_of_Circle_Accounts__c);
    }

    @isTest static void testLeadCircleAccountRollupUpdate(){
        Lead testLead = CircleTestDataFactory.insertLead();
        Test.startTest();
            Circle_Account__c ca = CircleTestDataFactory.makeCircleAccount(null, testLead.id, null,true,true,true,true,true,null,null,null,null,null);
            Circle_Account__c ca2 = CircleTestDataFactory.makeCircleAccount(null, testLead.id, null,true,true,true,true,true,null,null,null,null,null);
            insert new List<Circle_Account__c>{ca,ca2};
            ca2.Lead__c = null;
            update ca2;
            testLead = [SELECT ID, Number_of_Circle_Accounts__c FROM Lead WHERE ID = :testLead.id];
            System.assertEquals(1, testLead.Number_of_Circle_Accounts__c);
        Test.stopTest();

        ca2.Lead__c = testLead.id;
        update ca2;
        testLead = [SELECT ID, Number_of_Circle_Accounts__c FROM Lead WHERE ID = :testLead.id];
        System.assertEquals(2, testLead.Number_of_Circle_Accounts__c);
    }    

    @isTest static void testCountryMapping(){
        Account act = CircleTestDataFactory.insertAccount();
        Test.startTest();
            Circle_Account__c ca = CircleTestDataFactory.insertCircleAccount(act.id, null, 'Third-Party',true,true,true,false,true,'Cybavo Cashflow Manager', 'Cards;Wires', 'USDC;Wires',100,200);
            ca = [SELECT ID, Region__c FROM Circle_Account__c WHERE ID = :ca.id];
            System.assertEquals('Americas', ca.Region__c);
            ca.Country_Of_Incorporation__c = 'BR';
            update ca;
        Test.stopTest();
        ca = [SELECT ID, Region__c FROM Circle_Account__c WHERE ID = :ca.id];
        System.assertEquals('LATAM', ca.Region__c);
    }
}