force-app/main/default/objects/Account/fields/Business_Development_Owner__c.field-meta.xml
<CustomField>
    <fullName>Business_Development_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Development Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Circle_Ventures_Owner__c.field-meta.xml
<CustomField>
    <fullName>Circle_Ventures_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Circle Ventures Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountsGltS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Onboarding_Specialist__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Specialist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A representative from the Onboarding Concierge team</description>
    <label>Onboarding Specialist</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Platform_Owner__c.field-meta.xml
<CustomField>
    <fullName>Platform_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Platform Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Post_Sales_Solution_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Post_Sales_Solution_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Post-Sales Solution Engineer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountsGrmS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pre_Sales_Solution_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Pre_Sales_Solution_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pre-Sales Solution Engineer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts10</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Treasury_Owner__c.field-meta.xml
<CustomField>
    <fullName>Treasury_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treasury Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <businessProcess>Renewal</businessProcess>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Treasury.recordType-meta.xml
<RecordType>
    <fullName>Treasury</fullName>
    <active>true</active>
    <businessProcess>Treasury %28Yield%29</businessProcess>
    <label>Treasury</label>
</RecordType>

force-app/main/default/classes/OppTeamMemberCreation.cls
public class OppTeamMemberCreation {
	@InvocableMethod
    public static void createOppTeamMembers(List<Account> a_accountList){
        //Account acc = a_accountList[0];
        Map<Id, Account> accMap = new Map<Id, Account>(a_accountList);
        List<Opportunity> oppList = new List<Opportunity>();
        List<Opportunity> oppsToUpdateList = new List<Opportunity>();
        List<OpportunityTeamMember> otmList = new List<OpportunityTeamMember>();
        oppList = [select id, AccountId, OwnerId, RecordTypeId, RecordType.Name from Opportunity where AccountId in :accMap.keySet() and IsClosed = false];
        //Map<Id, RecordType> oppRecordTypeMap = new Map<Id, RecordType>([select Id,Name from RecordType where sObjectType='Opportunity']);
        
        for(Opportunity opp : oppList){
            Account ac = new Account();
            ac = accMap.get(opp.AccountId);
            
            String currentOwnerId = ac.Platform_Owner__c;
            if(String.isNotBlank(currentOwnerId)){
                if(opp.RecordType.Name == 'Platform'){
                    Opportunity oppToUpdate = new Opportunity(Id = opp.Id, OwnerId = currentOwnerId);
                    oppsToUpdateList.add(oppToUpdate);
                }
                else{
                    otmList.add(returnTeamMember(currentOwnerId, opp.Id, 'Platform Rep'));
                }
            }
            
            currentOwnerId = ac.Treasury_Owner__c;
            if(String.isNotBlank(currentOwnerId)){
                if(opp.RecordType.Name == 'Treasury'){
                    Opportunity oppToUpdate = new Opportunity(Id = opp.Id, OwnerId = currentOwnerId);
                    oppsToUpdateList.add(oppToUpdate);
                }
                else{
                	otmList.add(returnTeamMember(currentOwnerId, opp.Id, 'Treasury Services Rep'));
                }
            }
            
            currentOwnerId = ac.Business_Development_Owner__c;
            if(String.isNotBlank(currentOwnerId)){
                if(opp.RecordType.Name == 'Business Development'){
                    Opportunity oppToUpdate = new Opportunity(Id = opp.Id, OwnerId = currentOwnerId);
                    oppsToUpdateList.add(oppToUpdate);
                }
                else{
                	otmList.add(returnTeamMember(currentOwnerId, opp.Id, 'Business Development Rep'));
                }
            }
            
            currentOwnerId = ac.Pre_Sales_Solution_Engineer__c;
            if(String.isNotBlank(currentOwnerId)){
                otmList.add(returnTeamMember(currentOwnerId, opp.Id, 'Pre-Sales Solution Engineer'));
            }
            currentOwnerId = ac.Post_Sales_Solution_Engineer__c;
            if(String.isNotBlank(currentOwnerId)){
                otmList.add(returnTeamMember(currentOwnerId, opp.Id, 'Post-Sales Solution Engineer'));
            }
            
            currentOwnerId = ac.Customer_Success_Manager__c;
            if(String.isNotBlank(currentOwnerId)){
                if(opp.RecordType.Name == 'Renewal'){
                    Opportunity oppToUpdate = new Opportunity(Id = opp.Id, OwnerId = currentOwnerId);
                    oppsToUpdateList.add(oppToUpdate);
                }
                else{
                	otmList.add(returnTeamMember(currentOwnerId, opp.Id, 'Customer Success Manager'));
                }
            }
            currentOwnerId = ac.Onboarding_Specialist__c;
            if(String.isNotBlank(currentOwnerId)){
                otmList.add(returnTeamMember(currentOwnerId, opp.Id, 'Onboarding Specialist'));
            }
            
            currentOwnerId = ac.Circle_Ventures_Owner__c;
            if(String.isNotBlank(currentOwnerId)){
                if(opp.RecordType.Name == 'Circle Ventures'){
                    Opportunity oppToUpdate = new Opportunity(Id = opp.Id, OwnerId = currentOwnerId);
                    oppsToUpdateList.add(oppToUpdate);
                }
                else{
                	otmList.add(returnTeamMember(currentOwnerId, opp.Id, 'Circle Ventures Rep'));
                }
            }
        }
        
        if(otmList.size() > 0){
            insert otmList;
        }
        if(oppsToUpdateList.size() > 0){
            update oppsToUpdateList;
        }
    }
    
    public static OpportunityTeamMember returnTeamMember(String a_userId, String a_opportunityId, String a_roleName){
        OpportunityTeamMember otm = new OpportunityTeamMember();
        otm.UserId = a_userId;
        otm.TeamMemberRole = a_roleName;
        otm.OpportunityId = a_opportunityId;
        otm.OpportunityAccessLevel = 'Edit';
        return otm;
    }
}