force-app/main/default/objects/Account/fields/Current_Metrics__c.field-meta.xml
<CustomField>
    <fullName>Current_Metrics__c</fullName>
    <label>Current Metrics</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_30_Day_Metrics__c.field-meta.xml
<CustomField>
    <fullName>Last_30_Day_Metrics__c</fullName>
    <label>Last 30 Day Metrics</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_30_Day_Metrics_Trend__c.field-meta.xml
<CustomField>
    <fullName>Last_30_Day_Metrics_Trend__c</fullName>
    <label>Last 30 Day Metrics Trend</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/Monthly_Avg_Metrics__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Avg_Metrics__c</fullName>
    <label>Monthly Avg Metrics</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/Starting_Metrics__c.field-meta.xml
<CustomField>
    <fullName>Starting_Metrics__c</fullName>
    <label>Starting Metrics</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Burn_Volume_Last_30_Days__c.field-meta.xml
<CustomField>
    <fullName>Total_Burn_Volume_Last_30_Days__c</fullName>
    <label>Total Burn Volume Last 30 Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Current_Gross_Burn__c.field-meta.xml
<CustomField>
    <fullName>Total_Current_Gross_Burn__c</fullName>
    <label>Total Current Gross Burn</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Current_Gross_Mint__c.field-meta.xml
<CustomField>
    <fullName>Total_Current_Gross_Mint__c</fullName>
    <label>Total Current Gross Mint</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Mint_Volume_Last_30_Days__c.field-meta.xml
<CustomField>
    <fullName>Total_Mint_Volume_Last_30_Days__c</fullName>
    <label>Total Mint Volume Last 30 Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Monthly_Avg_Gross_Burn__c.field-meta.xml
<CustomField>
    <fullName>Total_Monthly_Avg_Gross_Burn__c</fullName>
    <label>Total Monthly Avg Gross Burn</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Monthly_Avg_Gross_Mint__c.field-meta.xml
<CustomField>
    <fullName>Total_Monthly_Avg_Gross_Mint__c</fullName>
    <label>Total Monthly Avg Gross Mint</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/Circle_Account__c.object-meta.xml
<CustomObject>
    <label>Circle Mint</label>
    <nameField>
        <label>Circle Mint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Circle Mints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Circle_Account__c/fields/Monthly_Avg_Gross_Burn__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Avg_Gross_Burn__c</fullName>
    <label>Monthly Avg Gross Burn</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Monthly_Avg_Gross_Mint__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Avg_Gross_Mint__c</fullName>
    <label>Monthly Avg Gross Mint</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/recordTypes/Circle.recordType-meta.xml
<RecordType>
    <fullName>Circle</fullName>
    <active>true</active>
    <label>Circle</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Circle_Account__c.field-meta.xml
<CustomField>
    <fullName>Circle_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Circle Mint</label>
    <referenceTo>Circle_Account__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RollUpCircleAccountMetricsBatchTest.cls
@isTest 
public with sharing class RollUpCircleAccountMetricsBatchTest {

    @TestSetup
    static void setup(){
        CircleTestDataFactory.insertCustomSettings();
    }

    @isTest static void testBatchJob(){
        Account act = CircleTestDataFactory.insertAccount();
        Account act2 = act.clone(false,true);
        insert act2;
        Opportunity opp = CircleTestDataFactory.insertOpportunity(act.Id, 'Test', Date.today(), 'Circle Mint');
        
        Test.startTest();
            Circle_Account__c ca = CircleTestDataFactory.makeCircleAccount(act.id, null,'Third-Party',true,true,true,true,true,'Cybavo Wallet SDK', 'Cards;Wires', 'Wires;USDC',200,100);
            insert ca;
            act = [SELECT ID, Starting_Metrics__c,Current_Metrics__c,Monthly_Avg_Metrics__c,Last_30_Day_Metrics__c,Last_30_Day_Metrics_Trend__c,Total_Burn_Volume_Last_30_Days__c,Total_Mint_Volume_Last_30_Days__c,Total_Current_Gross_Burn__c,Total_Current_Gross_Mint__c,Total_Monthly_Avg_Gross_Burn__c,Total_Monthly_Avg_Gross_Mint__c FROM Account WHERE ID = :act.id];        
            System.assertEquals(200,act.Total_Current_Gross_Mint__c);
            System.assertEquals(100,act.Total_Current_Gross_Burn__c);
            System.assertEquals(200,act.Total_Mint_Volume_Last_30_Days__c);
            System.assertEquals(100,act.Total_Burn_Volume_Last_30_Days__c);
            Circle_Account__c ca2 = CircleTestDataFactory.makeCircleAccount(act.id, null, 'None',true,true,true,false,true,'Cybavo Cashflow Manager', 'USDC;ACH','ACH',300,400);
            ca2.Monthly_Avg_Gross_Mint__c = 150;
            ca2.Monthly_Avg_Gross_Burn__c = 200;
            insert ca2;
            act = [SELECT ID, Starting_Metrics__c,Current_Metrics__c,Monthly_Avg_Metrics__c,Last_30_Day_Metrics__c,Last_30_Day_Metrics_Trend__c,Total_Burn_Volume_Last_30_Days__c,Total_Mint_Volume_Last_30_Days__c,Total_Current_Gross_Burn__c,Total_Current_Gross_Mint__c,Total_Monthly_Avg_Gross_Burn__c,Total_Monthly_Avg_Gross_Mint__c FROM Account WHERE ID = :act.id];
            System.assertEquals(500,act.Total_Current_Gross_Mint__c);
            System.assertEquals(500,act.Total_Current_Gross_Burn__c);
            System.assertEquals(350,act.Total_Monthly_Avg_Gross_Mint__c);
            System.assertEquals(300,act.Total_Monthly_Avg_Gross_Burn__c);
            System.assertEquals(500,act.Total_Mint_Volume_Last_30_Days__c);
            System.assertEquals(500,act.Total_Burn_Volume_Last_30_Days__c);
            ca2.Monthly_Avg_Gross_Mint__c = 450;
            ca2.Monthly_Avg_Gross_Burn__c = 500;
            update ca2;
            act = [SELECT ID, Starting_Metrics__c,Current_Metrics__c,Monthly_Avg_Metrics__c,Last_30_Day_Metrics__c,Last_30_Day_Metrics_Trend__c,Total_Burn_Volume_Last_30_Days__c,Total_Mint_Volume_Last_30_Days__c,Total_Current_Gross_Burn__c,Total_Current_Gross_Mint__c,Total_Monthly_Avg_Gross_Burn__c,Total_Monthly_Avg_Gross_Mint__c FROM Account WHERE ID = :act.id];
            System.assertEquals(650,act.Total_Monthly_Avg_Gross_Mint__c);
            System.assertEquals(600,act.Total_Monthly_Avg_Gross_Burn__c);
            System.assertEquals(500,act.Total_Mint_Volume_Last_30_Days__c);
            System.assertEquals(500,act.Total_Burn_Volume_Last_30_Days__c);
        Test.stopTest();
    }
}