force-app/main/default/objects/Account/fields/Lifecycle_Stage__c.field-meta.xml
<CustomField>
    <fullName>Lifecycle_Stage__c</fullName>
    <label>Account Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cold</fullName>
            </value>
            <value>
                <fullName>Subscriber</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>MQL</fullName>
            </value>
            <value>
                <fullName>SAL</fullName>
            </value>
            <value>
                <fullName>SQL</fullName>
            </value>
            <value>
                <fullName>OTY</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Former Customer</fullName>
            </value>
            <value>
                <fullName>Terminated Customer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Needs_Lifecycle_Recalculation__c.field-meta.xml
<CustomField>
    <fullName>Needs_Lifecycle_Recalculation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Needs Lifecycle Recalculation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <inlineHelpText>Refers to what stage the lead or contact is at in our pre-sales process.</inlineHelpText>
    <label>Contact Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cold</fullName>
            </value>
            <value>
                <fullName>Subscriber</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Researching</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Marketing Qualified</fullName>
            </value>
            <value>
                <fullName>Engaged</fullName>
            </value>
            <value>
                <fullName>Advanced</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Recycled - Not Ready</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Former Customer</fullName>
            </value>
            <value>
                <fullName>Terminated Customer</fullName>
            </value>
            <value>
                <fullName>Disqualified - Bad Fit</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
                <isActive>false</isActive>
                <label>Assigned</label>
            </value>
            <value>
                <fullName>Meeting scheduled</fullName>
                <isActive>false</isActive>
                <label>Meeting scheduled</label>
            </value>
            <value>
                <fullName>Nurture</fullName>
                <isActive>false</isActive>
                <label>Nurture</label>
            </value>
            <value>
                <fullName>Released</fullName>
                <isActive>false</isActive>
                <label>Released</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountLifecycleStageBatchTest.cls
@isTest 
public class AccountLifecycleStageBatchTest {

    @TestSetup
    static void setup(){
        CircleTestDataFactory.insertCustomSettings();
    }

    @isTest static void testLifecycleStages(){
        Account act = CircleTestDataFactory.insertAccount();
        Contact cont0 = CircleTestDataFactory.insertContactWithStage(act.Id, 'First', 'Last0', 'first.last0@circle.com',null);
        act = [SELECT LifeCycle_Stage__C FROM Account WHERE ID = :act.id];
        System.assertEquals(null,act.LifeCycle_Stage__C);
        Contact cont = CircleTestDataFactory.insertContactWithStage(act.Id, 'First', 'Last1', 'first.last@circle.com1','Cold');
        act = [SELECT LifeCycle_Stage__C FROM Account WHERE ID = :act.id];
        System.assertEquals('Cold',act.LifeCycle_Stage__C);
        cont.Stage__C = 'Customer';
        update cont;
        act = [SELECT LifeCycle_Stage__C FROM Account WHERE ID = :act.id];
        System.assertEquals('Customer',act.LifeCycle_Stage__C);
        act.Lifecycle_Stage__c = null;
        act.Needs_Lifecycle_Recalculation__c = true;
        update act;
        act = [SELECT LifeCycle_Stage__C FROM Account WHERE ID = :act.id];
        System.assertEquals(null,act.LifeCycle_Stage__C);

        Test.startTest();
            AccountLifecycleStageBatch b = new AccountLifecycleStageBatch();
            database.executeBatch(b);
        Test.stopTest();

        act = [SELECT LifeCycle_Stage__C ,Needs_Lifecycle_Recalculation__c FROM Account WHERE ID = :act.id];
        System.assertEquals('Customer',act.LifeCycle_Stage__C);
        System.assertEquals(false,act.Needs_Lifecycle_Recalculation__c);
    }
}