force-app/main/default/objects/Account/fields/Lifecycle_Stage__c.field-meta.xml
<CustomField>
    <fullName>Lifecycle_Stage__c</fullName>
    <label>Account Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cold</fullName>
            </value>
            <value>
                <fullName>Subscriber</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>MQL</fullName>
            </value>
            <value>
                <fullName>SAL</fullName>
            </value>
            <value>
                <fullName>SQL</fullName>
            </value>
            <value>
                <fullName>OTY</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Former Customer</fullName>
            </value>
            <value>
                <fullName>Terminated Customer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Needs_Lifecycle_Recalculation__c.field-meta.xml
<CustomField>
    <fullName>Needs_Lifecycle_Recalculation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Needs Lifecycle Recalculation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccountLifecycleStageBatch.cls
public class AccountLifecycleStageBatch implements Database.Batchable<sObject> {
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT ID, Lifecycle_Stage__c, (SELECT ID, Stage__c FROM Contacts) FROM Account WHERE Needs_Lifecycle_Recalculation__c = TRUE AND Lifecycle_Stage__C != 'Terminated Customer' AND LifeCycle_Stage__C != 'Former Customer']);
    }
    
    public void execute(Database.BatchableContext bc, List<Account> theAccounts) {
        for(Account act : theAccounts){
            act.Needs_Lifecycle_Recalculation__c = false;
        }
        Accounts.recalculateAccountLifeCycleStages(theAccounts);
    }
     
    public void finish(Database.BatchableContext bc) {
        
    }
}