force-app/main/default/objects/Account/fields/Nature_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Nature_of_Business__c</fullName>
    <label>Nature of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>accommodation</fullName>
                <label>Accommodation and Food Services (excluding Casinos)</label>
            </value>
            <value>
                <fullName>accounting</fullName>
                <label>Accounting and Legal Firms</label>
            </value>
            <value>
                <fullName>agriculture</fullName>
                <label>Agriculture, Forestry, Fishing and Hunting</label>
            </value>
            <value>
                <fullName>art</fullName>
                <label>Art Dealers and Auction Houses</label>
            </value>
            <value>
                <fullName>casino</fullName>
                <label>Casinos and Gambling</label>
            </value>
            <value>
                <fullName>construction</fullName>
                <label>Construction</label>
            </value>
            <value>
                <fullName>cryptoNetwork</fullName>
                <label>Crypto Network</label>
            </value>
            <value>
                <fullName>dapp</fullName>
                <label>DApp Providers and Developers</label>
            </value>
            <value>
                <fullName>preciousMetals</fullName>
                <label>Dealers and Retailers of Physical Precious Metals and/or Precious Stones</label>
            </value>
            <value>
                <fullName>defiExchange</fullName>
                <label>DeFI: Decentralized Exchanges</label>
            </value>
            <value>
                <fullName>defiOther</fullName>
                <label>DeFi: Other</label>
            </value>
            <value>
                <fullName>defiWallet</fullName>
                <label>DeFI: Self-Hosted Wallets</label>
            </value>
            <value>
                <fullName>education</fullName>
                <label>Education</label>
            </value>
            <value>
                <fullName>familyOffices</fullName>
                <label>Family Offices and Personal Investment Companies</label>
            </value>
            <value>
                <fullName>film</fullName>
                <label>Film, Television, Internet, and Print media</label>
            </value>
            <value>
                <fullName>fiAssetMgr</fullName>
                <label>Financial Institutions: Asset Managers, Hedge Funds, and Funds</label>
            </value>
            <value>
                <fullName>fiBank</fullName>
                <label>Financial Institutions: Banks and Credit Unions</label>
            </value>
            <value>
                <fullName>fiBrokerDealer</fullName>
                <label>Financial Institutions: Broker Dealers</label>
            </value>
            <value>
                <fullName>fiCryptoATM</fullName>
                <label>Financial Institutions: Crypto ATM Operator</label>
            </value>
            <value>
                <fullName>fiCryptoExchanges</fullName>
                <label>Financial Institutions: Crypto Exchanges</label>
            </value>
            <value>
                <fullName>fiCryptoInvesting</fullName>
                <label>Financial Institutions: Crypto Investing and Lending</label>
            </value>
            <value>
                <fullName>fiCryptoOnRamp</fullName>
                <label>Financial Institutions: Crypto On-Ramps / Retail OTC Trading</label>
            </value>
            <value>
                <fullName>fiCryptoWallets</fullName>
                <label>Financial Institutions: Crypto Wallets and Custodians</label>
            </value>
            <value>
                <fullName>fiOTC</fullName>
                <label>Financial Institutions: OTC Trading</label>
            </value>
            <value>
                <fullName>fiP2P</fullName>
                <label>Financial Institutions: Peer to Peer Payments / Money Transmitters</label>
            </value>
            <value>
                <fullName>healthCare</fullName>
                <label>Health Care</label>
            </value>
            <value>
                <fullName>manufacturingAutomobiles</fullName>
                <label>Manufacturing, Wholesale and Retail: Automobiles and Other Vehicles</label>
            </value>
            <value>
                <fullName>manufacturingElectronics</fullName>
                <label>Manufacturing, Wholesale and Retail: Electronics (including Computers)</label>
            </value>
            <value>
                <fullName>manufacturingJewelry</fullName>
                <label>Manufacturing, Wholesale and Retail: High Value Goods (Jewelry, Watches, Antiques)</label>
            </value>
            <value>
                <fullName>manufacturingOther</fullName>
                <label>Manufacturing, Wholesale and Retail: Other Goods</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Circle_Account__c/Circle_Account__c.object-meta.xml
<CustomObject>
    <label>Circle Mint</label>
    <nameField>
        <label>Circle Mint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Circle Mints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Circle_Account__c/fields/Account_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Account_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Lookup</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Circle_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Circle_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>Circle_Entity_Id__c</fullName>
    <label>Circle Entity Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Circle_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <label>Legal Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Circle_Account__c/fields/Nature_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Nature_of_Business__c</fullName>
    <label>Nature of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nature_of_Business</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Circle_Entity_ID__c.field-meta.xml
<CustomField>
    <fullName>Circle_Entity_ID__c</fullName>
    <label>Circle Entity ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Nature_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Nature_of_Business__c</fullName>
    <label>Nature of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nature_of_Business</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CircleAccountWebServiceTest.cls
@isTest
public class CircleAccountWebServiceTest {

    @TestSetup
    static void setup(){
       CircleTestDataFactory.insertCustomSettings(); 
    }
    
    @isTest static  void testWebService(){
        Account act = CircleTestDataFactory.insertAccount();
        Contact cont = CircleTestDataFactory.insertContact(act.Id,'first', 'last', null);
        Circle_Account__c ca = new Circle_Account__C(Account_Lookup__c = act.id, Contact__c = cont.id, Legal_entity_Name__C = 'legal', Nature_Of_Business__C = 'fiAssetMgr');
        ca.Name = 'Test CA';
        ca.Circle_Entity_Id__c = '123456z';
        insert ca;

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CircleAccount';
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
    
        CircleAccountWrapper accWrapper = new CircleAccountWrapper();
        accWrapper.natureOfBusiness = ca.Nature_of_Business__c;
        accWrapper.legalEntityName = ca.Legal_Entity_Name__c;
        accWrapper.name = ca.Name;
        accWrapper.withdrawalLimit = 123;
        CircleAccountWebService.upsertCircleAccount(accWrapper);
        List<Circle_Account__C> circleAccounts = [SELECT ID FROM Circle_Account__C WHERE Name = :ca.name];
        System.assertEquals(2, circleAccounts.size());
        accWrapper.circleEntityId = ca.Circle_Entity_Id__c;
        CircleAccountWebService.upsertCircleAccount(accWrapper);
        circleAccounts = [SELECT ID FROM Circle_Account__C WHERE Circle_Entity_Id__c = :ca.Circle_Entity_Id__c];
        System.assertEquals(1, circleAccounts.size());

        RestContext.response = null;
        String error;
        try{
            CircleAccountWebService.upsertCircleAccount(accWrapper);
        }
        catch(Exception e){
            error = e.getMessage();
        }
        System.assertNotEquals(null, error);

    }
}