force-app/main/default/objects/Account/fields/Nature_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Nature_of_Business__c</fullName>
    <label>Nature of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>accommodation</fullName>
                <label>Accommodation and Food Services (excluding Casinos)</label>
            </value>
            <value>
                <fullName>accounting</fullName>
                <label>Accounting and Legal Firms</label>
            </value>
            <value>
                <fullName>agriculture</fullName>
                <label>Agriculture, Forestry, Fishing and Hunting</label>
            </value>
            <value>
                <fullName>art</fullName>
                <label>Art Dealers and Auction Houses</label>
            </value>
            <value>
                <fullName>casino</fullName>
                <label>Casinos and Gambling</label>
            </value>
            <value>
                <fullName>construction</fullName>
                <label>Construction</label>
            </value>
            <value>
                <fullName>cryptoNetwork</fullName>
                <label>Crypto Network</label>
            </value>
            <value>
                <fullName>dapp</fullName>
                <label>DApp Providers and Developers</label>
            </value>
            <value>
                <fullName>preciousMetals</fullName>
                <label>Dealers and Retailers of Physical Precious Metals and/or Precious Stones</label>
            </value>
            <value>
                <fullName>defiExchange</fullName>
                <label>DeFI: Decentralized Exchanges</label>
            </value>
            <value>
                <fullName>defiOther</fullName>
                <label>DeFi: Other</label>
            </value>
            <value>
                <fullName>defiWallet</fullName>
                <label>DeFI: Self-Hosted Wallets</label>
            </value>
            <value>
                <fullName>education</fullName>
                <label>Education</label>
            </value>
            <value>
                <fullName>familyOffices</fullName>
                <label>Family Offices and Personal Investment Companies</label>
            </value>
            <value>
                <fullName>film</fullName>
                <label>Film, Television, Internet, and Print media</label>
            </value>
            <value>
                <fullName>fiAssetMgr</fullName>
                <label>Financial Institutions: Asset Managers, Hedge Funds, and Funds</label>
            </value>
            <value>
                <fullName>fiBank</fullName>
                <label>Financial Institutions: Banks and Credit Unions</label>
            </value>
            <value>
                <fullName>fiBrokerDealer</fullName>
                <label>Financial Institutions: Broker Dealers</label>
            </value>
            <value>
                <fullName>fiCryptoATM</fullName>
                <label>Financial Institutions: Crypto ATM Operator</label>
            </value>
            <value>
                <fullName>fiCryptoExchanges</fullName>
                <label>Financial Institutions: Crypto Exchanges</label>
            </value>
            <value>
                <fullName>fiCryptoInvesting</fullName>
                <label>Financial Institutions: Crypto Investing and Lending</label>
            </value>
            <value>
                <fullName>fiCryptoOnRamp</fullName>
                <label>Financial Institutions: Crypto On-Ramps / Retail OTC Trading</label>
            </value>
            <value>
                <fullName>fiCryptoWallets</fullName>
                <label>Financial Institutions: Crypto Wallets and Custodians</label>
            </value>
            <value>
                <fullName>fiOTC</fullName>
                <label>Financial Institutions: OTC Trading</label>
            </value>
            <value>
                <fullName>fiP2P</fullName>
                <label>Financial Institutions: Peer to Peer Payments / Money Transmitters</label>
            </value>
            <value>
                <fullName>healthCare</fullName>
                <label>Health Care</label>
            </value>
            <value>
                <fullName>manufacturingAutomobiles</fullName>
                <label>Manufacturing, Wholesale and Retail: Automobiles and Other Vehicles</label>
            </value>
            <value>
                <fullName>manufacturingElectronics</fullName>
                <label>Manufacturing, Wholesale and Retail: Electronics (including Computers)</label>
            </value>
            <value>
                <fullName>manufacturingJewelry</fullName>
                <label>Manufacturing, Wholesale and Retail: High Value Goods (Jewelry, Watches, Antiques)</label>
            </value>
            <value>
                <fullName>manufacturingOther</fullName>
                <label>Manufacturing, Wholesale and Retail: Other Goods</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Auto_Convert__c.field-meta.xml
<CustomField>
    <fullName>Auto_Convert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked this will trigger automation to auto convert a lead</description>
    <label>Auto Convert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <label>Email Domain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Is_this_a_work_email__c.field-meta.xml
<CustomField>
    <fullName>Is_this_a_work_email__c</fullName>
    <label>Is This a Work Email?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <label>Legal Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Nature_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Nature_of_Business__c</fullName>
    <label>Nature of Business</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>accommodation</fullName>
                <label>Accommodation and Food Services (excluding Casinos)</label>
            </value>
            <value>
                <fullName>accounting</fullName>
                <label>Accounting and Legal Firms</label>
            </value>
            <value>
                <fullName>agriculture</fullName>
                <label>Agriculture, Forestry, Fishing and Hunting</label>
            </value>
            <value>
                <fullName>art</fullName>
                <label>Art Dealers and Auction Houses</label>
            </value>
            <value>
                <fullName>casino</fullName>
                <label>Casinos and Gambling</label>
            </value>
            <value>
                <fullName>construction</fullName>
                <label>Construction</label>
            </value>
            <value>
                <fullName>cryptoNetwork</fullName>
                <label>Crypto Network</label>
            </value>
            <value>
                <fullName>dapp</fullName>
                <label>DApp Providers and Developers</label>
            </value>
            <value>
                <fullName>preciousMetals</fullName>
                <label>Dealers and Retailers of Physical Precious Metals and/or Precious Stones</label>
            </value>
            <value>
                <fullName>defiExchange</fullName>
                <label>DeFI: Decentralized Exchanges</label>
            </value>
            <value>
                <fullName>defiOther</fullName>
                <label>DeFi: Other</label>
            </value>
            <value>
                <fullName>defiWallet</fullName>
                <label>DeFI: Self-Hosted Wallets</label>
            </value>
            <value>
                <fullName>education</fullName>
                <label>Education</label>
            </value>
            <value>
                <fullName>familyOffices</fullName>
                <label>Family Offices and Personal Investment Companies</label>
            </value>
            <value>
                <fullName>film</fullName>
                <label>Film, Television, Internet, and Print media</label>
            </value>
            <value>
                <fullName>fiAssetMgr</fullName>
                <label>Financial Institutions: Asset Managers, Hedge Funds, and Funds</label>
            </value>
            <value>
                <fullName>fiBank</fullName>
                <label>Financial Institutions: Banks and Credit Unions</label>
            </value>
            <value>
                <fullName>fiBrokerDealer</fullName>
                <label>Financial Institutions: Broker Dealers</label>
            </value>
            <value>
                <fullName>fiCryptoATM</fullName>
                <label>Financial Institutions: Crypto ATM Operator</label>
            </value>
            <value>
                <fullName>fiCryptoExchanges</fullName>
                <label>Financial Institutions: Crypto Exchanges</label>
            </value>
            <value>
                <fullName>fiCryptoInvesting</fullName>
                <label>Financial Institutions: Crypto Investing and Lending</label>
            </value>
            <value>
                <fullName>fiCryptoOnRamp</fullName>
                <label>Financial Institutions: Crypto On-Ramps / Retail OTC Trading</label>
            </value>
            <value>
                <fullName>fiCryptoWallets</fullName>
                <label>Financial Institutions: Crypto Wallets and Custodians</label>
            </value>
            <value>
                <fullName>fiOTC</fullName>
                <label>Financial Institutions: OTC Trading</label>
            </value>
            <value>
                <fullName>fiP2P</fullName>
                <label>Financial Institutions: Peer to Peer Payments / Money Transmitters</label>
            </value>
            <value>
                <fullName>healthCare</fullName>
                <label>Health Care</label>
            </value>
            <value>
                <fullName>manufacturingAutomobiles</fullName>
                <label>Manufacturing, Wholesale and Retail: Automobiles and Other Vehicles</label>
            </value>
            <value>
                <fullName>manufacturingElectronics</fullName>
                <label>Manufacturing, Wholesale and Retail: Electronics (including Computers)</label>
            </value>
            <value>
                <fullName>manufacturingJewelry</fullName>
                <label>Manufacturing, Wholesale and Retail: High Value Goods (Jewelry, Watches, Antiques)</label>
            </value>
            <value>
                <fullName>manufacturingOther</fullName>
                <label>Manufacturing, Wholesale and Retail: Other Goods</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Switches__c/Trigger_Switches__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Trigger Switches</label>
</CustomObject>

force-app/main/default/objects/Trigger_Switches__c/fields/New_Lead_Conversion__c.field-meta.xml
<CustomField>
    <fullName>New_Lead_Conversion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New Lead Conversion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AutoLeadConvertTest.cls
@isTest(SeeAllData=true)
public class AutoLeadConvertTest {
    public static testmethod void convertLeadTest(){
        Trigger_Switches__c setting = [SELECT ID, New_Lead_Conversion__c FROM Trigger_Switches__C];
        setting.New_Lead_Conversion__c = False;
        update setting;
        Lead ld = [select id, auto_convert__c, email_domain__c, 
                   Legal_Entity_Name__c, Company from Lead 
                   where email_domain__c != null and nature_of_business__c = null limit 1];
        List<Lead> leadList = [select id, auto_convert__c, email_domain__c, Is_this_a_work_email__c,
                               Legal_Entity_Name__c, Company from Lead 
                   			   where email_domain__c != null and isconverted = false
                               limit 20];
        
        
        
        for(Lead l : leadList){
            l.Auto_Convert__c = true;
            L.Is_this_a_work_email__c = 'Yes';
            System.debug(l.Id);
        }
        ld.Auto_Convert__c = true;
        
        List<Lead> littleLeadList = [select id, auto_convert__c, email_domain__c, Legal_Entity_Name__c, Company from Lead 
                   			   where email_domain__c != null and isconverted = false
                               //and 
                               //(id = '00Q8L000001ghn3UAA')// or id = '00Q8L000001WjGLUA0' or 
                                //id = '00Q8L000001WjGKUA0' or id = '00Q8L000001WjGJUA0' or 
                                //id = '00Q8L000001WjGIUA0')
                               limit 5];
        for(Lead l : littleLeadList){
            l.Auto_Convert__c = true;
            System.debug(l.Id);
        }
        
        Lead insertLead = new Lead(LastName = 'test', Company = 'TestCompanyTesting123', email_domain__c = 'thisisatest12389.com', Auto_Convert__c = true);
        Lead insertLead1 = new Lead(LastName = 'test', Company = 'TestNameTest789', Legal_Entity_Name__c = 'TestNameTesting123', Auto_Convert__c = true,
                                    email_domain__c = 'thisisatest123489.com');
        Account acc = new Account(Name = 'TestCompanyTesting123');
        Account acc1 = new Account(Name = 'TestingHereAgain789', Legal_Entity_Name__c = 'TestNameTesting123');
        insert acc;
        insert acc1;
        Test.startTest();
        
        insert insertLead;
        insert insertLead1;
        update littleLeadList;
        update leadList;
        Test.stopTest();
        System.debug(insertLead.Company);
        System.debug(insertLead1.Legal_Entity_Name__c);
    }
}