force-app/main/default/objects/Account/fields/Nature_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Nature_of_Business__c</fullName>
    <label>Nature of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>accommodation</fullName>
                <label>Accommodation and Food Services (excluding Casinos)</label>
            </value>
            <value>
                <fullName>accounting</fullName>
                <label>Accounting and Legal Firms</label>
            </value>
            <value>
                <fullName>agriculture</fullName>
                <label>Agriculture, Forestry, Fishing and Hunting</label>
            </value>
            <value>
                <fullName>art</fullName>
                <label>Art Dealers and Auction Houses</label>
            </value>
            <value>
                <fullName>casino</fullName>
                <label>Casinos and Gambling</label>
            </value>
            <value>
                <fullName>construction</fullName>
                <label>Construction</label>
            </value>
            <value>
                <fullName>cryptoNetwork</fullName>
                <label>Crypto Network</label>
            </value>
            <value>
                <fullName>dapp</fullName>
                <label>DApp Providers and Developers</label>
            </value>
            <value>
                <fullName>preciousMetals</fullName>
                <label>Dealers and Retailers of Physical Precious Metals and/or Precious Stones</label>
            </value>
            <value>
                <fullName>defiExchange</fullName>
                <label>DeFI: Decentralized Exchanges</label>
            </value>
            <value>
                <fullName>defiOther</fullName>
                <label>DeFi: Other</label>
            </value>
            <value>
                <fullName>defiWallet</fullName>
                <label>DeFI: Self-Hosted Wallets</label>
            </value>
            <value>
                <fullName>education</fullName>
                <label>Education</label>
            </value>
            <value>
                <fullName>familyOffices</fullName>
                <label>Family Offices and Personal Investment Companies</label>
            </value>
            <value>
                <fullName>film</fullName>
                <label>Film, Television, Internet, and Print media</label>
            </value>
            <value>
                <fullName>fiAssetMgr</fullName>
                <label>Financial Institutions: Asset Managers, Hedge Funds, and Funds</label>
            </value>
            <value>
                <fullName>fiBank</fullName>
                <label>Financial Institutions: Banks and Credit Unions</label>
            </value>
            <value>
                <fullName>fiBrokerDealer</fullName>
                <label>Financial Institutions: Broker Dealers</label>
            </value>
            <value>
                <fullName>fiCryptoATM</fullName>
                <label>Financial Institutions: Crypto ATM Operator</label>
            </value>
            <value>
                <fullName>fiCryptoExchanges</fullName>
                <label>Financial Institutions: Crypto Exchanges</label>
            </value>
            <value>
                <fullName>fiCryptoInvesting</fullName>
                <label>Financial Institutions: Crypto Investing and Lending</label>
            </value>
            <value>
                <fullName>fiCryptoOnRamp</fullName>
                <label>Financial Institutions: Crypto On-Ramps / Retail OTC Trading</label>
            </value>
            <value>
                <fullName>fiCryptoWallets</fullName>
                <label>Financial Institutions: Crypto Wallets and Custodians</label>
            </value>
            <value>
                <fullName>fiOTC</fullName>
                <label>Financial Institutions: OTC Trading</label>
            </value>
            <value>
                <fullName>fiP2P</fullName>
                <label>Financial Institutions: Peer to Peer Payments / Money Transmitters</label>
            </value>
            <value>
                <fullName>healthCare</fullName>
                <label>Health Care</label>
            </value>
            <value>
                <fullName>manufacturingAutomobiles</fullName>
                <label>Manufacturing, Wholesale and Retail: Automobiles and Other Vehicles</label>
            </value>
            <value>
                <fullName>manufacturingElectronics</fullName>
                <label>Manufacturing, Wholesale and Retail: Electronics (including Computers)</label>
            </value>
            <value>
                <fullName>manufacturingJewelry</fullName>
                <label>Manufacturing, Wholesale and Retail: High Value Goods (Jewelry, Watches, Antiques)</label>
            </value>
            <value>
                <fullName>manufacturingOther</fullName>
                <label>Manufacturing, Wholesale and Retail: Other Goods</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SDR_Owner__c.field-meta.xml
<CustomField>
    <fullName>SDR_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SDR Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Data_Deleted_Customer_Request__c.field-meta.xml
<CustomField>
    <fullName>Data_Deleted_Customer_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Data Deleted / Customer Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Nature_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Nature_of_Business__c</fullName>
    <label>Nature of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Nature_of_Business</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SDR_Owner__c.field-meta.xml
<CustomField>
    <fullName>SDR_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SDR Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Auto_Convert__c.field-meta.xml
<CustomField>
    <fullName>Auto_Convert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked this will trigger automation to auto convert a lead</description>
    <label>Auto Convert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Data_Deleted_Customer_Request__c.field-meta.xml
<CustomField>
    <fullName>Data_Deleted_Customer_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Data Deleted Customer Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <label>Email Domain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Is_this_a_work_email__c.field-meta.xml
<CustomField>
    <fullName>Is_this_a_work_email__c</fullName>
    <label>Is This a Work Email?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <label>Legal Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Nature_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Nature_of_Business__c</fullName>
    <label>Nature of Business</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>accommodation</fullName>
                <label>Accommodation and Food Services (excluding Casinos)</label>
            </value>
            <value>
                <fullName>accounting</fullName>
                <label>Accounting and Legal Firms</label>
            </value>
            <value>
                <fullName>agriculture</fullName>
                <label>Agriculture, Forestry, Fishing and Hunting</label>
            </value>
            <value>
                <fullName>art</fullName>
                <label>Art Dealers and Auction Houses</label>
            </value>
            <value>
                <fullName>casino</fullName>
                <label>Casinos and Gambling</label>
            </value>
            <value>
                <fullName>construction</fullName>
                <label>Construction</label>
            </value>
            <value>
                <fullName>cryptoNetwork</fullName>
                <label>Crypto Network</label>
            </value>
            <value>
                <fullName>dapp</fullName>
                <label>DApp Providers and Developers</label>
            </value>
            <value>
                <fullName>preciousMetals</fullName>
                <label>Dealers and Retailers of Physical Precious Metals and/or Precious Stones</label>
            </value>
            <value>
                <fullName>defiExchange</fullName>
                <label>DeFI: Decentralized Exchanges</label>
            </value>
            <value>
                <fullName>defiOther</fullName>
                <label>DeFi: Other</label>
            </value>
            <value>
                <fullName>defiWallet</fullName>
                <label>DeFI: Self-Hosted Wallets</label>
            </value>
            <value>
                <fullName>education</fullName>
                <label>Education</label>
            </value>
            <value>
                <fullName>familyOffices</fullName>
                <label>Family Offices and Personal Investment Companies</label>
            </value>
            <value>
                <fullName>film</fullName>
                <label>Film, Television, Internet, and Print media</label>
            </value>
            <value>
                <fullName>fiAssetMgr</fullName>
                <label>Financial Institutions: Asset Managers, Hedge Funds, and Funds</label>
            </value>
            <value>
                <fullName>fiBank</fullName>
                <label>Financial Institutions: Banks and Credit Unions</label>
            </value>
            <value>
                <fullName>fiBrokerDealer</fullName>
                <label>Financial Institutions: Broker Dealers</label>
            </value>
            <value>
                <fullName>fiCryptoATM</fullName>
                <label>Financial Institutions: Crypto ATM Operator</label>
            </value>
            <value>
                <fullName>fiCryptoExchanges</fullName>
                <label>Financial Institutions: Crypto Exchanges</label>
            </value>
            <value>
                <fullName>fiCryptoInvesting</fullName>
                <label>Financial Institutions: Crypto Investing and Lending</label>
            </value>
            <value>
                <fullName>fiCryptoOnRamp</fullName>
                <label>Financial Institutions: Crypto On-Ramps / Retail OTC Trading</label>
            </value>
            <value>
                <fullName>fiCryptoWallets</fullName>
                <label>Financial Institutions: Crypto Wallets and Custodians</label>
            </value>
            <value>
                <fullName>fiOTC</fullName>
                <label>Financial Institutions: OTC Trading</label>
            </value>
            <value>
                <fullName>fiP2P</fullName>
                <label>Financial Institutions: Peer to Peer Payments / Money Transmitters</label>
            </value>
            <value>
                <fullName>healthCare</fullName>
                <label>Health Care</label>
            </value>
            <value>
                <fullName>manufacturingAutomobiles</fullName>
                <label>Manufacturing, Wholesale and Retail: Automobiles and Other Vehicles</label>
            </value>
            <value>
                <fullName>manufacturingElectronics</fullName>
                <label>Manufacturing, Wholesale and Retail: Electronics (including Computers)</label>
            </value>
            <value>
                <fullName>manufacturingJewelry</fullName>
                <label>Manufacturing, Wholesale and Retail: High Value Goods (Jewelry, Watches, Antiques)</label>
            </value>
            <value>
                <fullName>manufacturingOther</fullName>
                <label>Manufacturing, Wholesale and Retail: Other Goods</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/SDR_Owner__c.field-meta.xml
<CustomField>
    <fullName>SDR_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SDR Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads11</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadsTest.cls
@isTest 
public class LeadsTest {

    @TestSetup
    static void setup(){
        CircleTestDataFactory.insertCustomSettings();
    }

    @isTest static void testConvertLeadInsertMatchEmail(){
        Account act = CircleTestDataFactory.makeAccount();
        act.Email_Domain__c = 'circle.com';
        act.Name = 'not provided';
        insert act;

        Contact cont = CircleTestDataFactory.insertContactWithEmail(act.id, 'Test','Test','aidantest@circle.com');
    
        Lead testLead = CircleTestDataFactory.makeLead();
        testLead.Email = 'aidantest@circle.com';
        testLead.Email_Domain__c = 'circle.com';
        testLead.Is_this_a_work_email__c = 'Yes';
        testLead.Legal_Entity_Name__C = 'Legal Name To Account';
        testLead.Auto_Convert__c = true;

        Test.startTest();
            insert testLead;
        Test.stopTest();

        testLead = [SELECT ID, ConvertedAccountId, ConvertedContactID FROM Lead WHERE ID = :testLead.id];
        System.assertEquals(act.id, testLead.ConvertedAccountId);
        System.assertEquals(cont.id, testLead.ConvertedContactId);
        act = [SELECT Name FROM Account WHERE ID = :act.id];
        System.assertEquals('Legal Name To Account',act.name);
    }

    @isTest static void testConvertLeadInsert200Leads(){
        Account act = CircleTestDataFactory.makeAccount();
        act.Email_Domain__c = 'circlex.com';
        act.Name = 'The Company';
        insert act;

        Contact cont = CircleTestDataFactory.insertContactWithEmail(act.id, 'Test','Test','aidantest@circle.com');
    
        List<Lead> testLeads = CircleTestDataFactory.make200Leads('The Company');

        Test.startTest();
            insert testLeads;
        Test.stopTest();

        Lead testLead = [SELECT ID, ConvertedAccountId, ConvertedContactID FROM Lead WHERE ID = :testLeads.get(0).id];
        Lead testLead2 = [SELECT ID, ConvertedAccountId, ConvertedContactID FROM Lead WHERE ID = :testLeads.get(199).id];
        System.assertEquals(act.id, testLead.ConvertedAccountId);
        System.assertEquals(act.id, testLead2.ConvertedAccountId);
        System.assertNotEquals(cont.id, testLead.ConvertedContactId);
    }

    @isTest static void testConvertLeadUpdateMatchCompany(){
        Account act = CircleTestDataFactory.makeAccount();
        act.Email_Domain__c = 'circlex.com';
        act.Name = 'Test Circle X';
        insert act;

        Contact cont = CircleTestDataFactory.insertContactWithEmail(act.id, 'Test','Test','aidantest@circle.com');
    
        Lead testLead = CircleTestDataFactory.makeLead();
        testLead.Email = 'aidantest@circle.com';
        testLead.Email_Domain__c = 'notcircle.com';
        testLead.Company = 'Test Circle X';
        testLead.Is_this_a_work_email__c = 'Yes';
        insert testLead;

        Test.startTest();
            testLead.Auto_Convert__c = true;
            update testLead;
        Test.stopTest();

        testLead = [SELECT ID, ConvertedAccountId, ConvertedContactID FROM Lead WHERE ID = :testLead.id];
        System.assertEquals(act.id, testLead.ConvertedAccountId);
        System.assertEquals(cont.id, testLead.ConvertedContactId);
    }

    @isTest static void testConvertLeadUpdateMatchLegalEntity(){
        Account act = CircleTestDataFactory.makeAccount();
        act.Email_Domain__c = 'circlex.com';
        act.Legal_Entity_Name__c = 'Match Legal Name';
        act.Name = 'Not Test Circle X';
        insert act;

        Contact cont = CircleTestDataFactory.insertContactWithEmail(act.id, 'Test','Test','aidantest@circle.com');
    
        Lead testLead = CircleTestDataFactory.makeLead();
        testLead.Email = 'aidantest@circle.com';
        testLead.Email_Domain__c = 'notcircle.com';
        testLead.Company = 'Test Circle X';
        testLead.Is_this_a_work_email__c = 'Yes';
        testLead.Legal_Entity_Name__c = 'Match Legal Name';
        insert testLead;

        Test.startTest();
            testLead.Auto_Convert__c = true;
            update testLead;
        Test.stopTest();

        testLead = [SELECT ID, ConvertedAccountId, ConvertedContactID FROM Lead WHERE ID = :testLead.id];
        System.assertEquals(act.id, testLead.ConvertedAccountId);
        System.assertEquals(cont.id, testLead.ConvertedContactId);
    }

    
    @isTest static void testConvertLeadErrorCoverage(){
        Account act = CircleTestDataFactory.makeAccount();
        act.Email_Domain__c = 'circlex.com';
        act.Legal_Entity_Name__c = 'Match Legal Name';
        act.Name = 'Not Test Circle X';
        insert act;

        Contact cont = CircleTestDataFactory.insertContactWithEmail(act.id, 'Test','Test','aidantest@circle.com');
    
        Lead testLead = CircleTestDataFactory.makeLead();
        testLead.Email = 'aidantest@circle.com';
        testLead.Email_Domain__c = 'notcircle.com';
        testLead.Company = 'Test Circle X';
        testLead.Is_this_a_work_email__c = 'Yes';
        testLead.Legal_Entity_Name__c = 'Match Legal Name';
        testLead.Nature_Of_Business__c = 'FAIL';
        testLead.Auto_Convert__c = true;
        
        Test.startTest();
            insert testLead;
        Test.stopTest();
        //test doesn't have asserts because no error is thrown - sent via email
    }

    @isTest static void testConvertLeadNoMatch(){
        Account act = CircleTestDataFactory.makeAccount();
        act.Email_Domain__c = 'circlex.com';
        act.Legal_Entity_Name__c = 'Match Legal Name';
        act.Name = 'Not Test Circle X';
        insert act;

        Contact cont = CircleTestDataFactory.insertContactWithEmail(act.id, 'Test','Test','aidantest2@circle.com');
    
        Lead testLead = CircleTestDataFactory.makeLead();
        testLead.Email = 'aidantest@circle.com';
        testLead.Email_Domain__c = 'notcirclexx.com';
        testLead.Company = 'Test Circle Xxx';
        testLead.Is_this_a_work_email__c = 'Yes';
        testLead.Legal_Entity_Name__c = 'Match Legal Namexx';
        testLead.Auto_Convert__c = true;
        
        Test.startTest();
            insert testLead;
        Test.stopTest();
        testLead = [SELECT ID, ConvertedAccountId, ConvertedContactID FROM Lead WHERE ID = :testLead.id];
        System.assertNotEquals(act.id, testLead.ConvertedAccountId);
        System.assertNotEquals(cont.id, testLead.ConvertedContactId);
    }

    @isTest static void testConvertLeadMatchJustContact(){
        Account act = CircleTestDataFactory.makeAccount();
        act.Email_Domain__c = 'circlex.com';
        act.Legal_Entity_Name__c = 'Match Legal Name';
        act.Name = 'Not Test Circle X';
        insert act;

        Contact cont = CircleTestDataFactory.insertContactWithEmail(act.id, 'Test','Test','aidantest@circle.com');
    
        Lead testLead = CircleTestDataFactory.makeLead();
        testLead.Email = 'aidantest@circle.com';
        testLead.Email_Domain__c = 'notcirclexx.com';
        testLead.Company = 'Test Circle Xxx';
        testLead.Is_this_a_work_email__c = 'Yes';
        testLead.Legal_Entity_Name__c = 'Match Legal Namexx';
        testLead.Auto_Convert__c = true;
        
        Test.startTest();
            insert testLead;
        Test.stopTest();
        testLead = [SELECT ID, ConvertedAccountId, ConvertedContactID FROM Lead WHERE ID = :testLead.id];
        System.assertEquals(act.id, testLead.ConvertedAccountId);
        System.assertEquals(cont.id, testLead.ConvertedContactId);
    }

    @isTest static void testConvertLeadNoMatchOwnerSDR(){
        User u = CircleTestDataFactory.insertUser();
        Account act = CircleTestDataFactory.makeAccount();
        act.Email_Domain__c = 'circlex.com';
        act.Legal_Entity_Name__c = 'Match Legal Name';
        act.Name = 'Not Test Circle X';
        insert act;
        

        Contact cont = CircleTestDataFactory.insertContactWithEmail(act.id, 'Test','Test','aidantest2@circle.com');
    
        Lead testLead = CircleTestDataFactory.makeLead();
        testLead.Email = 'aidantest@circle.com';
        testLead.Email_Domain__c = 'notcirclexx.com';
        testLead.Company = 'Test Circle Xxx';
        testLead.Is_this_a_work_email__c = 'Yes';
        testLead.Legal_Entity_Name__c = 'Match Legal Namexx';
        testLead.Auto_Convert__c = true;
        testLead.SDR_Owner__c = u.id;
        
        Test.startTest();
            insert testLead;
        Test.stopTest();
        testLead = [SELECT ID, ConvertedAccountId, ConvertedContactID FROM Lead WHERE ID = :testLead.id];
        System.assertNotEquals(act.id, testLead.ConvertedAccountId);
        System.assertNotEquals(cont.id, testLead.ConvertedContactId);
        List<Account> newAccounts = [SELECT id, name, legal_entity_name__c, OwnerID FROM Account];
        System.assertEquals(2, newAccounts.size());

    }

    @isTest static void testDataDeletedLead(){
        Lead lead = new Lead(Email = 'abc@gmail.com',FirstName = 'Aidan', LastName = 'test', Company = 'Aidan Test', Status='New');
        insert lead;

        Test.startTest();
            lead.Data_Deleted_Customer_Request__c = true;
            update lead;
        Test.stopTest();

        lead = [SELECT ID, FirstName, Email FROM Lead WHERE ID = :lead.id];
        System.assertEquals('data_deleted_abc@gmail.com', lead.Email);
        System.assertEquals('Data Deleted', lead.FirstName);
    }
}