force-app/main/default/objects/Account/fields/Performance_Objective_Health__c.field-meta.xml
<CustomField>
    <fullName>Performance_Objective_Health__c</fullName>
    <label>Performance Objective Health</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Off Track</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>On Track</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Objective Not Met</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Exceeded Expectations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stablecoin__c.field-meta.xml
<CustomField>
    <fullName>Stablecoin__c</fullName>
    <description>Used on Business Development Opportunities - Growth / Incentive Campaigns</description>
    <label>Stablecoin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USDC</fullName>
            </value>
            <value>
                <fullName>EUROC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/Partnership_Objective__c.object-meta.xml
<CustomObject>
    <description>Track the key objectives of our customer relationships</description>
    <label>Partnership Objective</label>
    <nameField>
        <label>Partnership Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnership Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partnership_Objective__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field should auto-populate, but should be checked to ensure that the correct Salesforce Account is associated with the Partnership Objective</description>
    <inlineHelpText>This field should auto-populate, but should be checked to ensure that the correct Salesforce Account is associated with the Partnership Objective</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partnership Objectives</relationshipLabel>
    <relationshipName>Partnership_Objectives</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Segment__c</fullName>
    <description>This field should indicate the appropriate customer segment so that we can evaluate the impact of our Partnership Objectives across the various strategic customer segments</description>
    <inlineHelpText>This field should indicate the appropriate customer segment so that we can evaluate the impact of our Partnership Objectives across the various strategic customer segments</inlineHelpText>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Blockchains</fullName>
            </value>
            <value>
                <fullName>Crypto Custodians</fullName>
            </value>
            <value>
                <fullName>Crypto Exchanges</fullName>
            </value>
            <value>
                <fullName>DeFi Protocols</fullName>
            </value>
            <value>
                <fullName>Investment Platforms</fullName>
            </value>
            <value>
                <fullName>NGOs</fullName>
            </value>
            <value>
                <fullName>OTC Desks &amp; Market Makers</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Regional Stablecoins</fullName>
            </value>
            <value>
                <fullName>Remittance Platforms / Payment Technologies</fullName>
            </value>
            <value>
                <fullName>Strategic Enterprise Accounts</fullName>
            </value>
            <value>
                <fullName>Super Apps / Consumer Digital Wallets</fullName>
            </value>
            <value>
                <fullName>Web3 Platforms / Integrators</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Deal_Construct__c.field-meta.xml
<CustomField>
    <fullName>Deal_Construct__c</fullName>
    <description>This field is optional, but it should indicate what type of deal construct the Partnership Objective stems from when associated with a deal</description>
    <inlineHelpText>This field is optional, but it should indicate what type of deal construct the Partnership Objective stems from when associated with a deal</inlineHelpText>
    <label>Deal Construct</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activation Incentive</fullName>
            </value>
            <value>
                <fullName>Blockchain</fullName>
            </value>
            <value>
                <fullName>Channel Sales</fullName>
            </value>
            <value>
                <fullName>Performance Incentive</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Product Integration</fullName>
            </value>
            <value>
                <fullName>Referrals</fullName>
            </value>
            <value>
                <fullName>ITP</fullName>
            </value>
            <value>
                <fullName>Indirect Liquidity</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
                <isActive>false</isActive>
                <label>Channel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Liquidity__c.field-meta.xml
<CustomField>
    <fullName>Liquidity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field should be selected when the Partnership Object supports the Commercial team’s objective of making USDC the most liquid, and accessible digital dollar</description>
    <inlineHelpText>This field should be selected when the Partnership Object supports the Commercial team’s objective of making USDC the most liquid, and accessible digital dollar</inlineHelpText>
    <label>Liquidity_DNU</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Objective_Description__c.field-meta.xml
<CustomField>
    <fullName>Objective_Description__c</fullName>
    <description>This field should include include no more than a sentence and form an exacting definition of the objective</description>
    <inlineHelpText>This field should include include no more than a sentence and form an exacting definition of the objective</inlineHelpText>
    <label>Objective Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Objective_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Objective_End_Date__c</fullName>
    <description>This field should indicate when we expect to fulfill the objective</description>
    <inlineHelpText>This field should indicate when we expect to fulfill the objective</inlineHelpText>
    <label>Objective End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Objective_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Objective_Start_Date__c</fullName>
    <description>This field should indicate when active work on the objective will begin</description>
    <inlineHelpText>This field should indicate when active work on the objective will begin</inlineHelpText>
    <label>Objective Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Objective_Status__c.field-meta.xml
<CustomField>
    <fullName>Objective_Status__c</fullName>
    <description>This field should indicate the most current status of the objective based on the goals defined, the current progress, and the planned completion</description>
    <inlineHelpText>This field should indicate the most current status of the objective based on the goals defined, the current progress, and the planned completion</inlineHelpText>
    <label>Objective Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onboarding</fullName>
                <color>#F3D904</color>
                <label>Onboarding</label>
            </value>
            <value>
                <fullName>Pre-Launch</fullName>
                <color>#E27001</color>
                <label>Pre-Launch</label>
            </value>
            <value>
                <fullName>Launched</fullName>
                <color>#419249</color>
                <label>Launched</label>
            </value>
            <value>
                <fullName>Not Active</fullName>
                <color>#BBBBBB</color>
                <label>Not Active</label>
            </value>
            <value>
                <fullName>At Risk</fullName>
                <isActive>false</isActive>
                <label>At Risk</label>
            </value>
            <value>
                <fullName>Exceeded Expectations</fullName>
                <isActive>false</isActive>
                <label>Exceeded Expectations</label>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <isActive>false</isActive>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Objective Not Met</fullName>
                <isActive>false</isActive>
                <label>Objective Not Met</label>
            </value>
            <value>
                <fullName>Off Track</fullName>
                <isActive>false</isActive>
                <label>Off Track</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <isActive>false</isActive>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>On Track</fullName>
                <isActive>false</isActive>
                <label>On Track</label>
            </value>
            <value>
                <fullName>Successful</fullName>
                <isActive>false</isActive>
                <label>Successful</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is optional, but should be filled in most cases since the majority of objectives will stem from a specific Opportunity</description>
    <inlineHelpText>This field is optional, but should be filled in most cases since the majority of objectives will stem from a specific Opportunity</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Partnership Objectives</relationshipLabel>
    <relationshipName>Partnership_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Pillar__c.field-meta.xml
<CustomField>
    <fullName>Pillar__c</fullName>
    <description>This field should indicate the Commercial Pillar this Partnership Objective is tied to. Since some Accounts have multi-Pillar Opportunities, this can most commonly be thought of as the PM&apos;s assigned Pillar</description>
    <inlineHelpText>This field should indicate the Commercial Pillar this Partnership Objective is tied to. Since some Accounts have multi-Pillar Opportunities, this can most commonly be thought of as the PM&apos;s assigned Pillar</inlineHelpText>
    <label>Pillar</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ecosystem</fullName>
            </value>
            <value>
                <fullName>Liquidity</fullName>
            </value>
            <value>
                <fullName>Platform Distribution</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Stablecoin__c.field-meta.xml
<CustomField>
    <fullName>Stablecoin__c</fullName>
    <description>This field should indicate USDC in most cases, but for certain opportunities, the Partnership Objective will focus on the growth of EUROC or other stablecoins in the future</description>
    <inlineHelpText>This field should indicate USDC in most cases, but for certain opportunities, the Partnership Objective will focus on the growth of EUROC or other stablecoins in the future</inlineHelpText>
    <label>Stablecoin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USDC</fullName>
            </value>
            <value>
                <fullName>EURC</fullName>
            </value>
            <value>
                <fullName>EUROC</fullName>
                <isActive>false</isActive>
                <label>EUROC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This field is used by CSMs to separate Partner Objectives</description>
    <inlineHelpText>Keep the default for specific Partnership Objectives. Switch to Partner Metrics Tracking to track starting and current metrics.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Objective Tracking</fullName>
            </value>
            <value>
                <fullName>Partner Metrics Tracking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PartnershipObjectivesTest.cls
@isTest
public class PartnershipObjectivesTest {

    @TestSetup
    static void setup(){
        CircleTestDataFactory.insertCustomSettings();
    }

    @isTest static void testInsertPartnershipObjectiveRollupHealthLaunchStatus(){
        Account act = CircleTestDataFactory.insertAccount();
        Account act2 = act.clone(false,true);
        insert act2;
        Opportunity opp = CircleTestDataFactory.insertOpportunity(act.Id, 'Test', Date.today(), 'Circle Mint');
        Partnership_Objective__c obj = new Partnership_Objective__c(Account__c = act.id, Opportunity__c = opp.id, Objective_Description__c = 'test',Customer_Segment__c='Banks',Deal_Construct__c = 'Blockchain',Liquidity__c=true,Objective_End_Date__c=Date.today(),Objective_start_date__C = Date.today(),Pillar__c='Liquidity',Stablecoin__c = 'USDC',Objective_Status__c='Onboarding', Type__c = 'Partner Metrics Tracking',Performance_Objective_Health__c='Not Started');
        insert obj;
        Test.setCreatedDate(obj.id,Date.today().addDays(-1));
        Test.startTest();
            act = [SELECT ID, Performance_Objective_Health__c,Launch_Status__c FROM Account WHERE ID = :act.id];
            System.assertEquals('Not Started', act.Performance_Objective_Health__c);
            System.assertEquals('Onboarding', act.Launch_Status__c);
            Partnership_Objective__c obj2 = new Partnership_Objective__c(Account__c = act.id, Opportunity__c = opp.id, Objective_Description__c = 'test',Customer_Segment__c='Banks',Deal_Construct__c = 'Blockchain',Liquidity__c=true,Objective_End_Date__c=Date.today(),Objective_start_date__C = Date.today(),Pillar__c='Liquidity',Stablecoin__c = 'USDC',Objective_Status__c='Launched', Type__c = 'Partner Metrics Tracking',Performance_Objective_Health__c='On Track');
            insert obj2;
            act = [SELECT ID, Performance_Objective_Health__c,Launch_Status__c FROM Account WHERE ID = :act.id];
            System.assertEquals('On Track', act.Performance_Objective_Health__c);
            System.assertEquals('Launched', act.Launch_Status__c);
            obj2.Objective_Status__c = 'Onboarding';
            update obj2;
            act = [SELECT ID, Performance_Objective_Health__c,Launch_Status__c FROM Account WHERE ID = :act.id];
            System.assertEquals('On Track', act.Performance_Objective_Health__c);
            System.assertEquals('Onboarding', act.Launch_Status__c);
        Test.stopTest();
    }

    @isTest static void testMostRecentNoteHistory(){
        Account act = CircleTestDataFactory.insertAccount();
        Contact cont = CircleTestDataFactory.insertContact(act.id, 'first', 'last', null);
        Opportunity opp = CircleTestDataFactory.insertOpportunity(act.Id, 'Name', Date.today(), 'Circle Mint');
        Partnership_Objective__c obj = new Partnership_Objective__c(Account__c = act.id, Opportunity__c = opp.id, Objective_Description__c = 'test',Customer_Segment__c='Banks',Deal_Construct__c = 'Blockchain',Liquidity__c=true,Objective_End_Date__c=Date.today(),Objective_start_date__C = Date.today(),Pillar__c='Liquidity',Stablecoin__c = 'USDC',Objective_Status__c='Onboarding', Type__c = 'Objective Tracking',Performance_Objective_Health__c='On Track');
        insert obj;

        ContentNote objCntNote = new ContentNote();
        objCntNote.Title = 'Note Title';
        objCntNote.Content = Blob.valueOf('Note Content');
        insert objCntNote;

        ContentDocumentLink objCntDocLink = new ContentDocumentLink();
        objCntDocLink.LinkedEntityId = obj.id; 
        objCntDocLink.ContentDocumentId = objCntNote.Id; 
        objCntDocLink.shareType = 'V'; 
        insert objCntDocLink;
        
        Test.startTest();
            PartnershipObjectiveSetNoteBatch b = new PartnershipObjectiveSetNoteBatch();
            Database.executeBatch(b, 1);
        Test.stopTest();

        obj = [SELECT Most_Recent_Note__c, Most_recent_Note_History__c FROM Partnership_Objective__c WHERE ID = :obj.id];
        System.assertEquals('Note Content', obj.Most_Recent_Note__c);
        System.assertEquals('('+String.valueOf(Date.today())+') : Note Content', obj.Most_recent_Note_HIstory__C);
        obj.Most_recent_note__C = 'TEST 123';
        update obj;
        obj = [SELECT Most_Recent_Note__c, Most_recent_Note_History__c FROM Partnership_Objective__c WHERE ID = :obj.id];
        System.assertEquals('('+String.valueOf(Date.today())+') : TEST 123<br><br>('+String.valueOf(Date.today())+') : Note Content', obj.Most_recent_Note_History__c);
    }

    @isTest static void testAccountRollUpPOCalculationFields(){
        Account act = CircleTestDataFactory.insertAccount();
        Opportunity opp = CircleTestDataFactory.insertOpportunity(act.Id, 'Test', Date.today(), 'Circle Mint');
        opp.Success_Metrics__c = 'MEWs;USDC On Platform;Transaction Volume;Other';
        update opp;
        Partnership_Objective__c obj = new Partnership_Objective__c(Account__c = act.id, Opportunity__c = opp.id, Objective_Description__c = 'test',Customer_Segment__c='Banks',Deal_Construct__c = 'Blockchain',Liquidity__c=true,Objective_End_Date__c=Date.today(),Objective_start_date__C = Date.today(),Pillar__c='Liquidity',Objective_Status__c='Onboarding', Type__c = 'Partner Metrics Tracking',Performance_Objective_Health__c='Not Started');
        
        obj.Current_MEWs__c = 2;
        obj.Current_Stablecoin_Liquidity__c = 2;
        obj.Current_Stablecoin_Volume__c = 2;
        obj.Projected_MEWs_Growth__c = 2;
        obj.Projected_Stablecoin_on_Platform_Growth__c = 2;
        obj.Projected_Total_Stablecoin_Volume__c = 2;
        
        insert obj;
        Test.setCreatedDate(obj.id,Date.today().addDays(-1));
        Test.startTest();
            obj = [SELECT ID, Projected_Metrics__C,Current_Metrics__c,Attainment__c FROM Partnership_Objective__c WHERE ID = :obj.id];
            System.assertEquals('MEWs: 2<br>USDC On Platform: $2<br>Transaction Volume: $2',obj.Projected_Metrics__C);
            System.assertEquals('MEWs: 2<br>USDC On Platform: $2<br>Transaction Volume: $2',obj.Current_Metrics__c);
            System.assertEquals('MEWs: 100%<br>USDC On Platform: 100%<br>Transaction Volume: 100%',obj.Attainment__c);
            obj.Current_MEWs__c = 1;
            obj.Current_Stablecoin_Liquidity__c = 1;
            obj.Current_Stablecoin_Volume__c = 1;
            obj.Custom_Metric__c = 1234;
            update obj;
            obj = [SELECT ID, Projected_Metrics__C,Current_Metrics__c,Attainment__c FROM Partnership_Objective__c WHERE ID = :obj.id];
            System.assertEquals('MEWs: 2<br>USDC On Platform: $2<br>Transaction Volume: $2',obj.Projected_Metrics__C);
            System.assertEquals('MEWs: 1<br>USDC On Platform: $1<br>Transaction Volume: $1',obj.Current_Metrics__c);
            System.assertEquals('MEWs: 50%<br>USDC On Platform: 50%<br>Transaction Volume: 50%',obj.Attainment__c);
            obj.Custom_Metric__c = 12345;
            opp.Success_Metrics__c = 'Other';
            update opp;
            update obj;
            obj = [SELECT ID, Projected_Metrics__C,Current_Metrics__c,Attainment__c FROM Partnership_Objective__c WHERE ID = :obj.id];
            System.assertEquals('Click into Partnership Objective for Detail',obj.Projected_Metrics__C);
            System.assertEquals('Click into Partnership Objective for Detail',obj.Current_Metrics__c);
            System.assertEquals('Click into Partnership Objective for Detail',obj.Attainment__c);
        Test.stopTest();
    }
}