force-app/main/default/objects/Account/fields/Performance_Objective_Health__c.field-meta.xml
<CustomField>
    <fullName>Performance_Objective_Health__c</fullName>
    <label>Performance Objective Health</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Off Track</fullName>
            </value>
            <value>
                <fullName>At Risk</fullName>
            </value>
            <value>
                <fullName>On Track</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Objective Not Met</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Exceeded Expectations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stablecoin__c.field-meta.xml
<CustomField>
    <fullName>Stablecoin__c</fullName>
    <description>Used on Business Development Opportunities - Growth / Incentive Campaigns</description>
    <label>Stablecoin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USDC</fullName>
            </value>
            <value>
                <fullName>EUROC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/Partnership_Objective__c.object-meta.xml
<CustomObject>
    <description>Track the key objectives of our customer relationships</description>
    <label>Partnership Objective</label>
    <nameField>
        <label>Partnership Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnership Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partnership_Objective__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field should auto-populate, but should be checked to ensure that the correct Salesforce Account is associated with the Partnership Objective</description>
    <inlineHelpText>This field should auto-populate, but should be checked to ensure that the correct Salesforce Account is associated with the Partnership Objective</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partnership Objectives</relationshipLabel>
    <relationshipName>Partnership_Objectives</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Customer_Segment__c.field-meta.xml
<CustomField>
    <fullName>Customer_Segment__c</fullName>
    <description>This field should indicate the appropriate customer segment so that we can evaluate the impact of our Partnership Objectives across the various strategic customer segments</description>
    <inlineHelpText>This field should indicate the appropriate customer segment so that we can evaluate the impact of our Partnership Objectives across the various strategic customer segments</inlineHelpText>
    <label>Customer Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Banks</fullName>
            </value>
            <value>
                <fullName>Blockchains</fullName>
            </value>
            <value>
                <fullName>Crypto Custodians</fullName>
            </value>
            <value>
                <fullName>Crypto Exchanges</fullName>
            </value>
            <value>
                <fullName>DeFi Protocols</fullName>
            </value>
            <value>
                <fullName>Investment Platforms</fullName>
            </value>
            <value>
                <fullName>NGOs</fullName>
            </value>
            <value>
                <fullName>OTC Desks &amp; Market Makers</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Regional Stablecoins</fullName>
            </value>
            <value>
                <fullName>Remittance Platforms / Payment Technologies</fullName>
            </value>
            <value>
                <fullName>Strategic Enterprise Accounts</fullName>
            </value>
            <value>
                <fullName>Super Apps / Consumer Digital Wallets</fullName>
            </value>
            <value>
                <fullName>Web3 Platforms / Integrators</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Deal_Construct__c.field-meta.xml
<CustomField>
    <fullName>Deal_Construct__c</fullName>
    <description>This field is optional, but it should indicate what type of deal construct the Partnership Objective stems from when associated with a deal</description>
    <inlineHelpText>This field is optional, but it should indicate what type of deal construct the Partnership Objective stems from when associated with a deal</inlineHelpText>
    <label>Deal Construct</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Activation Incentive</fullName>
            </value>
            <value>
                <fullName>Blockchain</fullName>
            </value>
            <value>
                <fullName>Channel Sales</fullName>
            </value>
            <value>
                <fullName>Performance Incentive</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Product Integration</fullName>
            </value>
            <value>
                <fullName>Referrals</fullName>
            </value>
            <value>
                <fullName>ITP</fullName>
            </value>
            <value>
                <fullName>Indirect Liquidity</fullName>
            </value>
            <value>
                <fullName>Channel</fullName>
                <isActive>false</isActive>
                <label>Channel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Liquidity__c.field-meta.xml
<CustomField>
    <fullName>Liquidity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field should be selected when the Partnership Object supports the Commercial team’s objective of making USDC the most liquid, and accessible digital dollar</description>
    <inlineHelpText>This field should be selected when the Partnership Object supports the Commercial team’s objective of making USDC the most liquid, and accessible digital dollar</inlineHelpText>
    <label>Liquidity_DNU</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Objective_Description__c.field-meta.xml
<CustomField>
    <fullName>Objective_Description__c</fullName>
    <description>This field should include include no more than a sentence and form an exacting definition of the objective</description>
    <inlineHelpText>This field should include include no more than a sentence and form an exacting definition of the objective</inlineHelpText>
    <label>Objective Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Objective_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Objective_End_Date__c</fullName>
    <description>This field should indicate when we expect to fulfill the objective</description>
    <inlineHelpText>This field should indicate when we expect to fulfill the objective</inlineHelpText>
    <label>Objective End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Objective_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Objective_Start_Date__c</fullName>
    <description>This field should indicate when active work on the objective will begin</description>
    <inlineHelpText>This field should indicate when active work on the objective will begin</inlineHelpText>
    <label>Objective Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Objective_Status__c.field-meta.xml
<CustomField>
    <fullName>Objective_Status__c</fullName>
    <description>This field should indicate the most current status of the objective based on the goals defined, the current progress, and the planned completion</description>
    <inlineHelpText>This field should indicate the most current status of the objective based on the goals defined, the current progress, and the planned completion</inlineHelpText>
    <label>Objective Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onboarding</fullName>
                <color>#F3D904</color>
                <label>Onboarding</label>
            </value>
            <value>
                <fullName>Pre-Launch</fullName>
                <color>#E27001</color>
                <label>Pre-Launch</label>
            </value>
            <value>
                <fullName>Launched</fullName>
                <color>#419249</color>
                <label>Launched</label>
            </value>
            <value>
                <fullName>Not Active</fullName>
                <color>#BBBBBB</color>
                <label>Not Active</label>
            </value>
            <value>
                <fullName>At Risk</fullName>
                <isActive>false</isActive>
                <label>At Risk</label>
            </value>
            <value>
                <fullName>Exceeded Expectations</fullName>
                <isActive>false</isActive>
                <label>Exceeded Expectations</label>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <isActive>false</isActive>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Objective Not Met</fullName>
                <isActive>false</isActive>
                <label>Objective Not Met</label>
            </value>
            <value>
                <fullName>Off Track</fullName>
                <isActive>false</isActive>
                <label>Off Track</label>
            </value>
            <value>
                <fullName>On Hold</fullName>
                <isActive>false</isActive>
                <label>On Hold</label>
            </value>
            <value>
                <fullName>On Track</fullName>
                <isActive>false</isActive>
                <label>On Track</label>
            </value>
            <value>
                <fullName>Successful</fullName>
                <isActive>false</isActive>
                <label>Successful</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is optional, but should be filled in most cases since the majority of objectives will stem from a specific Opportunity</description>
    <inlineHelpText>This field is optional, but should be filled in most cases since the majority of objectives will stem from a specific Opportunity</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Partnership Objectives</relationshipLabel>
    <relationshipName>Partnership_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Pillar__c.field-meta.xml
<CustomField>
    <fullName>Pillar__c</fullName>
    <description>This field should indicate the Commercial Pillar this Partnership Objective is tied to. Since some Accounts have multi-Pillar Opportunities, this can most commonly be thought of as the PM&apos;s assigned Pillar</description>
    <inlineHelpText>This field should indicate the Commercial Pillar this Partnership Objective is tied to. Since some Accounts have multi-Pillar Opportunities, this can most commonly be thought of as the PM&apos;s assigned Pillar</inlineHelpText>
    <label>Pillar</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ecosystem</fullName>
            </value>
            <value>
                <fullName>Liquidity</fullName>
            </value>
            <value>
                <fullName>Platform Distribution</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Stablecoin__c.field-meta.xml
<CustomField>
    <fullName>Stablecoin__c</fullName>
    <description>This field should indicate USDC in most cases, but for certain opportunities, the Partnership Objective will focus on the growth of EUROC or other stablecoins in the future</description>
    <inlineHelpText>This field should indicate USDC in most cases, but for certain opportunities, the Partnership Objective will focus on the growth of EUROC or other stablecoins in the future</inlineHelpText>
    <label>Stablecoin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USDC</fullName>
            </value>
            <value>
                <fullName>EURC</fullName>
            </value>
            <value>
                <fullName>EUROC</fullName>
                <isActive>false</isActive>
                <label>EUROC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This field is used by CSMs to separate Partner Objectives</description>
    <inlineHelpText>Keep the default for specific Partnership Objectives. Switch to Partner Metrics Tracking to track starting and current metrics.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Objective Tracking</fullName>
            </value>
            <value>
                <fullName>Partner Metrics Tracking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PartnershipObjectiveNotificatioBatchTest.cls
@isTest 
public class PartnershipObjectiveNotificatioBatchTest {

    @TestSetup
    static void setup(){
        CircleTestDataFactory.insertCustomSettings();
    }

    @isTest static void testNotificationCreation(){
        Account act = CircleTestDataFactory.insertAccount();
        Contact cont = CircleTestDataFactory.insertContact(act.id, 'first', 'last', null);
        Opportunity opp = CircleTestDataFactory.insertOpportunity(act.Id, 'Name', Date.today(), 'Circle Mint');
        Partnership_Objective__c obj = new Partnership_Objective__c(Account__c = act.id, Opportunity__c = opp.id, Objective_Description__c = 'test',Customer_Segment__c='Banks',Deal_Construct__c = 'Blockchain',Liquidity__c=true,Objective_End_Date__c=Date.today()+100,Objective_start_date__C = Date.today()-30,Pillar__c='Liquidity',Stablecoin__c = 'USDC',Objective_Status__c='Onboarding', Type__c = 'Partner Metrics Tracking',Performance_Objective_Health__c='On Track');
        insert obj;
        
        Test.startTest();
            PartnershipObjectiveNotificationsBatch b = new PartnershipObjectiveNotificationsBatch();
            Database.executeBatch(b, 1);
        Test.stopTest();

        List<Task> taskss = [SELECT ID FROM Task WHERE WhatID = :obj.id];
        System.assertEquals(1, taskss.size());
    }

    @isTest static void testSchuedlePartnershipNotificationBatch(){
        String year = String.valueOf(Date.today().addYears(1).year());
        String CRON_EXP = '0 0 0 3 9 ? '+year;
        // Schedule the test job
        String jobId = System.schedule('SchedulePartnershipObjNotificationBatch', CRON_EXP, new SchedulePartnershipObjNotificationBatch());
        // Get the information from the CronTrigger API object 
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId]; 
        // Verify the expressions are the same System.assertEquals(CRON_EXP, ct.CronExpression); 
        // Verify the job has not run 
        System.assertEquals(0, ct.TimesTriggered); 
        // Verify the next time the job will run 
        System.assertEquals(year+'-09-03 00:00:00', String.valueOf(ct.NextFireTime));         
    }
}