force-app/main/default/objects/Account/fields/Platform_Owner__c.field-meta.xml
<CustomField>
    <fullName>Platform_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Platform Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Post_Sales_Solution_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Post_Sales_Solution_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Post-Sales Solution Engineer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountsGrmS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Pre_Sales_Solution_Engineer__c.field-meta.xml
<CustomField>
    <fullName>Pre_Sales_Solution_Engineer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pre-Sales Solution Engineer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts10</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Treasury_Owner__c.field-meta.xml
<CustomField>
    <fullName>Treasury_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treasury Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Update_Opp_Team_Members__c.field-meta.xml
<CustomField>
    <fullName>Update_Opp_Team_Members__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Update Opp Team Members</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_s__c.field-meta.xml
<CustomField>
    <fullName>Product_s__c</fullName>
    <inlineHelpText>Select all applicable products that are related to this opportunity.</inlineHelpText>
    <label>Product(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>247Book</fullName>
                <label>24/7 Book</label>
            </value>
            <value>
                <fullName>Accounts API</fullName>
            </value>
            <value>
                <fullName>Activation Incentives</fullName>
            </value>
            <value>
                <fullName>Blockchain Partnerships</fullName>
            </value>
            <value>
                <fullName>Bridged USDC Standard</fullName>
            </value>
            <value>
                <fullName>CCTP</fullName>
            </value>
            <value>
                <fullName>Channel Sales</fullName>
            </value>
            <value>
                <fullName>Core API</fullName>
            </value>
            <value>
                <fullName>Crypto Deposits</fullName>
            </value>
            <value>
                <fullName>Crypto Payouts</fullName>
            </value>
            <value>
                <fullName>Deposits</fullName>
            </value>
            <value>
                <fullName>Domestic Wires</fullName>
            </value>
            <value>
                <fullName>Gas Station</fullName>
            </value>
            <value>
                <fullName>Indirect Liquidity Partners</fullName>
            </value>
            <value>
                <fullName>Instant Settlement</fullName>
            </value>
            <value>
                <fullName>Institutional Trading Partnership</fullName>
            </value>
            <value>
                <fullName>IntlWires</fullName>
                <label>Int’l Wires</label>
            </value>
            <value>
                <fullName>Loans</fullName>
            </value>
            <value>
                <fullName>Payments API</fullName>
            </value>
            <value>
                <fullName>Payouts API</fullName>
            </value>
            <value>
                <fullName>Performance Incentives</fullName>
            </value>
            <value>
                <fullName>Product Integrations</fullName>
            </value>
            <value>
                <fullName>Programmable Wallets</fullName>
            </value>
            <value>
                <fullName>PSP Crypto Settlement</fullName>
            </value>
            <value>
                <fullName>Read Only API</fullName>
            </value>
            <value>
                <fullName>Referrals</fullName>
            </value>
            <value>
                <fullName>Smart Contract Platform</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountOppTeamCreationTest.cls
@isTest
public class AccountOppTeamCreationTest {

    @TestSetup
    static void setup(){
        CircleTestDataFactory.insertCustomSettings();
    }
    
    @isTest static void testOppTeamCreation(){
        Account acc = CircleTestDataFactory.insertAccount();
        acc.Platform_Owner__c = UserInfo.getUserId();
        acc.Pre_Sales_Solution_Engineer__c = UserInfo.getUserId();
        acc.Treasury_Owner__c = UserInfo.getUserId();
        acc.Post_Sales_Solution_Engineer__c = UserInfo.getUserId();
        update acc;

        Opportunity o = new Opportunity(AccountId = acc.Id, Name = 'TestOpp', CloseDate = date.today(),
                                        StageName = 'Discover', Product_s__c = 'Circle Mint');
        insert o;
        
        acc.Update_Opp_Team_Members__c = true;
        update acc;
    }
}