force-app/main/default/objects/Account_Maintenance_Request__c/Account_Maintenance_Request__c.object-meta.xml
<CustomObject>
    <label>Account Maintenance Request</label>
    <nameField>
        <displayFormat>AMR-{00000}</displayFormat>
        <label>Account Maintenance Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Maintenance Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Maintenance_Request__c/fields/New_Owner__c.field-meta.xml
<CustomField>
    <fullName>New_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Maintenance_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Maintenance_Request__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Maintenance_Request__c/fields/Request_Types_Selected__c.field-meta.xml
<CustomField>
    <fullName>Request_Types_Selected__c</fullName>
    <formula>IF(
   AND(
      INCLUDES(Request_Type__c, &apos;Target Account Update&apos;),
      INCLUDES(Request_Type__c, &apos;Ownership Update&apos;)
   ), 
   &apos;Ownership Update;Target Account Update&apos;,
   IF(
      INCLUDES(Request_Type__c,&apos;Target Account Update&apos;), 
      &apos;Target Account Update&apos;,
      IF(
         INCLUDES(Request_Type__c,&apos;Ownership Update&apos;)
         ,&apos;Ownership Update&apos;,
         IF(
            INCLUDES(Request_Type__c,&apos;Data Enrichment&apos;)
            ,&apos;Data Enrichment&apos;,
            IF(
               INCLUDES(Request_Type__c,&apos;Source New Contacts&apos;)
               ,&apos;Source New Contacts&apos;,null
            )
         )
         
      )
   )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Request Types Selected</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountMaintenanceRequests.cls
public class AccountMaintenanceRequests {

    public static void validateApproval(Map<Id, Account_Maintenance_Request__C> newRequests, Map<Id, Account_Maintenance_Request__c> oldRequests){
        for(Id id : newRequests.keyset()){
            if(newRequests.get(id).Request_Status__c == 'Approved' && newRequests.get(id).Request_Status__c != oldRequests.get(id).Request_Status__c && newRequests.get(id).Request_Types_Selected__c.contains('Ownership Update') && newRequests.get(id).New_Owner__c == null){
                newRequests.get(id).addError('Error: You must select a new owner before approving an account maintenance request if the request includes an ownership update');
            }
        }
    }
}