force-app/main/default/objects/Account_Maintenance_Request__c/Account_Maintenance_Request__c.object-meta.xml
<CustomObject>
    <label>Account Maintenance Request</label>
    <nameField>
        <displayFormat>AMR-{00000}</displayFormat>
        <label>Account Maintenance Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Maintenance Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Maintenance_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Maintenance_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Maintenance_Request__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Maintenance_Request__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ownership Update</fullName>
            </value>
            <value>
                <fullName>Target Account Update</fullName>
            </value>
            <value>
                <fullName>Data Enrichment</fullName>
            </value>
            <value>
                <fullName>Source New Contacts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountMaintenanceRequestsTest.cls
@isTest 
public class AccountMaintenanceRequestsTest {

    @TestSetup
    static void setup(){
        CircleTestDataFactory.insertCustomSettings();
    }

    @isTest 
    static void testValidation(){
        Account act = CircleTestDataFactory.insertAccount();
        Account_Maintenance_Request__c amr = new Account_Maintenance_Request__C(Account__c = act.id, Request_type__c = 'Ownership Update');
        insert amr;

        String error = '';
        Test.startTest();
            amr.Request_Status__c = 'Approved';
            try{
                update amr;
            }
            catch(Exception e){
                error = e.getMessage();
            }
        Test.stopTest();

        System.assert(error.contains('Error: You must select a new owner before approving an account maintenance request if the request includes an ownership update'));
    }
}