force-app/main/default/objects/Lead/fields/Auto_Convert__c.field-meta.xml
<CustomField>
    <fullName>Auto_Convert__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked this will trigger automation to auto convert a lead</description>
    <label>Auto Convert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Email_Domain__c.field-meta.xml
<CustomField>
    <fullName>Email_Domain__c</fullName>
    <label>Email Domain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Is_this_a_work_email__c.field-meta.xml
<CustomField>
    <fullName>Is_this_a_work_email__c</fullName>
    <label>Is This a Work Email?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Legal_Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity_Name__c</fullName>
    <label>Legal Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/SDR_Owner__c.field-meta.xml
<CustomField>
    <fullName>SDR_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SDR Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads11</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchLeadConvert.cls
global class BatchLeadConvert implements Database.Batchable<sObject> {
    private Set<Id> m_leadIdSet = new Set<Id>();
    
    global BatchLeadConvert(Set<Id> a_leadIdSet){
        m_leadIdSet = a_leadIdSet;
    }
    global Database.QueryLocator start(Database.BatchableContext a_bc) {
        //String query = 'SELECT Id, Name FROM Lead';
        //return Database.getQueryLocator(query);
        return Database.getQueryLocator([SELECT id,firstname,lastname,email,OwnerId,
                                         Legal_Entity_Name__c,Email_Domain__c,
                                         IsConverted, Auto_Convert__c, Company, Is_this_a_work_email__c,
                                         sdr_owner__c
                                         from Lead where id in:m_leadIdSet
                                         and IsConverted = false]);
    }
    
    global void execute(Database.BatchableContext a_bc, List<Lead> a_leadList) {
        Map<Id, Lead> leadMap = new Map<Id, Lead>();
        for(Lead ld : a_leadList){
            leadMap.put(ld.Id, ld);
        }
        //try {
        AutoConvertLead.checkForLeadsToConvert(leadMap);
        //} catch(Exception e) {
            //System.debug(e);
        //}
    }
     
    global void finish(Database.BatchableContext a_bc) {
        
    }
}