force-app/main/default/objects/Opportunity/fields/Accounting_Impact__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Impact__c</fullName>
    <inlineHelpText>AP: Circle will incur an expense and be billed 
AR: Circle has the potential to receive payment

Reach out to Robby Burns with questions!</inlineHelpText>
    <label>Accounting Impact</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accounts Payable</fullName>
            </value>
            <value>
                <fullName>Accounts Receivable</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Challenges__c.field-meta.xml
<CustomField>
    <fullName>Challenges__c</fullName>
    <description>Are there any headwinds or potential roadblocks?</description>
    <inlineHelpText>Are there any headwinds or potential roadblocks?</inlineHelpText>
    <label>Challenges</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Compliance_Analyst__c.field-meta.xml
<CustomField>
    <fullName>Compliance_Analyst__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compliance Analyst</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Date_Approvals_Stage_Entered__c.field-meta.xml
<CustomField>
    <fullName>Date_Approvals_Stage_Entered__c</fullName>
    <label>Date Approvals Stage Entered</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Date_Closed_Lost_Stage_Entered__c.field-meta.xml
<CustomField>
    <fullName>Date_Closed_Lost_Stage_Entered__c</fullName>
    <label>Date Closed Lost Stage Entered</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Date_Closed_Won_Stage_Entered__c.field-meta.xml
<CustomField>
    <fullName>Date_Closed_Won_Stage_Entered__c</fullName>
    <label>Date Closed Won Stage Entered</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Date_Contract_Stage_Entered__c.field-meta.xml
<CustomField>
    <fullName>Date_Contract_Stage_Entered__c</fullName>
    <label>Date Contract Stage Entered</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Date_Discover_Stage_Entered__c.field-meta.xml
<CustomField>
    <fullName>Date_Discover_Stage_Entered__c</fullName>
    <label>Date Discover Stage Entered</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Date_Negotiate_Stage_Entered__c.field-meta.xml
<CustomField>
    <fullName>Date_Negotiate_Stage_Entered__c</fullName>
    <label>Date Negotiate Stage Entered</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Date_Solution_Stage_Entered__c.field-meta.xml
<CustomField>
    <fullName>Date_Solution_Stage_Entered__c</fullName>
    <label>Date Solution Stage Entered</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Decision_Makers__c.field-meta.xml
<CustomField>
    <fullName>Decision_Makers__c</fullName>
    <description>The primary decision makers for the account</description>
    <inlineHelpText>Who are the primary decision makers on this deal? Please list their names and roles.</inlineHelpText>
    <label>Decision Makers</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Monthly_Active_Users__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Active_Users__c</fullName>
    <description>Used for Performance and Activation Incentives</description>
    <label>Monthly Active Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Next_Steps__c.field-meta.xml
<CustomField>
    <fullName>Next_Steps__c</fullName>
    <inlineHelpText>Use this field to keep a running log of all next steps throughout the deal cycle.</inlineHelpText>
    <label>Next Steps History</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Number_Of_Attachments__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Attachments__c</fullName>
    <label>Number Of Attachments</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Currency__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Currency__c</fullName>
    <description>Used for accounting purposes to identify which currency the customer/partner prefers.</description>
    <inlineHelpText>Used for accounting purposes to identify which currency the customer/partner prefers.</inlineHelpText>
    <label>Opportunity Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>MXN</fullName>
            </value>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>ARS</fullName>
            </value>
            <value>
                <fullName>COP</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>NTD</fullName>
                <isActive>false</isActive>
                <label>NTD</label>
            </value>
            <value>
                <fullName>TWD</fullName>
                <isActive>false</isActive>
                <label>TWD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Pricing_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Approval_Status__c</fullName>
    <defaultValue>&apos;Not Started&apos;</defaultValue>
    <label>Pricing Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Required</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_s__c.field-meta.xml
<CustomField>
    <fullName>Product_s__c</fullName>
    <inlineHelpText>Select all applicable products that are related to this opportunity.</inlineHelpText>
    <label>Product(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>247Book</fullName>
                <label>24/7 Book</label>
            </value>
            <value>
                <fullName>Accounts API</fullName>
            </value>
            <value>
                <fullName>Activation Incentives</fullName>
            </value>
            <value>
                <fullName>Blockchain Partnerships</fullName>
            </value>
            <value>
                <fullName>Bridged USDC Standard</fullName>
            </value>
            <value>
                <fullName>CCTP</fullName>
            </value>
            <value>
                <fullName>Channel Sales</fullName>
            </value>
            <value>
                <fullName>Core API</fullName>
            </value>
            <value>
                <fullName>Crypto Deposits</fullName>
            </value>
            <value>
                <fullName>Crypto Payouts</fullName>
            </value>
            <value>
                <fullName>Deposits</fullName>
            </value>
            <value>
                <fullName>Domestic Wires</fullName>
            </value>
            <value>
                <fullName>Gas Station</fullName>
            </value>
            <value>
                <fullName>Indirect Liquidity Partners</fullName>
            </value>
            <value>
                <fullName>Instant Settlement</fullName>
            </value>
            <value>
                <fullName>Institutional Trading Partnership</fullName>
            </value>
            <value>
                <fullName>IntlWires</fullName>
                <label>Int’l Wires</label>
            </value>
            <value>
                <fullName>Loans</fullName>
            </value>
            <value>
                <fullName>Payments API</fullName>
            </value>
            <value>
                <fullName>Payouts API</fullName>
            </value>
            <value>
                <fullName>Performance Incentives</fullName>
            </value>
            <value>
                <fullName>Product Integrations</fullName>
            </value>
            <value>
                <fullName>Programmable Wallets</fullName>
            </value>
            <value>
                <fullName>PSP Crypto Settlement</fullName>
            </value>
            <value>
                <fullName>Read Only API</fullName>
            </value>
            <value>
                <fullName>Referrals</fullName>
            </value>
            <value>
                <fullName>Smart Contract Platform</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_Minting_Volume__c.field-meta.xml
<CustomField>
    <fullName>Projected_Minting_Volume__c</fullName>
    <description>Monthly projected minting volume</description>
    <inlineHelpText>How much do we expect this customer to mint every month?</inlineHelpText>
    <label>Monthly Projected Minting Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_Wallet_Count__c.field-meta.xml
<CustomField>
    <fullName>Projected_Wallet_Count__c</fullName>
    <description>Projected monthly wallet count.</description>
    <inlineHelpText>Projected monthly wallet count.</inlineHelpText>
    <label>Projected Wallet Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referral_Partner__c.field-meta.xml
<CustomField>
    <fullName>Referral_Partner__c</fullName>
    <label>Referral Partner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Referral_Partner</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <businessProcess>Product</businessProcess>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/RecordTypeIds__c/RecordTypeIds__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>RecordTypeIds</label>
</CustomObject>

force-app/main/default/objects/RecordTypeIds__c/fields/BusinessDevelopmentOpp__c.field-meta.xml
<CustomField>
    <fullName>BusinessDevelopmentOpp__c</fullName>
    <label>BusinessDevelopmentOpp</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunitiesTest.cls
@isTest
public class OpportunitiesTest {

    @TestSetup
    static void setup(){
        CircleTestDataFactory.insertCustomSettings();
    }

    @isTest static void testRevertStageIfProductsChange(){
        Account act = CircleTestDataFactory.insertAccount();
        Opportunity opp = new Opportunity(AccountId = act.id, name = 'Test',StageName = 'Discover',CloseDate = Date.today(), Type = 'New Business',Product_s__c = 'Circle Mint');
        opp.RecordTypeId = RecordTypeIds__c.getInstance().BusinessDevelopmentOpp__c;
        insert opp;
        opp.StageName = 'Solution';
        opp.Compliance_Analyst__c = UserInfo.getUserId();
        update opp;
        
        Test.startTest();
            opp.Product_s__c = 'Circle Mint;Programmable Wallets';
            update opp;
            opp = [SELECT ID, StageName, Compliance_Analyst__c FROM Opportunity WHERE ID = :opp.id];
            System.assertEquals('Discover',opp.StageName);
            System.assertEquals(null, opp.Compliance_Analyst__c);
            opp.StageName = 'Solution';
            update opp;
            opp.Product_s__c = 'Circle Mint';
            update opp;
        Test.stopTest();
        opp = [SELECT ID, StageName FROM Opportunity WHERE ID = :opp.id];
        System.assertEquals('Solution',opp.StageName);
    }

    @isTest static void testOppTeamCSMValidationFailed(){
        Account act = CircleTestDataFactory.insertAccount();
        Opportunity opp = new Opportunity(Accountid = act.id, name = 'test', StageName = 'Discover', CloseDate = Date.today(), Type = 'New Business', Product_s__c = 'Circle Mint');
        opp.RecordTypeId = RecordTypeIds__c.getInstance().BusinessDevelopmentOpp__c;
        insert opp;
        String error = '';
        Test.startTest();
            opp.StageName = 'Closed Won';
            try{
                update opp;
            }
            catch(Exception e){
                error = e.getMessage();
            }
        Test.stopTest();
        System.assert(error.contains('You must add a CSM to the opportunity team beforce closing this opportunity'));
    }

    @isTest static void testOppTeamCSMValidationSuccess(){
        Account act = CircleTestDataFactory.insertAccount();
        Opportunity opp = new Opportunity(Accountid = act.id, name = 'test', StageName = 'Discover', CloseDate = Date.today(), Type = 'New Business', Product_s__c = 'Circle Mint');
        opp.RecordTypeId = RecordTypeIds__c.getInstance().BusinessDevelopmentOpp__c;
        insert opp;
        OpportunityTeamMember oppTeamMember = new OpportunityTeamMember(OpportunityId = opp.id, TeamMemberRole = 'Customer Success Manager', UserId = UserInfo.getUserId());
        insert oppTeamMember;
        String error = '';
        Test.startTest();
            opp.StageName = 'Closed Won';
            try{
                update opp;
            }
            catch(Exception e){
                error = e.getMessage();
            }
        Test.stopTest();
        System.assertEquals('', error);
    }

    @isTest static void testValidateProducts(){
        User sdr = CircleTestDataFactory.insertUser();
        Account act = CircleTestDataFactory.insertAccount();
        Opportunity opp = new Opportunity(OwnerId = sdr.id, Accountid = act.id, name = 'test', StageName = 'Discover', CloseDate = Date.today(), Type = 'New Business', Product_s__c = 'Invalid', Challenges__c = 'Challenges',Decision_Makers__C = 'Decision Makers', Projected_Wallet_Count__c = 123, Monthly_Active_Users__C = 123, Projected_Minting_Volume__c = 123);
        opp.RecordTypeId = RecordTypeIds__c.getInstance().BusinessDevelopmentOpp__c;
        insert opp;

        System.runAs(sdr){
            String error = '';
            Test.startTest();
                opp.StageName = 'Solution';
                try{
                    update opp;
                }
                catch(Exception e){
                    error = e.getMessage();
                }
            Test.stopTest();
            System.assert(error.contains('Error: You have a product selected which is not in the product book, please correct the selected product(s) to a valid option'));
        }
    }

    @isTest static void testAccountApplicability(){
        User u = CircleTestDataFactory.insertPricingUser();
        Account act = CircleTestDataFactory.insertAccount();
        Opportunity opp = new Opportunity(OwnerId = u.id, Accountid = act.id, name = 'test', StageName = 'Discover', CloseDate = Date.today(), Type = 'New Business', Product_s__c = 'Performance Incentives', Challenges__c = 'Challenges',Decision_Makers__C = 'Decision Makers', Projected_Wallet_Count__c = 123, Monthly_Active_Users__C = 123, Projected_Minting_Volume__c = 123);
        opp.RecordTypeId = RecordTypeIds__c.getInstance().BusinessDevelopmentOpp__c;
        insert opp;

        System.runAs(u){
            String error = '';
            Test.startTest();
                opp.Accounting_Impact__c = null;
                opp.Pricing_approval_status__c = 'Approved';
                try{
                    update opp;
                }
                catch(Exception e){
                    error = e.getMessage();
                }
            Test.stopTest();
            System.assert(error.contains('The pricing team must populate the Accounting Impact field before approving'));
            System.assert(error.contains('The Pricing Matrix, Stablecoin Custody, Weighted Margin % & Bps On Volume must be populated for all Performance Incentives'));

        }
    }

    @isTest static void testNextStepToHistory(){
        Account act = CircleTestDataFactory.insertAccount();
        Opportunity opp = new Opportunity(AccountId = act.id, name = 'Test',StageName = 'Discover',CloseDate = Date.today(), Type = 'New Business',Product_s__c = 'Circle Mint', NextStep = 'abc');
        opp.RecordTypeId = RecordTypeIds__c.getInstance().BusinessDevelopmentOpp__c;
        insert opp;

        opp = [SELECT ID, Next_steps__C from Opportunity WHERE ID = :opp.id];
        System.assertEquals('('+String.valueOf(Date.today())+') : abc', opp.Next_Steps__c);
        
        opp.NextStep = 'test 123';
        update opp;

        opp = [SELECT ID, Next_steps__C from Opportunity WHERE ID = :opp.id];
        System.assertEquals('('+String.valueOf(Date.today())+') : test 123<br><br>('+String.valueOf(Date.today())+') : abc', opp.Next_Steps__c);

    }

    @isTest static void testAccountingImpact(){
        Account act = CircleTestDataFactory.insertAccount();
        Opportunity opp = new Opportunity(AccountId = act.id, name = 'Test',StageName = 'Discover',CloseDate = Date.today(), Type = 'New Business',Product_s__c = 'Circle Mint', NextStep = 'abc');
        opp.RecordTypeId = RecordTypeIds__c.getInstance().BusinessDevelopmentOpp__c;
        insert opp; 

        opp = [Select Accounting_Impact__c FROM Opportunity WHERE ID = :opp.id];
        System.assertEquals('Not Applicable', opp.Accounting_Impact__c);

        Test.startTest();
            opp.Product_s__c = 'Circle Mint;Institutional Trading Partnership';
            update opp;
            opp = [Select Accounting_Impact__c FROM Opportunity WHERE ID = :opp.id];
            System.assertEquals(null, opp.Accounting_Impact__c);
            opp.Product_s__c = 'Circle Mint;Core API';
            update opp;
            opp = [Select Accounting_Impact__c FROM Opportunity WHERE ID = :opp.id];
            System.assertEquals('Accounts Receivable', opp.Accounting_Impact__c);
            opp.Product_s__c = 'Circle Mint;Activation Incentives';
            update opp;
            opp = [Select Accounting_Impact__c FROM Opportunity WHERE ID = :opp.id];
            System.assertEquals('Accounts Payable', opp.Accounting_Impact__c);
            opp.Product_s__c = 'Circle Mint;Core API;Activation Incentives';
            update opp;
            opp = [Select Accounting_Impact__c FROM Opportunity WHERE ID = :opp.id];
            System.assertEquals('Both', opp.Accounting_Impact__c);
            opp.Product_s__c = 'Circle Mint;Core API;Activation Incentives;Institutional Trading Partnership';
            update opp;
            opp = [Select Accounting_Impact__c FROM Opportunity WHERE ID = :opp.id];
            System.assertEquals(null, opp.Accounting_Impact__c);
        Test.stopTest();
    }

    @isTest static void testDateXStageEntered(){
        Account act = CircleTestDataFactory.insertAccount();
        Opportunity opp = CircleTestDataFactory.insertOpportunity(act.Id, 'TEST', Date.today(), 'Circle Mint');
        OpportunityTeamMember oppTeamMember = new OpportunityTeamMember(OpportunityId = opp.id, TeamMemberRole = 'Customer Success Manager', UserId = UserInfo.getUserId());
        insert oppTeamMember;

        Test.startTest();
            opp = [SELECT ID, Date_Discover_Stage_Entered__c FROM Opportunity WHERE ID = :opp.id];
            System.assertNotEquals(null, opp.Date_Discover_Stage_Entered__c);
            opp.StageName = 'Solution';
            update opp;
            opp = [SELECT ID, Date_Solution_Stage_Entered__c FROM Opportunity WHERE ID = :opp.id];
            System.assertNotEquals(null, opp.Date_Solution_Stage_Entered__c);
            opp.StageName = 'Approvals';
            update opp;
            opp = [SELECT ID, Date_Approvals_Stage_Entered__c FROM Opportunity WHERE ID = :opp.id];
            System.assertNotEquals(null, opp.Date_Approvals_Stage_Entered__c);
            opp.StageName = 'Negotiate';
            update opp;
            opp = [SELECT ID, Date_Negotiate_Stage_Entered__c FROM Opportunity WHERE ID = :opp.id];
            System.assertNotEquals(null, opp.Date_Negotiate_Stage_Entered__c);
            opp.StageName = 'Contract';
            update opp;
            opp = [SELECT ID, Date_Contract_Stage_Entered__c FROM Opportunity WHERE ID = :opp.id];
            System.assertNotEquals(null, opp.Date_Contract_Stage_Entered__c);
            opp.StageName = 'Closed Won';
            opp.Referral_Partner__c = 'Solana';
            opp.Accounting_Impact__c = 'Not Applicable';
            opp.Opportunity_Currency__c = 'USD';
            update opp;
            opp = [SELECT ID, Date_Closed_Won_Stage_Entered__c FROM Opportunity WHERE ID = :opp.id];
            System.assertNotEquals(null, opp.Date_Closed_Won_Stage_Entered__c);
            opp.StageName = 'Closed Lost';
            update opp;
            opp = [SELECT ID, Date_Closed_Won_Stage_Entered__c,Date_Closed_Lost_Stage_Entered__c FROM Opportunity WHERE ID = :opp.id];
            System.assertEquals(null, opp.Date_Closed_Won_Stage_Entered__c);
            System.assertNotEquals(null, opp.Date_Closed_Lost_Stage_Entered__c);
            opp.StageName = 'Discover';
            update opp;
            opp = [SELECT ID, Date_Discover_Stage_Entered__c, Date_Solution_Stage_Entered__c,Date_Approvals_Stage_Entered__c,Date_Negotiate_Stage_Entered__c, Date_Contract_Stage_Entered__c,Date_Closed_Lost_Stage_Entered__c FROM Opportunity WHERE ID = :opp.id];
            System.assertNotEquals(null, opp.Date_Discover_Stage_Entered__c);
            System.assertEquals(null, opp.Date_Solution_Stage_Entered__c);
            System.assertEquals(null, opp.Date_Approvals_Stage_Entered__c);
            System.assertEquals(null, opp.Date_Negotiate_Stage_Entered__c);
            System.assertEquals(null, opp.Date_Contract_Stage_Entered__c);
            System.assertEquals(null, opp.Date_Closed_Lost_Stage_Entered__c);
            opp.StageName = 'Closed Won';
            update opp;
            opp = [SELECT ID, Date_Discover_Stage_Entered__c, Date_Solution_Stage_Entered__c,Date_Approvals_Stage_Entered__c,Date_Negotiate_Stage_Entered__c, Date_Contract_Stage_Entered__c,Date_Closed_Lost_Stage_Entered__c,Date_Closed_Won_Stage_Entered__c FROM Opportunity WHERE ID = :opp.id];
            System.assertNotEquals(null, opp.Date_Discover_Stage_Entered__c);
            System.assertNotEquals(null, opp.Date_Solution_Stage_Entered__c);
            System.assertNotEquals(null, opp.Date_Approvals_Stage_Entered__c);
            System.assertNotEquals(null, opp.Date_Negotiate_Stage_Entered__c);
            System.assertNotEquals(null, opp.Date_Contract_Stage_Entered__c);
            System.assertNotEquals(null, opp.Date_Closed_Won_Stage_Entered__c);
            opp.StageName = 'Solution';
            update opp;
            opp = [SELECT ID, Date_Discover_Stage_Entered__c, Date_Solution_Stage_Entered__c,Date_Approvals_Stage_Entered__c,Date_Negotiate_Stage_Entered__c, Date_Contract_Stage_Entered__c,Date_Closed_Lost_Stage_Entered__c,Date_Closed_Won_Stage_Entered__c FROM Opportunity WHERE ID = :opp.id];
            System.assertNotEquals(null, opp.Date_Discover_Stage_Entered__c);
            System.assertNotEquals(null, opp.Date_Solution_Stage_Entered__c);
            System.assertEquals(null, opp.Date_Approvals_Stage_Entered__c);
            System.assertEquals(null, opp.Date_Negotiate_Stage_Entered__c);
            System.assertEquals(null, opp.Date_Contract_Stage_Entered__c);
            System.assertEquals(null, opp.Date_Closed_Won_Stage_Entered__c);
            opp.StageName = 'Closed Won';
            update opp;
            opp.StageName = 'Approvals';
            update opp;
            opp = [SELECT ID, Date_Discover_Stage_Entered__c, Date_Solution_Stage_Entered__c,Date_Approvals_Stage_Entered__c,Date_Negotiate_Stage_Entered__c, Date_Contract_Stage_Entered__c,Date_Closed_Lost_Stage_Entered__c,Date_Closed_Won_Stage_Entered__c FROM Opportunity WHERE ID = :opp.id];
            System.assertNotEquals(null, opp.Date_Discover_Stage_Entered__c);
            System.assertNotEquals(null, opp.Date_Solution_Stage_Entered__c);
            System.assertNotEquals(null, opp.Date_Approvals_Stage_Entered__c);
            System.assertEquals(null, opp.Date_Negotiate_Stage_Entered__c);
            System.assertEquals(null, opp.Date_Contract_Stage_Entered__c);
            System.assertEquals(null, opp.Date_Closed_Won_Stage_Entered__c);
            opp.StageName = 'Closed Won';
            update opp;
            opp.StageName = 'Negotiate';
            update opp;
            opp = [SELECT ID, Date_Discover_Stage_Entered__c, Date_Solution_Stage_Entered__c,Date_Approvals_Stage_Entered__c,Date_Negotiate_Stage_Entered__c, Date_Contract_Stage_Entered__c,Date_Closed_Lost_Stage_Entered__c,Date_Closed_Won_Stage_Entered__c FROM Opportunity WHERE ID = :opp.id];
            System.assertNotEquals(null, opp.Date_Discover_Stage_Entered__c);
            System.assertNotEquals(null, opp.Date_Solution_Stage_Entered__c);
            System.assertNotEquals(null, opp.Date_Approvals_Stage_Entered__c);
            System.assertNotEquals(null, opp.Date_Negotiate_Stage_Entered__c);
            System.assertEquals(null, opp.Date_Contract_Stage_Entered__c);
            System.assertEquals(null, opp.Date_Closed_Won_Stage_Entered__c);
            opp.StageName = 'Closed Won';
            update opp;
            opp.StageName = 'Contract';
            update opp;
            opp = [SELECT ID, Date_Discover_Stage_Entered__c, Date_Solution_Stage_Entered__c,Date_Approvals_Stage_Entered__c,Date_Negotiate_Stage_Entered__c, Date_Contract_Stage_Entered__c,Date_Closed_Lost_Stage_Entered__c,Date_Closed_Won_Stage_Entered__c FROM Opportunity WHERE ID = :opp.id];
            System.assertNotEquals(null, opp.Date_Discover_Stage_Entered__c);
            System.assertNotEquals(null, opp.Date_Solution_Stage_Entered__c);
            System.assertNotEquals(null, opp.Date_Approvals_Stage_Entered__c);
            System.assertNotEquals(null, opp.Date_Negotiate_Stage_Entered__c);
            System.assertNotEquals(null, opp.Date_Contract_Stage_Entered__c);
            System.assertEquals(null, opp.Date_Closed_Won_Stage_Entered__c);
        Test.stopTest();       
    }

    @isTest static void testAddFileOpportunityCount(){
        Account act = CircleTestDataFactory.insertAccount();
        Contact cont = CircleTestDataFactory.insertContact(act.id, 'first', 'last', null);
        Opportunity opp = CircleTestDataFactory.insertOpportunity(act.Id, 'Name', Date.today(), 'Circle Mint');

        ContentVersion contentVersion = new ContentVersion(Title = 'a picture',PathOnClient   = 'Pic.jpg', VersionData = Blob.valueOf('Test Content'),IsMajorVersion = true);
        insert contentVersion;
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];

        ContentDocumentLink objCntDocLink = new ContentDocumentLink();
        objCntDocLink.LinkedEntityId = opp.id; 
        objCntDocLink.ContentDocumentId = documents[0].Id; 
        objCntDocLink.shareType = 'V';        
        
        Test.startTest();
            insert objCntDocLink;
        Test.stopTest();

        opp = [SELECT Number_Of_Attachments__c FROM Opportunity WHERE ID = :opp.id];
        System.assertEquals(1, opp.Number_Of_Attachments__c);
    }

    @isTest static void testApprovalRecall(){
        Account act = CircleTestDataFactory.insertAccount();
        Contact cont = CircleTestDataFactory.insertContact(act.id, 'first', 'last', null);
        Opportunity opp = CircleTestDataFactory.insertOpportunity(act.Id, 'Name', Date.today(), 'Accounts API');

        Approval.ProcessSubmitRequest testapproval = new Approval.ProcessSubmitRequest();
        testapproval.setComments('Submitting request for approval');
        testapproval.setObjectId(opp.Id);
        Approval.ProcessResult result1 = Approval.process(testapproval);
        
        List<ProcessInstanceWorkitem> piwis = [SELECT Id, ProcessInstanceId, ProcessInstance.TargetObjectId FROM ProcessInstanceWorkitem WHERE ProcessInstance.TargetObjectId = :opp.id];
        System.assertEquals(1, piwis.size());
        
        Test.startTest();
            opp.StageName = 'Closed Lost';
            update opp;
        Test.stopTest();

        piwis = [SELECT Id, ProcessInstanceId, ProcessInstance.TargetObjectId FROM ProcessInstanceWorkitem WHERE ProcessInstance.TargetObjectId = :opp.id];
        System.assertEquals(0, piwis.size());
    }

}