force-app/main/default/objects/Opportunity/fields/Accounting_Impact__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Impact__c</fullName>
    <inlineHelpText>AP: Circle will incur an expense and be billed 
AR: Circle has the potential to receive payment

Reach out to Robby Burns with questions!</inlineHelpText>
    <label>Accounting Impact</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accounts Payable</fullName>
            </value>
            <value>
                <fullName>Accounts Receivable</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_s__c.field-meta.xml
<CustomField>
    <fullName>Product_s__c</fullName>
    <inlineHelpText>Select all applicable products that are related to this opportunity.</inlineHelpText>
    <label>Product(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>247Book</fullName>
                <label>24/7 Book</label>
            </value>
            <value>
                <fullName>Accounts API</fullName>
            </value>
            <value>
                <fullName>Activation Incentives</fullName>
            </value>
            <value>
                <fullName>Blockchain Partnerships</fullName>
            </value>
            <value>
                <fullName>Bridged USDC Standard</fullName>
            </value>
            <value>
                <fullName>CCTP</fullName>
            </value>
            <value>
                <fullName>Channel Sales</fullName>
            </value>
            <value>
                <fullName>Core API</fullName>
            </value>
            <value>
                <fullName>Crypto Deposits</fullName>
            </value>
            <value>
                <fullName>Crypto Payouts</fullName>
            </value>
            <value>
                <fullName>Deposits</fullName>
            </value>
            <value>
                <fullName>Domestic Wires</fullName>
            </value>
            <value>
                <fullName>Gas Station</fullName>
            </value>
            <value>
                <fullName>Indirect Liquidity Partners</fullName>
            </value>
            <value>
                <fullName>Instant Settlement</fullName>
            </value>
            <value>
                <fullName>Institutional Trading Partnership</fullName>
            </value>
            <value>
                <fullName>IntlWires</fullName>
                <label>Int’l Wires</label>
            </value>
            <value>
                <fullName>Loans</fullName>
            </value>
            <value>
                <fullName>Payments API</fullName>
            </value>
            <value>
                <fullName>Payouts API</fullName>
            </value>
            <value>
                <fullName>Performance Incentives</fullName>
            </value>
            <value>
                <fullName>Product Integrations</fullName>
            </value>
            <value>
                <fullName>Programmable Wallets</fullName>
            </value>
            <value>
                <fullName>PSP Crypto Settlement</fullName>
            </value>
            <value>
                <fullName>Read Only API</fullName>
            </value>
            <value>
                <fullName>Referrals</fullName>
            </value>
            <value>
                <fullName>Smart Contract Platform</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SetAccountingImpactBatchTest.cls
@isTest 
public class SetAccountingImpactBatchTest {

    @TestSetup
    static void setup(){
        CircleTestDataFactory.insertCustomSettings();
    }

    @isTest static void testAccountingImpact(){
        Account act = CircleTestDataFactory.insertAccount();
        Opportunity opp = new Opportunity(AccountId = act.id, name = 'Test',StageName = 'Discover',CloseDate = Date.today(), Type = 'New Business',Product_s__c = 'Circle Mint', NextStep = 'abc');
        insert opp; 

        opp = [Select Accounting_Impact__c FROM Opportunity WHERE ID = :opp.id];
        System.assertEquals('Not Applicable', opp.Accounting_Impact__c);

        Test.startTest();
            opp.Product_s__c = 'Circle Mint;Institutional Trading Partnership';
            update opp;
            opp = [Select Accounting_Impact__c FROM Opportunity WHERE ID = :opp.id];
            System.assertEquals(null, opp.Accounting_Impact__c);
            opp.Product_s__c = 'Circle Mint;Core API';
            update opp;
            opp = [Select Accounting_Impact__c FROM Opportunity WHERE ID = :opp.id];
            System.assertEquals('Accounts Receivable', opp.Accounting_Impact__c);
            opp.Product_s__c = 'Circle Mint;Activation Incentives';
            update opp;
            opp = [Select Accounting_Impact__c FROM Opportunity WHERE ID = :opp.id];
            System.assertEquals('Accounts Payable', opp.Accounting_Impact__c);
            opp.Product_s__c = 'Circle Mint;Core API;Activation Incentives';
            update opp;
            opp = [Select Accounting_Impact__c FROM Opportunity WHERE ID = :opp.id];
            System.assertEquals('Both', opp.Accounting_Impact__c);
            opp.Accounting_Impact__C = null;
            SetAccountingImpactBatch b = new SetAccountingImpactBatch();
            Database.executeBatch(b, 1);
        Test.stopTest();
        opp = [Select Accounting_Impact__c FROM Opportunity WHERE ID = :opp.id];
        System.assertEquals('Both', opp.Accounting_Impact__c);
    }
}