force-app/main/default/objects/Opportunity/fields/Accounting_Impact__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Impact__c</fullName>
    <inlineHelpText>AP: Circle will incur an expense and be billed 
AR: Circle has the potential to receive payment

Reach out to Robby Burns with questions!</inlineHelpText>
    <label>Accounting Impact</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accounts Payable</fullName>
            </value>
            <value>
                <fullName>Accounts Receivable</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_s__c.field-meta.xml
<CustomField>
    <fullName>Product_s__c</fullName>
    <inlineHelpText>Select all applicable products that are related to this opportunity.</inlineHelpText>
    <label>Product(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>247Book</fullName>
                <label>24/7 Book</label>
            </value>
            <value>
                <fullName>Accounts API</fullName>
            </value>
            <value>
                <fullName>Activation Incentives</fullName>
            </value>
            <value>
                <fullName>Blockchain Partnerships</fullName>
            </value>
            <value>
                <fullName>Bridged USDC Standard</fullName>
            </value>
            <value>
                <fullName>CCTP</fullName>
            </value>
            <value>
                <fullName>Channel Sales</fullName>
            </value>
            <value>
                <fullName>Core API</fullName>
            </value>
            <value>
                <fullName>Crypto Deposits</fullName>
            </value>
            <value>
                <fullName>Crypto Payouts</fullName>
            </value>
            <value>
                <fullName>Deposits</fullName>
            </value>
            <value>
                <fullName>Domestic Wires</fullName>
            </value>
            <value>
                <fullName>Gas Station</fullName>
            </value>
            <value>
                <fullName>Indirect Liquidity Partners</fullName>
            </value>
            <value>
                <fullName>Instant Settlement</fullName>
            </value>
            <value>
                <fullName>Institutional Trading Partnership</fullName>
            </value>
            <value>
                <fullName>IntlWires</fullName>
                <label>Int’l Wires</label>
            </value>
            <value>
                <fullName>Loans</fullName>
            </value>
            <value>
                <fullName>Payments API</fullName>
            </value>
            <value>
                <fullName>Payouts API</fullName>
            </value>
            <value>
                <fullName>Performance Incentives</fullName>
            </value>
            <value>
                <fullName>Product Integrations</fullName>
            </value>
            <value>
                <fullName>Programmable Wallets</fullName>
            </value>
            <value>
                <fullName>PSP Crypto Settlement</fullName>
            </value>
            <value>
                <fullName>Read Only API</fullName>
            </value>
            <value>
                <fullName>Referrals</fullName>
            </value>
            <value>
                <fullName>Smart Contract Platform</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SetAccountingImpactBatch.cls
public class SetAccountingImpactBatch implements Database.Batchable<sObject> {
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT ID, Product_s__c,Accounting_Impact__c FROM Opportunity WHERE Product_S__C != null and Accounting_Impact__C = null AND CloseDate = THIS_YEAR]);
    }
    
    public void execute(Database.BatchableContext bc, List<Opportunity> theOpps) {
        Opportunities.setAccountingImpact(theOpps);
        update theOpps;
    }
     
    public void finish(Database.BatchableContext bc) {
    }
}