force-app/main/default/objects/Opportunity/fields/Challenges__c.field-meta.xml
<CustomField>
    <fullName>Challenges__c</fullName>
    <description>Are there any headwinds or potential roadblocks?</description>
    <inlineHelpText>Are there any headwinds or potential roadblocks?</inlineHelpText>
    <label>Challenges</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <description>The date for which a contract will end.</description>
    <inlineHelpText>The date for which a contract will end.</inlineHelpText>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/Partnership_Objective__c.object-meta.xml
<CustomObject>
    <description>Track the key objectives of our customer relationships</description>
    <label>Partnership Objective</label>
    <nameField>
        <label>Partnership Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnership Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partnership_Objective__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field should auto-populate, but should be checked to ensure that the correct Salesforce Account is associated with the Partnership Objective</description>
    <inlineHelpText>This field should auto-populate, but should be checked to ensure that the correct Salesforce Account is associated with the Partnership Objective</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partnership Objectives</relationshipLabel>
    <relationshipName>Partnership_Objectives</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Challenges__c.field-meta.xml
<CustomField>
    <fullName>Challenges__c</fullName>
    <inlineHelpText>What is preventing us from maximizing growth of the relationship?</inlineHelpText>
    <label>Challenges</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <description>For contracted customers this field is derived from the opportunity. For those without a contract this defaults to 12 months from Objective Start Date, but can be edited if necessary.</description>
    <inlineHelpText>For contracted customers this field is derived from the opportunity. For those without a contract this defaults to 12 months from Objective Start Date, but can be edited if necessary.</inlineHelpText>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Learnings__c.field-meta.xml
<CustomField>
    <fullName>Learnings__c</fullName>
    <inlineHelpText>What have we learned from this relationship that we didn&apos;t know at deal signing?</inlineHelpText>
    <label>Learnings</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Objective_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Objective_Start_Date__c</fullName>
    <description>This field should indicate when active work on the objective will begin</description>
    <inlineHelpText>This field should indicate when active work on the objective will begin</inlineHelpText>
    <label>Objective Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Opportunities__c.field-meta.xml
<CustomField>
    <fullName>Opportunities__c</fullName>
    <inlineHelpText>What are the primary opportunities we have in front of us to grow the relationship?</inlineHelpText>
    <label>Opportunities</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is optional, but should be filled in most cases since the majority of objectives will stem from a specific Opportunity</description>
    <inlineHelpText>This field is optional, but should be filled in most cases since the majority of objectives will stem from a specific Opportunity</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Partnership Objectives</relationshipLabel>
    <relationshipName>Partnership_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Successes__c.field-meta.xml
<CustomField>
    <fullName>Successes__c</fullName>
    <inlineHelpText>What is going well with the relationship?</inlineHelpText>
    <label>Successes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This field is used by CSMs to separate Partner Objectives</description>
    <inlineHelpText>Keep the default for specific Partnership Objectives. Switch to Partner Metrics Tracking to track starting and current metrics.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Objective Tracking</fullName>
            </value>
            <value>
                <fullName>Partner Metrics Tracking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PartnershipObjectiveNotificationsBatch.cls
global class PartnershipObjectiveNotificationsBatch implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext bc) {
        Set<Date> dateList = new Set<Date>();
        Date today = Date.today();
        dateList.addAll(new List<Date>{today.addDays(-30),today.addDays(-60),today.addDays(-90),today.addDays(-180),today.addDays(-270),today.addDays(-360),today.addDays(-450),today.addDays(-540),today.addDays(-630),today.addDays(-720),today.addDays(-810),today.addDays(-900),today.addDays(-990),today.addDays(-1080),today.addDays(-1170),today.addDays(-1260),today.addDays(-1350),today.addDays(-1440)});
        String query = 'SELECT ID, Name,OwnerId, Account__r.Name,Opportunity__r.Name, Owner.Name,Successes__c,Challenges__c,Opportunities__c,Learnings__c FROM Partnership_Objective__c WHERE Objective_Start_Date__c IN :dateList AND (Contract_End_Date__c >= :today OR Contract_End_Date__c = null) AND Type__c = \'Partner Metrics Tracking\'';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Partnership_Objective__c> objectives) {
        List<Task> tasksToInsert = new List<Task>();
        for(Partnership_objective__c objective : objectives){
            Task t = new Task();
            t.WhatId = objective.id;
            t.Status = 'Open';
            t.ActivityDate = Date.today()+7;
            t.Description = 'Please review the Insights section of this Partnership Objective. Once you\'ve completed this task, insights will be shared with leadership.';
            t.Ownerid = objective.OwnerId;
            t.Priority = 'Normal';
            t.Subject = 'Update Partnership Objective Insights Reminder';
            t.TaskSubtype = 'Task';
            tasksToInsert.add(t);
        }
        if(tasksToInsert.size()>0){
            insert tasksToInsert;
        }
    }
     
    global void finish(Database.BatchableContext bc) {
    }
}