force-app/main/default/objects/Opportunity/fields/Compliance_Analyst__c.field-meta.xml
<CustomField>
    <fullName>Compliance_Analyst__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compliance Analyst</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Compliance_State__c.field-meta.xml
<CustomField>
    <fullName>Compliance_State__c</fullName>
    <label>Compliance State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer Risk Acceptance</fullName>
            </value>
            <value>
                <fullName>Form Not Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Periodic Review</fullName>
            </value>
            <value>
                <fullName>Pending AML Review</fullName>
                <label>Pending with AML</label>
            </value>
            <value>
                <fullName>Pending with BD Team</fullName>
            </value>
            <value>
                <fullName>Pending with Customer</fullName>
            </value>
            <value>
                <fullName>Pending with Legal</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Send_Compliance_SLA_Notification__c.field-meta.xml
<CustomField>
    <fullName>Send_Compliance_SLA_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Compliance SLA Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Violates_Compliance_SLA__c.field-meta.xml
<CustomField>
    <fullName>Violates_Compliance_SLA__c</fullName>
    <formula>IF(
   AND(
      !ISBLANK(Last_Compliance_State_Change_Date__c),
      ISPICKVAL(Compliance_State__c,&apos;Pending AML Review&apos;)
   ),
   IF(
      (NOW()-Last_Compliance_State_Change_Date__c)*24&gt;120, TRUE,
      IF(
         (NOW()-Last_Compliance_State_Change_Date__c)*24&gt;72,
          IF(
            WEEKDAY(DATEVALUE(NOW()-5/24))=1,
            IF(
               (NOW()-Last_Compliance_State_Change_Date__c)*24 - 24 - HOUR(TIMEVALUE(NOW()-5/24))-MINUTE(TIMEVALUE(NOW()))/60&gt;72,TRUE,FALSE
            ),
            IF(
               WEEKDAY(DATEVALUE(NOW()-5/24))=2,
               IF(
                  (NOW()-Last_Compliance_State_Change_Date__c)*24 -48 &gt; 72,TRUE,FALSE
               ),
               IF(
                  WEEKDAY(DATEVALUE(NOW()-5/24))=3,
                  IF(
                     (NOW()-Last_Compliance_State_Change_Date__c)*24 -48 &gt; 72,TRUE,FALSE
                  ),
                  IF(
                     WEEKDAY(DATEVALUE(NOW()-5/24))=4,
                     IF(
                        (NOW()-Last_Compliance_State_Change_Date__c)*24 - 48&gt;72,TRUE,FALSE
                     ),
                     IF(
                        WEEKDAY(DATEVALUE(NOW()-5/24))=7,
                        IF(
                           (NOW()-Last_Compliance_State_Change_Date__c)*24 - HOUR(TIMEVALUE(NOW()-5/24))-MINUTE(TIMEVALUE(NOW()))/60&gt;72,TRUE,FALSE
                        ),TRUE
                    )
                  )
               )
            )
         ),FALSE
      )
   ),FALSE
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Violates Compliance SLA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ComplianceSLANotificationsBatch.cls
public class ComplianceSLANotificationsBatch implements Database.Batchable<sObject> {
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        DateTime now = Datetime.now();
        DateTime hoursAgo72 = now.addHours(-72);
        return Database.getQueryLocator([SELECT ID, Compliance_Analyst__c, Compliance_Analyst__r.ManagerId FROM Opportunity WHERE StageName = 'Approvals' AND Violates_Compliance_SLA__c=true AND Compliance_State__c = 'Pending AML Review']);
    }
    
    public void execute(Database.BatchableContext bc, List<Opportunity> theOpportunities) {
        for(Opportunity opp : theOpportunities){
            opp.send_Compliance_SLA_Notification__c = true;
       }
       update theOpportunities;
    }
     
    public void finish(Database.BatchableContext bc) {
        
    }
}