force-app/main/default/objects/Opportunity/fields/Generate_Partnership_Construct__c.field-meta.xml
<CustomField>
    <fullName>Generate_Partnership_Construct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Generate Partnership Construct</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Hypothesis__c.field-meta.xml
<CustomField>
    <fullName>Hypothesis__c</fullName>
    <description>Why do we think the objective is possible? Through discovery discussions with the partner, how do both Circle and the partner think the partner can get us to the objective? Example: By introducing USDC as an in-app remittance option alongside significant existing fiat remittance volume, the partner and Circle believe we can drive a significant share-shift and activate significant MEWs and USDC on platform.</description>
    <inlineHelpText>Why do we think the objective is possible? Through discovery discussions with the partner, how do both Circle and the partner think the partner can get us to the objective? Example: By introducing USDC as an in-app remittance option alongside significant existing fiat remittance volume, the partner and Circle believe we can drive a significant share-shift and activate significant MEWs and USDC on platform.</inlineHelpText>
    <label>Hypothesis</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>The very specific strategies &amp; measurable tactics that make up an actual deal with the partner that will drive us toward the objective. Example: By listing USDC as the preferred remittance option in the app and running a blended email and in-app marketing feature on USDC education, we and the partner believe we can drive a significant uplift in both USDC on platform and MEWs.</description>
    <inlineHelpText>The very specific strategies &amp; measurable tactics that make up an actual deal with the partner that will drive us toward the objective. Example: By listing USDC as the preferred remittance option in the app and running a blended email and in-app marketing feature on USDC education, we and the partner believe we can drive a significant uplift in both USDC on platform and MEWs.</inlineHelpText>
    <label>Method</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <description>A simple framing of the strategic goals of working with that partner. Should include some strategic rationale and a clear articulation of the product-market fit for USDC and the use case. Example: Significantly grow USDC distribution in X region by partnering with the region’s top super-app with a reach of 50 million digital-native active users focusing on remittance.</description>
    <inlineHelpText>A simple framing of the strategic goals of working with that partner. Should include some strategic rationale and a clear articulation of the product-market fit for USDC and the use case. Example: Significantly grow USDC distribution in X region by partnering with the region’s top super-app with a reach of 50 million digital-native active users focusing on remittance.</inlineHelpText>
    <label>Objective</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Partnership_Construct_Document_ID__c.field-meta.xml
<CustomField>
    <fullName>Partnership_Construct_Document_ID__c</fullName>
    <label>Partnership Construct Document ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Partnership_Construct_Last_Updated_Date__c.field-meta.xml
<CustomField>
    <fullName>Partnership_Construct_Last_Updated_Date__c</fullName>
    <label>Partnership Construct Last Updated Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_MeWs_Growth__c.field-meta.xml
<CustomField>
    <fullName>Projected_MeWs_Growth__c</fullName>
    <label>Projected MeWs Growth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_Stablecoin_On_Platform_Growth__c.field-meta.xml
<CustomField>
    <fullName>Projected_Stablecoin_On_Platform_Growth__c</fullName>
    <label>Projected Stablecoin On Platform Growth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_Total_Stablecoin_Volume__c.field-meta.xml
<CustomField>
    <fullName>Projected_Total_Stablecoin_Volume__c</fullName>
    <label>Projected Total Stablecoin Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Risks_Dependencies__c.field-meta.xml
<CustomField>
    <fullName>Risks_Dependencies__c</fullName>
    <description>Potential obstacles and interdependencies that can significantly impact the success of the deal. These factors pose challenges that, if not carefully managed, may lead to the deal’s failure.</description>
    <inlineHelpText>Potential obstacles and interdependencies that can significantly impact the success of the deal. These factors pose challenges that, if not carefully managed, may lead to the deal’s failure.</inlineHelpText>
    <label>Risks &amp; Dependencies</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Success_Metrics__c.field-meta.xml
<CustomField>
    <fullName>Success_Metrics__c</fullName>
    <description>Populated by the BD to note how we will track success for this Partnership</description>
    <inlineHelpText>How we will track success for this partnership?</inlineHelpText>
    <label>Success Metrics</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MEWs</fullName>
            </value>
            <value>
                <fullName>USDC on Platform</fullName>
            </value>
            <value>
                <fullName>Transaction Volume</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Success_Metrics_Details__c.field-meta.xml
<CustomField>
    <fullName>Success_Metrics_Details__c</fullName>
    <description>Required if Success Metrics = Other</description>
    <inlineHelpText>Required if Success Metrics = Other</inlineHelpText>
    <label>Success Metrics Details</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Success_Metrics_Tracking__c.field-meta.xml
<CustomField>
    <fullName>Success_Metrics_Tracking__c</fullName>
    <description>What are the measurable indicators of success for this plan/deal? Every deal needs a clear articulation of shared metrics and success criteria. What will we be tracking to measure the success of this deal, how will we track the metrics, who is responsible for tracking the metrics, and how will it be communicated? Example: We will track USDC on platform toward the 30% lift goal and we will use partner-reported data to track toward the 20% lift target for MEWs. Both will be reported on a monthly basis over the 6 month term of the campaign.</description>
    <inlineHelpText>What will we be tracking to measure the success of this deal, how will we track the metrics, who is responsible for tracking the metrics, and how will it be communicated? Example: We will track USDC on platform toward the 30% lift goal and we will use partner-reported data to track toward the 20% lift target for MEWs. Both will be reported on a monthly basis over the 6 month term of the campaign.</inlineHelpText>
    <label>Success Metrics Tracking</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trigger_Switches__c/Trigger_Switches__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Trigger Switches</label>
</CustomObject>

force-app/main/default/objects/Trigger_Switches__c/fields/Generate_Partnership_Construct__c.field-meta.xml
<CustomField>
    <fullName>Generate_Partnership_Construct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Generate Partnership Construct</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/GoogleDocAPITest.cls
@IsTest
global class GoogleDocAPITest {

    @TestSetup
    static void setup(){
        CircleTestDataFactory.insertCustomSettings();
        Trigger_Switches__c setting = [SELECT ID,Generate_Partnership_Construct__c FROM Trigger_Switches__c LIMIT 1];
        setting.Generate_Partnership_Construct__c = true;
        update setting;
    }

    @isTest static void testCreate(){
        GoogleDocMockResponse googleResponse = new GoogleDocMockResponse();
        googleResponse.statusCode = 400;
        Test.setMock(HttpCalloutMock.class, googleResponse);
        Account act = CircleTestDataFactory.insertAccount();
        Opportunity opp = CircleTestDataFactory.makeOpportunity(act.id, 'Name', Date.today(), 'Institutional Trading Partnership');
        opp.Objective__c = '1234';
        opp.Hypothesis__c = '1234';
        opp.Risks_Dependencies__c = '1234';
        opp.Method__c = '1234';
        opp.Success_Metrics__c = 'MEWs;USDC on Platform;Transaction Volume;Other';
        opp.Success_Metrics_Details__c = '1234';
        opp.Success_Metrics_Tracking__c = '1234';
        opp.Projected_Mews_Growth__c = 1234;
        opp.Projected_Stablecoin_on_Platform_Growth__c = 1234;
        opp.Projected_Total_Stablecoin_Volume__c = 1234;
    
        
        googleResponse.statusCode = 200;
        Test.setMock(HttpCalloutMock.class, googleResponse);

        Test.startTest();
            insert opp;
        Test.stopTest();

        opp = [SELECT ID, Partnership_Construct_Document_ID__c FROM Opportunity WHERE ID = :opp.id];
        System.assertEquals('1234567', opp.Partnership_Construct_Document_ID__c);
    }

    @isTest static void testUpdate(){
        Test.setMock(HttpCalloutMock.class, new GoogleDocMockResponse());
        Account act = CircleTestDataFactory.insertAccount();
        Opportunity opp = CircleTestDataFactory.makeOpportunity(act.id, 'Name', Date.today(), 'Institutional Trading Partnership');
        opp.Objective__c = '1234';
        opp.Hypothesis__c = '1234';
        opp.Risks_Dependencies__c = '1234';
        opp.Method__c = '1234';
        opp.Success_Metrics__c = 'MEWs;USDC on Platform;Transaction Volume;Other';
        opp.Success_Metrics_Details__c = '1234';
        opp.Success_Metrics_Tracking__c = '1234';
        opp.Projected_Mews_Growth__c = 1234;
        opp.Projected_Stablecoin_on_Platform_Growth__c = 1234;
        opp.Projected_Total_Stablecoin_Volume__c = 1234;
        insert opp;
        
        Test.startTest();
            opp.Partnership_Construct_Document_ID__c = '1234567';
            opp.Partnership_Construct_Last_Updated_Date__c = null;
            opp.Objective__c = '12345';
            update opp;   
        Test.stopTest();

        opp = [SELECT ID, Partnership_Construct_Document_ID__c,Partnership_Construct_Last_Updated_Date__c FROM Opportunity WHERE ID = :opp.id];
        System.assertEquals('1234567', opp.Partnership_Construct_Document_ID__c);
        System.assertNotEquals(null, opp.Partnership_Construct_Last_Updated_Date__c);
    }

    @isTest
    private static void testCopy(){
        Test.setMock(HttpCalloutMock.class, new GoogleDocMockResponse());
        Account act = CircleTestDataFactory.insertAccount();
        Opportunity opp = CircleTestDataFactory.insertOpportunity(act.id, 'Name', Date.today(), 'Institutional Trading Partnership');
        
        test.startTest();
            HttpResponse res = GoogleDocAPI.copyPartnershipConstructFromTemplate('TEST');
        test.stopTest();

        System.assertEquals('application/json', res.getHeader('Content-Type'));
        System.assertEquals('{"documentId":"1234567", "id":"1234567"}', res.getBody());
        System.assertEquals(200, res.getStatusCode());
    }

    @isTest
    private static void testCopyFailure(){
        GoogleDocMockResponse googleResponse = new GoogleDocMockResponse();
        googleResponse.statusCode = 400;
        Test.setMock(HttpCalloutMock.class, googleResponse);
        Account act = CircleTestDataFactory.insertAccount();
        Opportunity opp = CircleTestDataFactory.insertOpportunity(act.id, 'Name', Date.today(), 'Institutional Trading Partnership');

        test.startTest();
            HttpResponse res = GoogleDocAPI.copyPartnershipConstructFromTemplate('TEST');
        test.stopTest();
        
        System.assertEquals(null, res);
    }

    @isTest
    private static void testShare(){
        GoogleDocMockResponse googleResponse = new GoogleDocMockResponse();
        googleResponse.statusCode = 200;
        Test.setMock(HttpCalloutMock.class, googleResponse);
        Account act = CircleTestDataFactory.insertAccount();
        Opportunity opp = CircleTestDataFactory.insertOpportunity(act.id, 'Name', Date.today(), 'Institutional Trading Partnership');

        test.startTest();
            HttpResponse res = GoogleDocAPI.shareNewDocument('1234567');
        test.stopTest();

        System.assertEquals('application/json', res.getHeader('Content-Type'));
        System.assertEquals('{"documentId":"1234567", "id":"1234567"}', res.getBody());
        System.assertEquals(200, res.getStatusCode());
    }

    @isTest
    private static void testShareFailure(){
        GoogleDocMockResponse googleResponse = new GoogleDocMockResponse();
        googleResponse.statusCode = 200;
        Test.setMock(HttpCalloutMock.class, googleResponse);
        Account act = CircleTestDataFactory.insertAccount();
        Opportunity opp = CircleTestDataFactory.insertOpportunity(act.id, 'Name', Date.today(), 'Institutional Trading Partnership');
        googleResponse.statusCode = 400;
        Test.setMock(HttpCalloutMock.class, googleResponse);
        test.startTest();
            HttpResponse res = GoogleDocAPI.shareNewDocument('1234567');
        test.stopTest();

        System.assertEquals(null, res);
    }


    @isTest
    private static void testBatchUpdate(){
        GoogleDocMockResponse googleResponse = new GoogleDocMockResponse();
        googleResponse.statusCode = 200;
        Test.setMock(HttpCalloutMock.class, googleResponse);
        Account act = CircleTestDataFactory.insertAccount();
        Opportunity opp = CircleTestDataFactory.insertOpportunity(act.id, 'Name', Date.today(), 'Institutional Trading Partnership');

        test.startTest();
            HttpResponse res = GoogleDocAPI.batchUpdate('1234',opp.id,null);
        test.stopTest();

        System.assertEquals('application/json', res.getHeader('Content-Type'));
        System.assertEquals('{"documentId":"1234567", "id":"1234567"}', res.getBody());
        System.assertEquals(200, res.getStatusCode());
        opp = [SELECT ID, Partnership_Construct_Document_ID__c FROM Opportunity WHERE ID = :opp.id];
        System.assertEquals('1234567', opp.Partnership_Construct_Document_ID__c);
    }

    @isTest
    private static void testBatchUpdateFailure(){
        GoogleDocMockResponse googleResponse = new GoogleDocMockResponse();
        googleResponse.statusCode = 400;
        Test.setMock(HttpCalloutMock.class, googleResponse);

        Account act = CircleTestDataFactory.insertAccount();
        Opportunity opp = CircleTestDataFactory.insertOpportunity(act.id, 'Name', Date.today(), 'Institutional Trading Partnership');

        test.startTest();
            HttpResponse res = GoogleDocAPI.batchUpdate('1234',opp.id,null);
        test.stopTest();
        
        System.assertEquals(null, res);
        opp = [SELECT ID, Partnership_Construct_Document_ID__c FROM Opportunity WHERE ID = :opp.id];
        System.assertEquals(null, opp.Partnership_Construct_Document_ID__c);
    }
}