force-app/main/default/objects/Opportunity/fields/MeW_Timeframe_in_months__c.field-meta.xml
<CustomField>
    <fullName>MeW_Timeframe_in_months__c</fullName>
    <label>MeW Timeframe (in months)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Monthly_Active_Users__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Active_Users__c</fullName>
    <description>Used for Performance and Activation Incentives</description>
    <label>Monthly Active Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_MeWs_Growth__c.field-meta.xml
<CustomField>
    <fullName>Projected_MeWs_Growth__c</fullName>
    <label>Projected MeWs Growth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_Stablecoin_On_Platform_Growth__c.field-meta.xml
<CustomField>
    <fullName>Projected_Stablecoin_On_Platform_Growth__c</fullName>
    <label>Projected Stablecoin On Platform Growth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Projected_Total_Stablecoin_Volume__c.field-meta.xml
<CustomField>
    <fullName>Projected_Total_Stablecoin_Volume__c</fullName>
    <label>Projected Total Stablecoin Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stablecoin_On_Pltfrm_Timeframe_months__c.field-meta.xml
<CustomField>
    <fullName>Stablecoin_On_Pltfrm_Timeframe_months__c</fullName>
    <label>Stablecoin On Pltfrm Timeframe (months)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stablecoin_Volume_Timeframe_in_months__c.field-meta.xml
<CustomField>
    <fullName>Stablecoin_Volume_Timeframe_in_months__c</fullName>
    <label>Stablecoin Volume Timeframe (in months)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Success_Metrics_Details__c.field-meta.xml
<CustomField>
    <fullName>Success_Metrics_Details__c</fullName>
    <description>Required if Success Metrics = Other</description>
    <inlineHelpText>Required if Success Metrics = Other</inlineHelpText>
    <label>Success Metrics Details</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Success_Metrics_Tracking__c.field-meta.xml
<CustomField>
    <fullName>Success_Metrics_Tracking__c</fullName>
    <description>What are the measurable indicators of success for this plan/deal? Every deal needs a clear articulation of shared metrics and success criteria. What will we be tracking to measure the success of this deal, how will we track the metrics, who is responsible for tracking the metrics, and how will it be communicated? Example: We will track USDC on platform toward the 30% lift goal and we will use partner-reported data to track toward the 20% lift target for MEWs. Both will be reported on a monthly basis over the 6 month term of the campaign.</description>
    <inlineHelpText>What will we be tracking to measure the success of this deal, how will we track the metrics, who is responsible for tracking the metrics, and how will it be communicated? Example: We will track USDC on platform toward the 30% lift goal and we will use partner-reported data to track toward the 20% lift target for MEWs. Both will be reported on a monthly basis over the 6 month term of the campaign.</inlineHelpText>
    <label>Success Metrics Tracking</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/Partnership_Objective__c.object-meta.xml
<CustomObject>
    <description>Track the key objectives of our customer relationships</description>
    <label>Partnership Objective</label>
    <nameField>
        <label>Partnership Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partnership Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partnership_Objective__c/fields/Data_Pulled_From_Opportunity_Datestamp__c.field-meta.xml
<CustomField>
    <fullName>Data_Pulled_From_Opportunity_Datestamp__c</fullName>
    <label>Data Pulled From Opportunity Datestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/MeW_Timeframe_in_months__c.field-meta.xml
<CustomField>
    <fullName>MeW_Timeframe_in_months__c</fullName>
    <description>Projected number of months to realize the Projected MeWs target.</description>
    <inlineHelpText>Projected number of months to realize the Projected MeWs target.</inlineHelpText>
    <label>MeW Timeframe (in months)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Monthly_Active_Users__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Active_Users__c</fullName>
    <label>Monthly Active Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is optional, but should be filled in most cases since the majority of objectives will stem from a specific Opportunity</description>
    <inlineHelpText>This field is optional, but should be filled in most cases since the majority of objectives will stem from a specific Opportunity</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Partnership Objectives</relationshipLabel>
    <relationshipName>Partnership_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Projected_MeWs_Growth__c.field-meta.xml
<CustomField>
    <fullName>Projected_MeWs_Growth__c</fullName>
    <description>Projected incremental MeWs added during the timeframe of the objective</description>
    <inlineHelpText>Projected incremental MeWs added during the timeframe of the objective</inlineHelpText>
    <label>Projected MeWs Growth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Projected_Stablecoin_On_Platform_Growth__c.field-meta.xml
<CustomField>
    <fullName>Projected_Stablecoin_On_Platform_Growth__c</fullName>
    <description>Projected incremental stablecoin on platform growth during the timeframe of the objective</description>
    <inlineHelpText>Projected incremental stablecoin on platform growth during the timeframe of the objective</inlineHelpText>
    <label>Projected Stablecoin On Platform Growth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Projected_Total_Stablecoin_Volume__c.field-meta.xml
<CustomField>
    <fullName>Projected_Total_Stablecoin_Volume__c</fullName>
    <description>Projected aggregate stablecoin transaction volume during the timeframe of the objective</description>
    <inlineHelpText>Projected aggregate stablecoin transaction volume during the timeframe of the objective</inlineHelpText>
    <label>Projected Total Stablecoin Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Stablecoin_On_Pltfrm_Timeframe_months__c.field-meta.xml
<CustomField>
    <fullName>Stablecoin_On_Pltfrm_Timeframe_months__c</fullName>
    <label>Stablecoin On Pltfrm Timeframe (months)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Stablecoin_Volume_Timeframe_in_months__c.field-meta.xml
<CustomField>
    <fullName>Stablecoin_Volume_Timeframe_in_months__c</fullName>
    <label>Stablecoin Volume Timeframe (in months)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Success_Metrics_Details__c.field-meta.xml
<CustomField>
    <fullName>Success_Metrics_Details__c</fullName>
    <description>Alternative metrics defined in the Partnership Construct that do no fit within our predefined templates.</description>
    <inlineHelpText>Alternative metrics defined in the Partnership Construct that do no fit within our predefined templates.</inlineHelpText>
    <label>Success Metrics Details</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Partnership_Objective__c/fields/Success_Metrics_Tracking__c.field-meta.xml
<CustomField>
    <fullName>Success_Metrics_Tracking__c</fullName>
    <label>Success Metrics Tracking</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/PartnershipObjectivePullOppMetricsBatch.cls
global class PartnershipObjectivePullOppMetricsBatch implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT ID,Data_Pulled_From_Opportunity_Datestamp__c,MeW_Timeframe_in_months__c,Projected_Mews_Growth__c,Stablecoin_Volume_Timeframe_in_months__c,Projected_Total_Stablecoin_Volume__c,Stablecoin_On_Pltfrm_Timeframe_months__c,Projected_Stablecoin_on_Platform_Growth__c,Monthly_active_users__C,Success_Metrics_Details__c,Success_Metrics_Tracking__C, Opportunity__r.MeW_Timeframe_in_months__c, Opportunity__r.Monthly_active_users__C, Opportunity__r.Projected_Mews_Growth__c, Opportunity__r.Projected_Total_Stablecoin_Volume__c, Opportunity__r.Projected_Stablecoin_on_Platform_Growth__c, Opportunity__r.Stablecoin_Volume_Timeframe_in_months__c, Opportunity__r.Stablecoin_On_Pltfrm_Timeframe_months__c, Opportunity__r.Success_Metrics_Details__c, opportunity__r.Success_Metrics_Tracking__C FROM Partnership_Objective__c Where Opportunity__r.LastModifiedDate = LAST_N_DAYS:2';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<Partnership_Objective__c> objectives) {
        for(Partnership_objective__c objective : objectives){
            Boolean updated = false;
            if(objective.MeW_Timeframe_in_months__c == null && objective.opportunity__r.MeW_Timeframe_in_months__c != null){
                objective.MeW_Timeframe_in_months__c = objective.opportunity__r.MeW_Timeframe_in_months__c;
                updated = true;
            }
            if(objective.Projected_Mews_Growth__c == null && objective.opportunity__r.Projected_Mews_Growth__c != null){
                objective.Projected_Mews_Growth__c = objective.opportunity__r.Projected_Mews_Growth__c;
                updated = true;
            }
            if(objective.Stablecoin_Volume_Timeframe_in_months__c == null && objective.opportunity__r.Stablecoin_Volume_Timeframe_in_months__c != null){
                objective.Stablecoin_Volume_Timeframe_in_months__c = objective.opportunity__r.Stablecoin_Volume_Timeframe_in_months__c;
                updated = true;
            }
            if(objective.Projected_Total_Stablecoin_Volume__c == null && objective.opportunity__r.Projected_Total_Stablecoin_Volume__c != null){
                objective.Projected_Total_Stablecoin_Volume__c = objective.opportunity__r.Projected_Total_Stablecoin_Volume__c;
                updated = true;
            }
            if(objective.Stablecoin_On_Pltfrm_Timeframe_months__c == null && objective.opportunity__r.Stablecoin_On_Pltfrm_Timeframe_months__c != null){
                objective.Stablecoin_On_Pltfrm_Timeframe_months__c = objective.opportunity__r.Stablecoin_On_Pltfrm_Timeframe_months__c;
                updated = true;
            }
            if(objective.Projected_Stablecoin_on_Platform_Growth__c == null && objective.opportunity__r.Projected_Stablecoin_on_Platform_Growth__c != null){
                objective.Projected_Stablecoin_on_Platform_Growth__c = objective.opportunity__r.Projected_Stablecoin_on_Platform_Growth__c;
                updated = true;
            }
            if(objective.Monthly_active_users__C == null && objective.opportunity__r.Monthly_active_users__C != null){
                objective.Monthly_active_users__C = objective.opportunity__r.Monthly_active_users__C;
                updated = true;
            }
            if(objective.Success_Metrics_Details__c == null && objective.opportunity__r.Success_Metrics_Details__c != null){
                objective.Success_Metrics_Details__c = objective.opportunity__r.Success_Metrics_Details__c;
                updated = true;
            }
            if(objective.Success_Metrics_Tracking__C == null && objective.opportunity__r.Success_Metrics_Tracking__C != null){
                objective.Success_Metrics_Tracking__C = objective.opportunity__r.Success_Metrics_Tracking__C;
                updated = true;
            }
            if(updated){
                objective.Data_Pulled_From_Opportunity_Datestamp__c = Datetime.now();
            }
        }
        update objectives;
    }
    
    global void finish(Database.BatchableContext bc) {
    }
}