force-app/main/default/objects/Opportunity/fields/Needs_Attachmnet_Recalculation__c.field-meta.xml
<CustomField>
    <fullName>Needs_Attachmnet_Recalculation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Needs Attachmnet Recalculation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Number_Of_Attachments__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Attachments__c</fullName>
    <label>Number Of Attachments</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OpportunityDAO.cls
public class OpportunityDAO {

    public static List<Opportunity> getOpportunitiesById(Set<Id> ids){
        return [SELECT ID, OwnerId, Name FROM Opportunity WHERE ID IN :ids];
    }

    public static List<Opportunity> getOpportunitiesWithAttachmentCount(Set<Id> ids){
        return [SELECT ID, Number_Of_Attachments__c, Needs_Attachmnet_Recalculation__c FROM Opportunity WHERE ID in :ids];
    }

    public static List<OpportunityTeamMember> getCSMOppTeamMembers(Set<Id> ids){
        return [SELECT ID, OpportunityId FROM OpportunityTeamMember WHERE OpportunityId IN :ids and TeamMemberRole = 'Customer Success Manager'];

    }
}