force-app/main/default/objects/Support_Settings__c/Support_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Support Settings</label>
</CustomObject>

force-app/main/default/objects/Support_Settings__c/fields/NetworkId__c.field-meta.xml
<CustomField>
    <fullName>NetworkId__c</fullName>
    <label>NetworkId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InvokePortalUserEmailVerification.cls
public class InvokePortalUserEmailVerification {
    @InvocableMethod(label='InvokePortalUserEmailVerification' description='Send portal user verification email')
    public static void sendVerificationEmail(List<String> portalUserId) {
        Support_Settings__c ss = Support_Settings__c.getInstance();
        System.UserManagement.sendAsyncEmailConfirmation(portaluserId.get(0),null,ss.NetworkId__c,'/EmailVerified');
    }
}